### ISSUE TITLE
use per-resource type sg_id types (and warn about mismatches)

### ISSUE THREAD

**Issue by floooh** [floooh/sokol#10]
Instead of a generic sg_id there should be sg_buffer_id, sg_image_id, etc...

**Comment by floooh** [comment]
...I guess a better name would simply be sg_buffer, sg_image, etc... without the '_id'

**Comment by floooh** [comment]
done, but I need to figure out how to get the compilers emit warnings when assigning using the wrong type (since everything is uint32_t underneath at least clang doesn't complain when using a sg_image when an sg_buffer is expected, etc...

**Comment by amerkoleci** [comment]
What about typedef handle like vulkan?

**Comment by pervognsen** [comment]
Typedefs are just aliases so they're not going to offer type safety. You'll want a struct for each id type, like struct sg_buffer { int32_t id; };

**Comment by floooh** [comment]
I'll try this, and also will have a look at the Vulkan headers, thanks!

**Comment by amerkoleci** [comment]
You can use something similar to VK_DEFINE_HANDLE then have the struct implemented per backend, under opengl it would be, for example sg_buffer_id with gl handle and some other props you need.

**Comment by floooh** [comment]
Ok I wrapped the id into a struct, and type checking works now... let's see how (in-)convenient this will be with designed-initialisers though...

**Comment by floooh** [comment]
reminder feedback from @pervognsen:

- To reply to your final comment (since I can't reply to closed issues): API users shouldn't need to deal with the id fields.

- Just the structs as a whole. And for sentinels, you can do e.g. #define SG_BUFFER_NONE ((sg_buffer){0}) with C99 compound literals.
