### ISSUE TITLE
[sokol_app] A call to GetIntegerv in _sapp_wgl_create_context leaves the stack corrupted

### ISSUE THREAD

**Issue by rcases** [floooh/sokol#1005]
It can be solved by changing the call convention of GetIntegerv to WINAPI:

```void WINAPI (*GetIntegerv)(uint32_t pname, int32_t* data);```
and
```_sapp.wgl.GetIntegerv = (void WINAPI (*)(uint32_t, int32_t*)) GetProcAddress(_sapp.wgl.opengl32, "glGetIntegerv");```

**Comment by floooh** [comment]
Looks like an oversight on my side, but interesting that it didn't show up during testing. What compiler are you using?

**Comment by floooh** [comment]
Ok, should be fixed now. I moved the WINAPI macro inside `(*)` as in the other GL loader definitions.

Curious though that I wasn't able to reproduce the stack corruption, neither in debug nor release mode (tested with MSVC).

**Comment by floooh** [comment]
Are you compiling for 32-bits x86 maybe? E.g. I'm seeing this in the MSVC docs:

> All __stdcall functions must have prototypes. This calling convention is only available in compilers that target x86, and is ignored by compilers that target other architectures.

...might explain why it didn't crash for me because I'm not testing 32-bit builds anymore.

**Comment by rcases** [comment]
> Are you compiling for 32-bits x86 maybe? E.g. I'm seeing this in the MSVC docs:
> 
> > All __stdcall functions must have prototypes. This calling convention is only available in compilers that target x86, and is ignored by compilers that target other architectures.
> 
> ...might explain why it didn't crash for me because I'm not testing 32-bit builds anymore (at least 32-bits x86, technically WASM is 32-bits).

Yes, I am compiling at 32-bits x86.

**Comment by floooh** [comment]
Ah ok, that explains it at least. Is there a specific reason for using 32-bit builds though? E.g. in my last job we supported old Windows versions for much longer than even Microsoft did, and we dropped 32-bit support in 2017 and Windows XP support around 2020 or so :)

**Comment by floooh** [comment]
Ah ok makes sense. If you stumble over additional problem please open new tickets. I don't want to "officially" support 32-bit x86, but if it's only about minor things like this then there's no harm in fixing the issues :)
