### ISSUE TITLE
Apps showcase

### ISSUE THREAD

**Issue by RuiVarela** [floooh/sokol#1014]
Hello,

Thank you for this great framework, here are some open source projects I've based on your libs:

- [hIghQube](https://github.com/RuiVarela/hIghQube) A game demo that used sokol rendering extensively 
- [Senos](https://github.com/RuiVarela/Senos) A music app that uses sokol as backend

Thanks

**Comment by floooh** [comment]
Nice! Can I put those into the sokol readme in the 'examples and related projects' section?

**Comment by RuiVarela** [comment]
@floooh sure, please do,
Thanks
