### ISSUE TITLE
README gives no indication of what this library does

### ISSUE THREAD

**Issue by gmofishsauce** [floooh/sokol#1032]
The top-level README does not contain a single word about the _purpose_ of this library. This is both elegant and hilarious. Should the README be modified to say something like "...**graphics** library"? Or _something_? ;-)

**Comment by floooh** [comment]
Right at the top:

| Simple [STB-style](https://github.com/nothings/stb/blob/master/docs/stb_howto.txt) cross-platform libraries for C and C++, written in C.

...and just a bit further down:

- [sokol_gfx.h](https://github.com/floooh/sokol/blob/master/sokol_gfx.h): 3D-API wrapper (GL/GLES3/WebGL2 + Metal + D3D11 + WebGPU)
- [sokol_app.h](https://github.com/floooh/sokol/blob/master/sokol_app.h): app framework wrapper (entry + window + 3D-context + input)
- ...
