### ISSUE TITLE
[sokol_gfx] Any plans to support base vertex location?

### ISSUE THREAD

**Issue by jakubtomsu** [floooh/sokol#1033]
When using a single big vertex+index buffer to store multiple meshes, it would be useful if `sg.draw` also had a base vertex location parameter. This way it wouldn't be necessary to pre-process the index buffers and add the offsets manually. So essentially the GPU would load vertex from `index_buffer[i] + vertex_offset`.

This feature is supported in [D3D11](https://learn.microsoft.com/en-us/windows/win32/api/d3d11/nf-d3d11-id3d11devicecontext-drawindexedinstanced) and [OpenGL](https://registry.khronos.org/OpenGL-Refpages/gl4/html/glDrawElementsBaseVertex.xhtml) 3.2+, however I'm not sure if all other APIs sokol targets support it. Maybe each backend could report an error if the base_vertex parameter is used and not supported. There could also be a way to query the support.

Another issue is that adding a new parameter to `sg_draw` would break existing code, which isn't very good considering how important this function is...

**Comment by jakubtomsu** [comment]
I just noticed `vertex_buffer_offsets` from `Bindings` struct, I guess that does something similar? It would still be nice to have that info on a per-draw basis, but this could also be useful...

**Comment by jakubtomsu** [comment]
Right, that's cool. However I'm mostly concerned with D3D11, which seems to bind everything all the time at the moment... (unless the runtime/driver can skip it?)

I think I'll just do apply_bindings every time for now, the renderer uses instancing as much as possible so the number of draw calls should be low anyway. If I run into perf issues I could just write the hot inner loop with d3d11 directly by bypassing sokol

**Comment by floooh** [comment]
>  However I'm mostly concerned with D3D11

...yeah I didn't specifically benchmark yet how much filtering redundant bindings would actually help in D3D11, but I really don't think it's a performance issue. First, D3D11 already uses 'batched' bindings calls (e.g. all bindings of one type and shader stage are applied with a single D3D11 call), and second, IME D3D11 is really well optimized internally, so if it helps I would expect that they do the redundant-bindings-filtering internally.

**Comment by floooh** [comment]
PS: what *might* make sense in D3D11 though is skipping the D3D11 binding calls by resource types... e.g. if you call `sg_apply_bindings()` with only the vertex offsets changes, don't do the other binding calls (IASetIndexBuffer, VSSetShaderResources, PSSetShaderResources, VSSetSamplers, PSSetSamplers).

...e.g. if you find that writing the hot inner loop directly in D3D11 is significantly faster because of those redundant bind calls, just holler and we can figure something out.

**Comment by floooh** [comment]
> Also I just found out the vertex_buffer_offsets don't seem to work with indexed meshes (at least on D3D11), which is unfortunate...

Hmm, it should. This sample is using indices:

https://github.com/floooh/sokol-samples/blob/master/sapp/bufferoffsets-sapp.c

Also the sokol_imgui.h header is using both vertex_buffer_offsets and index_buffer_offset:

https://github.com/floooh/sokol/blob/c2bb83f0b35e09d97a354b5f4cf4c3df783c4193/util/sokol_imgui.h#L2682-L2684

Your index ranges for a 'submesh' need to be zero-based though. E.g. an index 0 points to the vertex at the vertex_buffer_offset.

**Comment by floooh** [comment]
PS:

> So essentially the GPU would load vertex from index_buffer[i] + vertex_offset.

That's what's happening, except that the vertex_offset counted in bytes, not in 'number of vertices'. Maybe that's the problem?

**Comment by jakubtomsu** [comment]
Right, I understand the offset is in bytes and the vertex indices are zero based, so it looks like I was just doing something wrong. Thanks for the examples!

**Comment by floooh** [comment]
If you still discover a bug with the buffer offsets, let me know!
