### ISSUE TITLE
Missing ETC_R11 format

### ISSUE THREAD

**Issue by julhe** [floooh/sokol#1041]
I tried to find the single-channel format from the ETC family, but only found the two-channel variant (``SG_PIXELFORMAT_ETC2_RG11``). For the BC family, there is BC4, so I guess it would make sense to have ETC2_R11 as well.

**Comment by floooh** [comment]
Hmm yeah, strange that I overlooked that since the two-channel variants are there...

Technically those should probably be changed to `EAC_*` though, see the WebGPU extension (https://www.w3.org/TR/webgpu/#texture-compression-etc2).

**Comment by floooh** [comment]
Ok fixed in https://github.com/floooh/sokol/pull/1044

I actually also found a bug in the WebGPU backend where the RG11 formats were mapped to the wrong WebGPU texture formats.
