### ISSUE TITLE
Best way of enabling shader debugging for D3D11?

### ISSUE THREAD

**Issue by hsjunnesson** [floooh/sokol#1043]
Currently, sokol_gfx will call `d3dcompile()` with the flags `D3DCOMPILE_PACK_MATRIX_COLUMN_MAJOR | D3DCOMPILE_OPTIMIZATION_LEVEL3` which makes it very difficult to debug step through shaders in RenderDoc or other debuggers.
I resorted to this, but I feel there might be a better way of doing this?

```
	UINT flags1 = D3DCOMPILE_PACK_MATRIX_COLUMN_MAJOR;
	
	#if defined(SOKOL_DEBUG)
		flags1 |= D3DCOMPILE_DEBUG | D3DCOMPILE_SKIP_OPTIMIZATION;
	#else
		flags1 |= D3DCOMPILE_OPTIMIZATION_LEVEL3;
	#endif
```

The shader is compiled via sokol-shdc.

**Comment by floooh** [comment]
Ah hmm right, maybe we need a runtime option for that in sg_shader_desc. For Metal it's enough to run sokol-shdc without the --binary option (e.g. MSL shaders are passed into sokol-gfx as sources, not as binary blobs), this is enough to enable source level debugging in the Xcode Metal debugger. But I rarely tried source-level debugging for D3D11.

**Comment by hsjunnesson** [comment]
I'll let you cook. But like your example with Metal, I feel that this is pretty dependent on the specific backend. I havn't found a tool that lets me source debug shaders with OpenGL, so that's maybe a moot point for that backend. Vulkan will probably have seventeen different flavors of optimization flags and debuggability extensions, so maybe one global flag isn't enough there?

**Comment by floooh** [comment]
We can incrementally solve those backend-specific issues, and there's also no need to wrap this all under a single backend-agnostic flag, it's ok to have backend-specific flags in the desc structs as long as ignoring them doesn't break anything.

**Comment by Ignitron** [comment]
I have the same issue, shaders can't be decompiled...

**Comment by floooh** [comment]
Working on a solution now, I'm adding a `.d3d11_shader_debugging` boolean to `sg_desc` which then uses the `D3DCOMPILE_DEBUG | D3DCOMPILE_SKIP_OPTIMIZATION` for all shaders that are provided as HLSL source code. Works nicely:

![image](https://github.com/user-attachments/assets/e1e9dcb8-c2b9-479a-af04-ddd1152536e3)

**Comment by floooh** [comment]
Ok, fixed via https://github.com/floooh/sokol/pull/1101
