### ISSUE TITLE
sokol_audio.h: capture input

### ISSUE THREAD

**Issue by digitalsignalperson** [floooh/sokol#1054]
Low priority, but any thoughts on adding basic audio input capture?

E.g. with miniaudio: https://miniaud.io/docs/examples/simple_duplex.html

**Comment by floooh** [comment]
TBH I don't want to add any big feature areas to sokol_audio.h, for anything more advanced using miniaudio.h might indeed be the better option :)

**Comment by digitalsignalperson** [comment]
Roger that, yeah I've started experimenting with miniaudio and it's pretty impressive!
