### ISSUE TITLE
Right shift is recognized as "invalid key" on Windows.

### ISSUE THREAD

**Issue by skejeton** [floooh/sokol#1076]
Any event related to right shift will fire, but it will use `SAPP_KEYCODE_INVALID`

**Comment by skejeton** [comment]
This is a bigger problem - sokol uses OEM dependent scancodes from bits 16-23 of lParam. It should instead read the virtual codes from wParam.

**Comment by skejeton** [comment]
(Nevermind, most OEM's seem to use a standard layout, but then the unhelpful graphic they provide is very unclear on what keys are on the right side)

**Comment by floooh** [comment]
Hmm, it works here on a Win10 Asus laptop, and Win10 gaming PC. Do you have something special in your keyboard setup, some special keyboard hardware or layout?

IIRC the key input code for Windows was a mix of Oryol and an older version of GLFW, but GLFW has diverged quite a bit in the meantime. It might make sense to harmonize keyboard input with more recent GLFW code (I definitely want GLFW and sokol_app.h to behave mostly the same).

Do you see the same problem in browsers? E.g. https://floooh.github.io/sokol-html5/events-sapp.html

**Comment by skejeton** [comment]
Nope. However, I figured out something - right shift fires 0x136 instead of 0x36.

**Comment by skejeton** [comment]
I found the solution, instead of `(int)(HIWORD(lParam)&0x1FF)` do `(int)(HIWORD(lParam)&0xFF)`

**Comment by skejeton** [comment]
Yep, that works. I think that's just an edge case on my external keyboard. Sorry for making mess of a comment list here, I was figuring things out on the go.

**Comment by skejeton** [comment]
I opened a pull request at #1077. Thank you for help ^^

**Comment by floooh** [comment]
Ah yeah, I was gonna recommend adding new entries to the lookup table, that's definitely the quickest solution.

I'll merge it right away, one sec...

**Comment by skejeton** [comment]
Thank you very much :)!
