### ISSUE TITLE
attributeless rendering support

### ISSUE THREAD

**Issue by digitalsignalperson** [floooh/sokol#1084]
For many cases, instead of providing explicit vertex and index buffers, it's "free" to calculate the geometry in the vertex shader based on gl_VertexIndex and gl_InstanceIndex. 

With sokol_gfx & sokol-shdc I could only achieve doing this by a couple tricks:
- have to create and bind at least one dummy buffer or else fails validation
- I couldn't get gl_InstanceIndex to work without including another dummy attribute with SG_VERTEXSTEP_PER_INSTANCE set, and ensuring it doesn't get optimized out of the shader by doing something like `color.r += in_dummy * 0.000000001f`.

Are there any ways to avoid those extra steps?

**Comment by floooh** [comment]
Are you on an older sokol-gfx version? The 'storage buffer update' from May-2024 (https://github.com/floooh/sokol/blob/master/CHANGELOG.md#09-may-2024) also contains fixes to allow attribute less rendering.

For instance here's the 'bufferless triangle' sample, which also works on the GLES3 backends:

https://floooh.github.io/sokol-html5/triangle-bufferless-sapp.html

C source: https://github.com/floooh/sokol-samples/blob/master/sapp/triangle-bufferless-sapp.c

Shader code: https://github.com/floooh/sokol-samples/blob/master/sapp/triangle-bufferless-sapp.glsl

...all the other 'attribute-less' samples use storage buffers to provide the vertex data instead, and don't work on all backends (notably macOS with GL, and all the GLES3 backends).

For instance here's the cube sample modified to use vertex pulling from a storage buffer:

C: https://github.com/floooh/sokol-samples/blob/master/sapp/vertexpull-sapp.c
Shader: https://github.com/floooh/sokol-samples/blob/master/sapp/vertexpull-sapp.glsl

For more info, also see this blog post: https://floooh.github.io/2024/05/06/sokol-storage-buffers.html

**Comment by digitalsignalperson** [comment]
Oh cool I didn't realize the storage buffers update covered this. I had things pinned just at April 2024 so I'll have to go update. Thanks for all the links and info!

Looking forward to more platform/browser support coming for webgpu too. Bummed that for linux it's behind unsafe flags in chrome, or nightlies only for firefox
