### ISSUE TITLE
A comment on `hooks`

### ISSUE THREAD

**Issue by septag** [floooh/sokol#109]
I've been following your new commits on ```dbgui``` branch and I think it's a great idea that you are planning to add hooks for debugging purposes. I've been planning to do it myself but now I'm gonna wait for this update.

So i just had a little suggestion if you are interested.  We could have a macro function to filter those ```if``` checks for hooks all together in release builds. much like ```assert``` macro.

thank you!

**Comment by floooh** [comment]
Yes, a similar thought occured to me when writing the stuff. I would most likely put it behind a new define (something like SOKOL_NO_TRACE_HOOKS).
