### ISSUE TITLE
Add extern "C" declarations for C++ users

### ISSUE THREAD

**Issue by swiftcoder** [floooh/sokol#11]
Sokol doesn't play terribly nice with C++ compilers. Rather than forcing C++ consumers to fiddle with the header files, it would be nice to wrap the entire library in `extern "C"` guards:

```
#ifdef __cplusplus
extern "C" {
#endif

// ...

#ifdef __cplusplus
}
#endif
```

Note that stb_* libraries do exactly this: https://github.com/nothings/stb/blob/master/stb_image.h#L323

**Comment by floooh** [comment]
Done, but please note that compile problems may currently be caused by not strictly following a C standard (e.g. on GCC). This will eventually be fixed of course.
