### ISSUE TITLE
Intrusive GPU profiler

### ISSUE THREAD

**Issue by Alzathar** [floooh/sokol#110]
Hello,

I saw you are working on debug-inspection extensions and this reminds me I would like to implement an intrusive GPU profiler for Sokol. The idea would be to adapt the intrusive GPU profiler proposed in the project [Dx11Base](https://github.com/sebh/Dx11Base) and extending it for OpenGL, Metal, and WebGL (if possible). The ImGui UI can stay the same.

Do you think this would be an interesting feature?

**Comment by floooh** [comment]
Yes sounds like an interesting feature, maybe add a minimal amount of instrumentation code to the sokol_gfx.h backends, and then have a separate header to render an UI via ImGui...

If you are experimenting in that direction, please keep me updated, I'd be interested how the backend integration would need to look like and I think it makes sense to add this functionality to "core sokol_gfx.h".

**Comment by Alzathar** [comment]
I agree to have specific instrumentation code in sokol_gfx and the rest in a separate header for the UI.

Regarding the API, it can be very similar than the one proposed in DX11Base.
 
```c++
// Add a member in the structure `sg_desc` to enable the GPU profiler. For example:
sg_desc desc();
desc.enable_gpu_profiler = true; // This will initialize the backend in consequence
sg_setup(&desc);
```

In the public API four new functions will be proposed and two macros
```c++
// - sg_gpu_profiler_start_frame(): start to sample the content of a frame
// - sg_gpu_profiler_start_timer(const char *name, unsigned r, unsigned g, unsigned b, unsigned a): create a main timer to sample the content of a frame
// - sg_gpu_profiler_stop_timer(const char *name): stop the timer previously started using its name
// - sg_gpu_profiler_end_frame(): stop to sample the content of a frame
```

The macros simplifies the creations of timer to sample specific parts of the rendering.
```c++
// - SOKOL_GPU_SCOPED_TIMEREVENT(name, r, g, b, a): Create a new event to sample in a frame and start a timer
// - SOKOL_GPU_SCOPED_TIMER(name, r, g, b, a): Create a new timer to sample a part of an event.
```

To give you an example of this API (and largely based on the code proposed in DX11Base),

```c++
// render loop
while (true) {
  // Start a new frame to sample 
  sg_gpu_profiler_start_frame();
  const char* frameGpuTimerName = "Frame";
  sg_gpu_profiler_start_timer(frameGpuTimerName, 150, 150, 150)
  // Sample specific parts
  GPU_SCOPED_TIMEREVENT(GameRender, 75, 75, 75);
  {
    GPU_SCOPED_TIMER(Clear, 34, 177, 76);
    sg_begin_default_pass(&pass_action, cur_width, cur_height);
  }
  {
    GPU_SCOPED_TIMER(Shadow, 128, 128, 255);
    {
      GPU_SCOPED_TIMER(ShadowCasc0, 64, 64, 255);
      {
        GPU_SCOPED_TIMER(Shadow0, 64, 0, 255);
        // The GPU code to sample
     }
     {
        GPU_SCOPED_TIMER(PartShad0, 0, 64, 255);
        // The GPU code to sample
    }
    // Continue this for the rest of your code
  }
  // After sg_commit()
  sg_gpu_profiler_stop_timer(frameGpuTimerName);
  sg_gpu_profiler_end_frame();
}
```

The result could looks likes [this](https://raw.githubusercontent.com/sebh/Dx11Base/master/DX11Application.png) using the UI proposed in DX11Base.

For the internal structures, again the ones proposed by DX11Base are very well done and use internally a graph (see the content of the class [DxGpuPerformance](https://github.com/sebh/Dx11Base/blob/master/DX11Base/Dx11Device.h#L429)). However, some lines must be replaced to be specific to each backend. For example, [here](https://github.com/sebh/Dx11Base/blob/master/DX11Base/Dx11Device.h#L479) and [here](https://github.com/sebh/Dx11Base/blob/master/DX11Base/Dx11Device.h#L499-L501).

I have not yet thought about the structures to implement for each backend.

**Comment by septag** [comment]
I haven't tried it myself but what I've experienced from using [remotery](https://github.com/Celtoys/Remotery), metal API does not support per API call profiling and can only sample the whole command buffer.

**Comment by Alzathar** [comment]
@septag Good catch! That would mean than specifically for the Metal backend the macros SOKOL_GPU_SCOPED_TIMEREVENT and SOKOL_GPU_SCOPED_TIMER will have not no effect (e.g. defined empty).

The profiler will return only the the time associated with a sample ("Frame" in my example), but not the events inside.

**Comment by Alzathar** [comment]
FYI, I continued my review of available intrusive GPU profilers. I found [tracy](https://bitbucket.org/wolfpld/tracy) and this is more than I expected (CPU / GPU / memory profiler), plus the author is working on a docking version (see this [screenshot](https://user-images.githubusercontent.com/600573/54481622-40dae800-4837-11e9-9a21-14251271c15c.png)).

It seems irrelevant for me to work on another profiler but someone might has counter arguments against this!

My main question now is about the possibility to see the sokol trace hook API with tracy

**Comment by Alzathar** [comment]
Another GPU profiler with a Dear ImGui user interface: https://github.com/dougbinks/microprofile

![Avoyd_2019-06-22_enkiTS_microprofile.jpg](https://raw.githubusercontent.com/juliettef/Media/master/Avoyd_2019-06-22_enkiTS_microprofile.jpg)
