### ISSUE TITLE
Extend and cleanup supported pixel formats.

### ISSUE THREAD

**Issue by floooh** [floooh/sokol#112]
The list of pixel formats should be cleaned up so that it it contains a "core" of pixel formats that are supported in all backends, and a more relaxed list of optional backend-specific pixel formats for which support must be queried (similar to how the compressed texture formats are currently handled).

There's also the problem of renderable pixel formats vs pixel formats that are only supported for texturing, how should this be queried? Should we keep the simple sg_query_feature(...) and just extend the feature enum with new items? Or should there be a new query-feature method just for pixel formats, with additional query params (such as "renderable")?

**Comment by amerkoleci** [comment]
That makes sense, I think we should allow to query feature for every single format (core also) and have something to vulkan (vkGetPhysicalDeviceFormatProperties) and therefore know max size (width, height) and usage allowed, if sampled, render target, depth stencil etc

**Comment by floooh** [comment]
Hmm yes, probably a new ```sg_pixel_format_info sg_query_pixel_format_info(sg_pixel_format)``` function, this would return a struct with the most important info (what's in this struct should again be the common set of information available in the backend APIs. In OpenGL, at least some of this stuff can be queried via glGetIntegerv() (e.g. GL_MAX_TEXTURE_SIZE), others (like whether a pixel format is renderable) is (AFAIK) defined by the GL spec for a specific GL version.

**Comment by mattiasljungstrom** [comment]
Any plans to support linear output to screen framebuffers? (The naming conventions are a bit confusing, basically support for GL_FRAMEBUFFER_SRGB / EXT_framebuffer_sRGB)

**Comment by floooh** [comment]
>  Any plans to support linear output to screen framebuffers? (The naming conventions are a bit confusing, basically support for GL_FRAMEBUFFER_SRGB / EXT_framebuffer_sRGB)

I'm not sure if that's worth the trouble to be honest, is there any advantage versus doing the srgb->linear->srgb conversion in the pixel shader (I think the performance difference is negligable, even on mobile GPUs)?

**Comment by mattiasljungstrom** [comment]
Makes sense, I haven't actually tested the performance difference.

**Comment by floooh** [comment]
...work is happening here: https://github.com/floooh/sokol/tree/pixelformat

**Comment by floooh** [comment]
Closing this as duplicate for new issue: #187
