### ISSUE TITLE
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x90 in tid 20522 (ImageReader-640), pid 20416 (cent.yolov8ncnn)

### ISSUE THREAD

**Issue by lkjvzizh** [floooh/sokol#1125]
I deployed my own model to ncnn-android-yolov8 and debugged it to int winw_w=ANativeWindow_getWidth (win), which reported an error. Please seek help

**Comment by floooh** [comment]
Ok, so I found this project:

https://github.com/FeiGeChuanShu/ncnn-android-yolov8

...which has a line of code the line of code `int win_w = ANativeWindow_getWidth(win);`:

https://github.com/FeiGeChuanShu/ncnn-android-yolov8/blob/4ad0a7a19d8e2f24c805650e9d5b6fc93db04de1/ncnn-android-yolov8/app/src/main/jni/ndkcamera.cpp#L538

But that project doesn't use sokol_gfx.h, wrong project bud ;)
