### ISSUE TITLE
sokol_imgui update necessary for Dear ImGui v1.91.4

### ISSUE THREAD

**Issue by DctrNoob** [floooh/sokol#1135]
Dear Imgur changed the `ImTextureID` type from `void*` to `uint64_t` so an update of `sokol_imgui.h` is necessary. I created a PR for this: #1134.

It doesn't build at the moment because the referenced cimgui repo must be updated, too. I don't want to mess with your repos too much, so I leave that to you.

**Comment by floooh** [comment]
Looking into this now...

**Comment by floooh** [comment]
Ok #1134 has been merged. Thanks!
