### ISSUE TITLE
[Request] Possibility of setting framebuffer size independently of the window size

### ISSUE THREAD

**Issue by heretique** [floooh/sokol#1152]
I'm doing some tests on a RPI5 with Sokol and I noticed that as soon as I maximize windows or use fullscreen, performance drops abuptly as the size of the framebuffer grows (I'm using a 4k monitor). It become obviously to me that on that device I really need to be able to control framebuffer size to get acceptable performance from the GPU.
Is there a way to manually set a fixed framebuffer size independent of window size? Skimming though the code I didn't find any way of manually doing that or setting the DPI scale.

How hard it would be to implement such a feature? Is this something that I could do as a new contributor? (I have no knowledge of ObjC if I need to touch MacOS platform)

**Comment by floooh** [comment]
AFAIK controlling the default framebuffer size is not possible on some backends (thinking mostly of GL with GLX and WGL). The best solution might be to render to a fixed-size render target texture in an offscreen sokol-gfx render pass, and then in the swapchain pass render that texture as fullscreen rectangle with an as cheap as possible pixel shader which basically just copies the texture samples into the output color.

**Comment by heretique** [comment]
I see, worth to try this then. Thanks @floooh
