### ISSUE TITLE
sokol_imgui fails to build in sokol-samples

### ISSUE THREAD

**Issue by JanVelas** [floooh/sokol#1160]
Hello, I am having problems building with sokol_imgui.

To try and narrow down the issue I have decided to use the demo from https://github.com/floooh/sokol-samples which I know have worked for me some time ago.

I have pulled the repo and set the configuration to **sapp-win64-vstudio-debug** as per the README.

git clone https://github.com/floooh/sokol-samples
cd sokol-samples
./fips set config sapp-win64-vstudio-debug

Before building I made sure to delete and re-fetch the latest dependencies.

./fips fetch

I have then attempted to build the samples, but all of the imgui samples appeared to fail with the same set of errors.
I continued my search for problems while only building **imgui-sapp** from now on.

./fips make imgui-sapp

This produced following set of errors (edited to save space):

Building Custom Rule C:/Projekty/fips-workspace/sokol-samples/sapp/CMakeLists.txt
  imgui-sapp.cc
sokol_imgui.h(2668,13): error C2065: 'ImGuiPlatformIO': undeclared identifier 
sokol_imgui.h(2668,30): error C2065: 'pio': undeclared identifier 
sokol_imgui.h(2668,44): error C2039: 'GetPlatformIO': is not a member of 'ImGui' 
sokol_imgui.h(2668,44): error C3861: 'GetPlatformIO': identifier not found 
sokol_imgui.h(2672,9): error C2065: 'pio': undeclared identifier 
sokol_imgui.h(2673,9): error C2065: 'pio': undeclared identifier 
sokol_imgui.h(2889,42): error C2440: '=': cannot convert from 'uint64_t' to 'ImTextureID' 
[ERROR] Failed to build config 'sapp-win64-vstudio-debug' of project 'sokol-samples'

The last error seems related to https://github.com/floooh/sokol/issues/1082 (and commit 33185e4)

My understanding of C is very basic and I am unable to understand the cause at the moment.
I would appreciate if anyone could try to replicate this issue, or correct me.

I hope this is not some kind of misunderstanding on my part. :-)

Jan

**Comment by JanVelas** [comment]
I have also been trying (brute forcing) random things, one of which was adding 
"#define SOKOL_IMGUI_NO_SOKOL_APP" 
to my original app (which DOES actually use sokol_app.h) and this has gotten rid of almost all the errors, except for the last one.
This could hint at something, but I did not have time to investigate more yet.
After reverting the changes of uint64_t back to void*, the code would build, but I was not yet able to confirm that imgui actually runs in this state.

**Comment by floooh** [comment]
You could try a simpler example here which doesn't rely on the fips meta build system, build instructions are in the readme, and this also comes with embedded ImGui (in the sokol-samples it might be that Dear ImGui has introduced a breaking change in the master branch):

https://github.com/floooh/cimgui-sokol-starterkit/

...trying to build the sokol-samples from scratch now...

**Comment by floooh** [comment]
Hmm, all building fine here on Windows on a fresh clone, e.g.:

```
mkdir scratch
cd scratch
git clone https://github.com/floooh/sokol-samples
cd sokol-samples
fips set config sapp-win64-vstudio-debug
fips build
```

...the errors you're getting look like it's using an outdated Dear ImGui version (`GetPlatformIO()` was added in Dear ImGui v1.91.1 released beginning of September 2024), so first thing I would make sure is to *really* run from scratch in a new directory. You can also run `fips diag imports` to check the status of all dependencies (for instance there are situations where a local dependency is not updated - like local changes that haven't been committed or pushed yet).

**Comment by JanVelas** [comment]
Thank you for the tips and notes about the errors.

I booted up a different machine and followed your steps and there were **no errors**.
All builds and runs as expected. ✅

Thank you very much for your help and excuse me for this false alarm. :-)
