### ISSUE TITLE
GL + macOS Mojave remaining issues

### ISSUE THREAD

**Issue by floooh** [floooh/sokol#124]
Now that @gustavolsson has brought back GL support for macOS in sokol_app.h, a few remaining issues on macOS Mojave must be fixed:

- the backing framebuffer is always reported as Retina-resolution
- vsync doesn't work

See the PR comment thread for details:

https://github.com/floooh/sokol/pull/122

**Comment by floooh** [comment]
It seems like the vsync issue has been fixed in macOS Mojave 10.14.4 Beta (18E205e), the Retina resolution confustion is still there, but that's most like easier to fix (for instance, when resizing the window, the framebuffer "snaps" into the right resolution).

**Comment by floooh** [comment]
Everything fixed now.

**Comment by gustavolsson** [comment]
Nice!!
