### ISSUE TITLE
Add functions to access userdata.

### ISSUE THREAD

**Issue by floooh** [floooh/sokol#126]
Accessing the userdata member directly may be useful for things like language binding, e.g.

https://github.com/code-disaster/sokol-rs/blob/master/sokol/src/lib.c

**Comment by code-disaster** [comment]
I moved the code in sokol-rs, working link here:
https://github.com/code-disaster/sokol-rs/blob/00b47234a4259b15c2d09eadf7a49196c199a641/sokol/src/lib.c

**Comment by floooh** [comment]
...I finally got around to fix this, there are now the following functions:

```
void* sapp_userdata(void);
sapp_desc sapp_query_desc(void);
void* saudio_userdata(void);
saudio_desc saudio_query_desc(void);
```
The userdata pointer can also be obtained via the query_desc functions, but that's more expensive because those return a copy of the desc struct.
