### ISSUE TITLE
Cannot build Emscripten samples in Linux (Debian)

### ISSUE THREAD

**Issue by AndrewAMD** [floooh/sokol#127]
Hi,

I am having trouble building sokol-samples for Emscripten in Debian Linux.  I have produced some logs, I am not sure what the problem is.

```
> python --version
Python 2.7.13

> cmake --version
cmake version 3.7.2

> make --version
GNU Make 4.1

```

The procedure:

```
mkdir ~/fips-workspace/
cd ~/fips-workspace/

git clone https://github.com/floooh/sokol
git clone https://github.com/floooh/sokol-samples

cd sokol-samples
./fips setup emscripten > ./emout.txt 2>./emerr.txt
./fips set config webgl2-emsc-make-release
./fips build > ./bout.txt 2>./berr.txt

```

Here are the logs:
[berr.txt](https://github.com/floooh/sokol-samples/files/2932236/berr.txt)
[bout.txt](https://github.com/floooh/sokol-samples/files/2932237/bout.txt)
[emerr.txt](https://github.com/floooh/sokol-samples/files/2932238/emerr.txt)
[emout.txt](https://github.com/floooh/sokol-samples/files/2932239/emout.txt)

Thanks,
Andrew

**Comment by floooh** [comment]
Ok, that was simple, I just forgot an include in sokol_time.h, that _stm_js_perfnow() functions is fairly new, and in the sokol-app samples, the required emscripten.h is included by another header so the bug wasn't triggered.

Updating sokol and trying again should work (note that the build config webgl2-emsc-make-release builds the asm.js samples, to get the WebAssembly samples use one of the -wasm- configs

```
./fips list configs | grep webgl2-wasm
```

Cheers, and thanks for the bug report :)

(oh and I transfered the bug from sokol-samples to here, in case you're wondering)

**Comment by AndrewAMD** [comment]
Whew, that was fast! Nice library, by the way! :)
