### ISSUE TITLE
sokol_gfx_imgui: crash in _sg_imgui_draw_uniforms_panel

### ISSUE THREAD

**Issue by septag** [floooh/sokol#130]
in `_sg_imgui_draw_uniforms_panel` when pip== NULL, it crashes on the line:

```c
_sg_shader_t* shd = _sg_lookup_shader(&ctx->sg->pools, pip->shader_id.id);
```

**Comment by floooh** [comment]
True, without pipeline or shader it's not possible to display anything useful anyway, so I'm returning early now in that case.
