### ISSUE TITLE
Qt integration/demo

### ISSUE THREAD

**Issue by ppiecuch** [floooh/sokol#131]
Hello, first congrats for great piece of software! :) I tried to integrated sokol_gfx with Qt (using QWindow and other Qt's OpenGL classes) and seems like it works  well - I shared the code in my fork at: https://github.com/ppiecuch/sokol if someone is interested.

Regards
Paweel

**Comment by floooh** [comment]
Cool stuff :)

**Comment by floooh** [comment]
PS: looking at the code I'm seeing that you have added a SOKOL_NO_FUNC_PROTO. What sort of warnings or errors did you get without this? Does it make sense to add this to the main version?

**Comment by ppiecuch** [comment]
I simplified definitions in last commit: there is SOKOL_CLASS_IMPL when including sokol in class implementation and SOKOL_CLASS_PROTO when including sokol in class definition.

**Comment by floooh** [comment]
Ah, now I understand, you're including the entire sokol header *inside* a C++ class... phew, I haven't seen this approach yet, I'm a bit surprised this works at all to be honest :)

Would it make sense for C++ to provide a way to wrap the sokol declaration and implementation into a C++ namespace instead?

E.g. something like this:

#define SOKOL_GFX_NAMESPACE sgfx
#include "sokol_gfx.h"

...and in this case all structs and functions would be wrapped in a namespace called sgfx?

This define would need to be set everywhere where sokol_gfx.h is included though, so this is a bit unusual (usually such config defines only need to be set before including the implementation).

**Comment by ppiecuch** [comment]
I was even more surprise and happy too :) because what I did is Qt-ish way for OpenGL function loading:

class Window : public QWindow, protected **QOpenGLFunctions**

QOpenGLFunctions allows me to import (and resolve using method **initializeOpenGLFunctions()**) all OpenGL functions as methods of my Window class - they are not visible outside of the class. So I need to import Sokol functions in a same way. That way this demo works nice on all platforms.

**Comment by danhambleton** [comment]
@ppiecuch Integrating sokol in Qt has just come up on one of my projects :) I tried your code base with Qt 5.9 (win64 VS2015) but kept getting a null reference error during `sg_setup`. I believe Sokol thinks that OpenGL is not intialized. 

@floooh I have also tried including sokol without modifications (i.e. no added `SOKOL_CLASS_IMPL` defines or anything. Basically like the the GLFW examples. I get the same null access error.

Any thoughts on this would be most appreciated!

**Comment by ppiecuch** [comment]
Sure - I will update later my repo with latest changes.

Pawel

**Comment by danhambleton** [comment]
@ppiecuch Hey thanks. Yeah, I can't get past that assert either. I have tried a couple different SOKOL GL defines, but no dice.

**Comment by floooh** [comment]
Yeah, the GL backend in sokol_gfx.h only supports OpenGL 3.3, GLES 2.0 or GLES 3.0.

**Comment by ppiecuch** [comment]
@danhambleton I had some time to take a look again on this problem (that I have a feeling already struggle with): on OSX/OpenGL2 problem is with calling **glClearDepthf** (**glClearDepth** should be called instead):

```
           #if defined(SOKOL_GLES2) && !defined(_SG_TARGET_MACOS)
            glClearDepthf(action->depth.val);
            #else
            glClearDepth(action->depth.val);
            #endif
```

This require some refactoring to have _SG_TARGET_MACOS available in GL mode. I have already committed these changes.

<img width="800" alt="demo2" src="https://user-images.githubusercontent.com/1011685/82732610-8124d880-9d0e-11ea-8ba7-dbf08dc096ae.png">
