### ISSUE TITLE
sokol_app high DPI initialization API question

### ISSUE THREAD

**Issue by iskolbin** [floooh/sokol#140]
Sorry for such silly question but why we initialize high DPI as bool and get it as float(scale factor)?Why not just set scaling factor directly?Am I missing something?As I can tell high_dpi means scaling factor = 2 but many modern phones have devicePixelRatio = 3 in browsers, are they handled properly?

**Comment by floooh** [comment]
The idea is that high_dpi=true gives you the native rendering resolution of the display, and high_dpi=false gives you some "default" resolution which might be scaled up. The exact behaviour is pretty much platform-specific...

On Windows, using high_dpi=false gives 96 dpi, and dpi_scale is "native_dpi / 96".

On Mac and iOS the contentScaleFactor is 1 or 2 (not sure if that's still true on the latest Macs and iOS devices though).

On Emscripten, dpi_scale is set to the result of emscripten_get_device_pixel_ratio(), and the rendering size adjusted accordingly.

On Linux, there's currently no high_dpi support.

**Comment by iskolbin** [comment]
Thanks for clarification! Just to complete the list and close this:
On Android?

**Comment by floooh** [comment]
Android currently seems to have a hardwired factor 2.0, but I'm not sure if the current implementation is 'best practice' for the Android NDK.
