### ISSUE TITLE
sokol_app.h Win32: __argv doesn't actually provide UTF-8 strings...

### ISSUE THREAD

**Issue by floooh** [floooh/sokol#141]
...need to use __wargv and convert that to UTF-8 myself.

(Correction: looks like __wargv is null unless compiled with UNICODE define, need to find another solution)

PS: but maybe it works to convert from the codepage-encoded __argv to UTF-8 MultiByteToWide (codepage -> UTF-16) followed by WideToMultiByte (UTF16 -> UTF8)

PPS: alternatively GetCommandLineW() + CommandLineToArgvW(), and convert that to UTF-8

**Comment by martincohen** [comment]
I can help with this. I had success with `GetCommandLineW()` + `CommandLineToArgvW()` in my own platform layer.

**Comment by floooh** [comment]
If you find the time to provide a PR that would be great :)

**Comment by floooh** [comment]
ok fixed in #211
