### ISSUE TITLE
win32 compile fixes

### ISSUE THREAD

**Issue by questor** [floooh/sokol#145]
Hi,
some small potential windows compile fixes in sokol_gl.h:
static void _sgl_perspective(_sgl_matrix_t* dst, float fovy, float aspect, float near, float far) {
near and far are defined in windows.h, renaming helps atleast on windows. 

another one was: with msvc I got a compile error in this line:
https://github.com/floooh/sokol/blob/master/util/sokol_gl.h#L1415
in c++ mode...

**Comment by floooh** [comment]
Hmm ok, compilation in C mode is tested via AppVeyor and Travis for VS2015 and VS2017, but it's not currently tested in C++ mode (I need to add the other headers here: https://github.com/floooh/sokol-samples/blob/master/tests/cpp-compile-test.cc)

Thanks for the ticket, I'll take care of it in the next couple of days :)

**Comment by questor** [comment]
yeah, it's a pitty that c++ differs in the initialization so much from c (yes, it's on the list for 2020 finally after 21 years). windows-header is a different (dreaded) story...

thanks for your fast support :)

**Comment by questor** [comment]
another warning I've got in linux using clang7:

sources/sokol/sokol_app.h:6018:13: warning: logical not is only applied to the left hand side of this bitwise operator [-Wlogical-not-parentheses]
        if (!_sapp_glx_attrib(n, GLX_RENDER_TYPE) & GLX_RGBA_BIT) {
            ^                                     ~
sources/sokol/sokol_app.h:6018:13: note: add parentheses after the '!' to evaluate the bitwise operator first
        if (!_sapp_glx_attrib(n, GLX_RENDER_TYPE) & GLX_RGBA_BIT) {
            ^
             (                                                  )
sources/sokol/sokol_app.h:6018:13: note: add parentheses around left hand side expression to silence this warning
        if (!_sapp_glx_attrib(n, GLX_RENDER_TYPE) & GLX_RGBA_BIT) {
            ^
            (                                    )
sources/sokol/sokol_app.h:6022:13: warning: logical not is only applied to the left hand side of this bitwise operator [-Wlogical-not-parentheses]
        if (!_sapp_glx_attrib(n, GLX_DRAWABLE_TYPE) & GLX_WINDOW_BIT) {
            ^                                       ~
sources/sokol/sokol_app.h:6022:13: note: add parentheses after the '!' to evaluate the bitwise operator first
        if (!_sapp_glx_attrib(n, GLX_DRAWABLE_TYPE) & GLX_WINDOW_BIT) {
            ^
             (                                                      )
sources/sokol/sokol_app.h:6022:13: note: add parentheses around left hand side expression to silence this warning
        if (!_sapp_glx_attrib(n, GLX_DRAWABLE_TYPE) & GLX_WINDOW_BIT) {
            ^

**Comment by floooh** [comment]
...oops, that may actually even be a bug, thanks for notifying me.

**Comment by floooh** [comment]
...should be all fixed now:

5d8d4be2f690d6be91f949a7426b99f53fd7ffbf
1e1e48431ceda1940702688e2998461e21e49672
5646166498d9e1cd9c8d1d6ac5f68eaa0d0bef9c
