### ISSUE TITLE
Ignore key repeat.

### ISSUE THREAD

**Issue by slembcke** [floooh/sokol#162]
It seems that there is no way to ignore key repeat events? I get repeated key down events on Linux. I can test on Mac later, but that computer is currently occupied. (I don't see a check for NSEvent.isARepeat though)

It would be pretty easy to add as a boolean to the sapp_event struct. NSEvent makes it pretty easy on Apple, and I could look into Linux.

**Comment by floooh** [comment]
Sounds like a good feature. New ```bool key_repeat``` in sapp_desc?

If you want to, you can provide a partial pull request, and I can fill in the rest :)

**Comment by slembcke** [comment]
Yup, that was exactly my thought. I'm hoping to have time this week to look into it.
