### ISSUE TITLE
two channel render target format

### ISSUE THREAD

**Issue by velkyel** [floooh/sokol#172]
could you please add sg_pixel_format like SG_PIXELFORMAT_RG8 and SG_PIXELFORMAT_RG16F?
thank you.

**Comment by floooh** [comment]
There's a (quit longstanding) issue to generally cleanup the pixel formats: https://github.com/floooh/sokol/issues/112

Part of the reason why this isn't a quick fix is that not all pixel formats and their properties (e.g. renderable, 2^N dimensions, rectangular or not, etc...) are supported across all 3D backends, so there need to be new functions for querying pixel format capabilities.

There's a WIP PR here: https://github.com/floooh/sokol/pull/154, I guess after the stuff I'm currently working on, I'll take over that PR and complete it for the other backends.

Until then I would recommend to hack support for those pixel formats into you own copy of sokol_gfx.h :)

**Comment by amerkoleci** [comment]
I agree, but we need definitely more pixel formats support, at least the bgfx one

**Comment by floooh** [comment]
Ok, I think I'll try to look at the pixel format stuff next. Need to finish that example GLTF viewer I started, and look at a D3D shader compiling problem that popped up, but then I should have some time.

**Comment by floooh** [comment]
Closing this as duplicate for new issue: https://github.com/floooh/sokol/issues/187
