### ISSUE TITLE
sokol_gfx.h: Multi-window support with single context?

### ISSUE THREAD

**Issue by exavi** [floooh/sokol#176]
I have noticed that there is a multi-window glfw example but it seems to create one full set of data per context.

I'm after a way of sharing the context across windows/widgets (think of Autodesk Maya, or 3d Studio Max), with their different viewports, they all share the same data but draw from different cameras.

I unfortunately have not found a way to do this from looking at the public api, although I might be missing something, is there anything I could be missing?

I was thinking that since this would be using the same exact context there shouldn't be any need for context switching/creation so having an extra "window/widget id" argument at the end of sg_begin_default_pass might do the trick (without breaking code)

ie something along the lines of:

void sg_begin_default_pass(const sg_pass_action* pass_action, int width, int height, int window_id = 0)

or maybe as an override with an additional parameter, this time with explicit window_id?

the window_id would just be a way to internally set things up for the possibility of several "default/non-pass/pre-existent" framebuffers, which would be bound just before drawing, although the more I think of this the more I am starting to think that this might require a bit more of bookkeeping to keep track of some sort of sg_window(s) to know what goes where, and that they will also need initializing.

Off the top of my head (without testing) the hacky workaround for now would be to explicitly set the FBO id directly on gfx's internals before the sg_begin_default_pass call which I think should be harmless, but I honestly don't know if there is anything entangled that might cause trouble down the line in the backends that I'm not as familiar with as with OpenGL (which is quite forgiving!)

I'm also saying because to me it feels like having an extra sg_pass to deal with pre-existing widgets with their own framebuffers and somehow blitting sg_passes to them would be a bit of a hack?

**Comment by floooh** [comment]
Hi, rendering to different "contexts" is a topic that's only relevant (and possible) in GL, and I don't want to bend the sokol-gfx API too much for that specific use case, but I think what you need is already possible with what's already there:

I'm not sure if you've seen the GLFW multi-window example (https://github.com/floooh/sokol-samples/blob/master/glfw/multiwindow-glfw.c), but that's what the context-support in sokol-gfx was created for basically. Each window or widget gets its own GL context, each context has its own GL framebuffer, and resources like textures or buffers would use GL's resource sharing feature.

So with GLFW the first step would be to enable resource sharing for all contexts/windows (see here: https://www.glfw.org/docs/latest/context_guide.html#context_sharing). Then I would render the different cameras on the "main context" into offscreen passes. Since this rendering would go into shared textures, it should be possible to render the camera views on the other contexts as a simple fullscreen rectangle.

The last time I tried using multiple GL contexts in Qt resulted in a lot of pain and suffering, but that was a few years ago, maybe it has improved in the meantime ;)

**Comment by floooh** [comment]
PS: for using shared textures across different GL context you'd probably want to use sokol_gfx.h's "native resource injection", basically create one texture via direct GL calls, and create several sokol textures on different sokol different with the same GL texture handle, see here for an example (this doesn't use different contexts, but demonstrates how to "inject" a GL texture): https://github.com/floooh/sokol-samples/blob/master/glfw/inject-glfw.c

**Comment by exavi** [comment]
Sorry perhaps I didn't explain myself well, I think that we're talking about different things?

I would actually prefer **avoiding using contexts completely** what I am actually after is re-using the same *single* context across multiple windows/widgets. Although I can see why the word shared context would throw anyone out as it's also a valid concept in GL.

The only reason why I used the word context was to say that I had in fact looked at the glfw multi-window example and is doing the **opposite** of what I'm after.

As I mention the only thing that I can think of _(my backend knowledge is limited to GL)_ that would be needed for my purposes isn't a context change but some sort of window "id" that would tell sokol that I'm going to be rendering to a certain FBO id or another.

Perhaps this explains a bit better my use case, going back to the QOpenGLWidget example:

I would have multiple QOpenGLWidgets, think of the typical front/back/top/perspective 4 viewport case in 3d softwares and a **single** context for all of them, that does not cause any issues since it can only redraw one at a time anyway.

in each "draw" call...

```
void GLWidget::paintGL()
{
    sg_begin_default_pass(&pass_action, width(), height()); // <--- no sg_window concept***
    queue_drawables(); 
    sg_end_pass();
    sg_commit();
}
```

my _issue_ with the current concept of `sg_begin_default_pass` is that it assumes that there is a single default pass/or a single window/widget.

I was asking about the possibility of either contemplating the possibility of having an extra concept of `sg_window`(s) used on `sg_begin_default_pass` like so:

```
sg_begin_default_pass(&pass_action, width(), height(), &this_window_id); // sg_window this_window_id;
// everything going forward goes to the fbo of this_window_id... as long as sg_pass aren't involved
```

or maybe some global state:

```
sg_set_current_window(&this_window_id);
sg_begin_default_pass(&pass_action, width(), height());
// everything going forward goes to the fbo of this_window_id... as long as sg_pass aren't involved
```

As far as I can think of (right now, with my GL-only knowledge) `sg_window` would be something along the lines of:

```
struct sg_window {
 uint32_t fbo_id;
}
```

whereas right now without this concept of `sg_window` it assumes that `this_window_id` is always going to be `_sg.gl.cur_context->default_framebuffer`

Does this make more sense now? Is there already a nice way to do this? Would you consider supporting this?

I was basically saying earlier that I could probably do something along the lines of the following and call it a day, I'd assume this would work on GL but I'm not sure about doing the equivalent on Metal, for instance. 
```
void GLWidget::paintGL()
{
    _sg.gl.cur_context->default_framebuffer = this_window_id.fbo_id;
    sg_begin_default_pass(&pass_action, width(), height());
    //...
```

**Comment by exavi** [comment]
another approach to doing this would be to create and use sg_pass for all widgets/windows (without ever dealing with a "default" one) but without actually creating the fbos that may be attached to sg_pass. (to avoid having unused fbos)

ie: since Qt already creates FBOs one would want to create sg_passes pre-initializing them with existing FBOs so they wouldn't have to create any (if that makes sense), in this case sg_pass would need to have some sort of bookkeeping to know the ownership of the FBOs it manages.

**Comment by floooh** [comment]
Ok, if this code works in GL:

```c
_sg.gl.cur_context->default_framebuffer = this_window_id.fbo_id;
sg_begin_default_pass(&pass_action, width(), height());
```

Then I think it's better if you wrap that your own small extension header for sokol-gfx (to be included after the sokol_gfx.h implementation), where you add a small extension function which would look like this:

```c
void sg_begin_pass_with_fbo(sg_pass pass_id, const sg_pass_action* pass_action, GLuint fbo) {
    GLuint cur_fbo = _sg.gl.cur_context->default_framebuffer;
    _sg.gl.cur_context->default_framebuffer = this_window_id.fbo_id;
    sg_begin_pass(pass_id, pass_action);
    _sg.gl.cur_context->default_framebuffer = cur_fbo;
}
``` 

The "multiple window rendering" approaches of the different backend APIs differ too much to generalize this case IMHO, and at least in Metal and D3D11 it also needs code that's normally living in sokol_app.h, so it couldn't be done in sokol-gfx alone.

**Comment by exavi** [comment]
I see thanks, I will need to have a look at the Metal side of things then to see how to wrap it nicely since having OpenGL && Metal supported is the reason why I'm considering moving my codebase from raw OpenGL to sokol_gfx.h.

I naively expected other backends to have a similar way around this by dealing with FBOs with some numeric id... :(

Cheers!

**Comment by exavi** [comment]
I did a quick test in Metal, in the _super simple_ test I hacked together looks like all it takes to get it to handle multi-MTKView rendering is setting up `mtk_view` before drawing like so:

```
- (void)drawInMTKView:(nonnull MTKView *)view {
    mtk_view = view;
    sg_begin_default_pass(&pass_action, m_width, m_height);
    //...
```

and/or before initialization the first time, so it has something to hold on to, given that the setup is using the callbacks `osx_mtk_get_render_pass_descriptor()` and `osx_mtk_get_drawable()` which rely on an assigned MTKView*, if it gets swapped out it _seems_ to be all good...

This is looking good, I'll have a bit more of a play when I get to something more "complex" as right now when I say it works it means that it works by modifying one of the samples, if it works then I'd be happy to send a PR.
