### ISSUE TITLE
Using metal without xcode

### ISSUE THREAD

**Issue by sherjilozair** [floooh/sokol#192]
I'm trying to use the metal renderer. I prefer the unix workflow, but it seems that ARC requires Xcode. Is that correct?

I looked at FIPS code which enables ARC and I see:

```
option(FIPS_OSX_USE_ARC "Enable/disable Automatic Reference Counting" OFF)
if (FIPS_OSX_USE_ARC)
    set(CMAKE_XCODE_ATTRIBUTE_CLANG_ENABLE_OBJC_ARC "YES")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fobjc-arc")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fobjc-arc")
else()
    set(CMAKE_XCODE_ATTRIBUTE_CLANG_ENABLE_OBJC_ARC "NO")
endif()
```
When I add this in my own cmake project, `-fobjc-arc` gets passed to clang, but I still get the ARC error in sokol_gfx.h

In summary, is it possible to use metal renderer without using xcode? How?

If xcode must be used, is it possible to use other IDEs like CLion but getting the project built via xcode?

**Comment by mattiasljungstrom** [comment]
You don't need to use the xcode IDE, I have been using VS Code for instance. You can compile on the command line with xcode, make sure to install the command line extensions from inside xcode. 

If you use fips, make sure your fips config file has this in it:

defines:
    SOKOL_USE_METAL: ON
    FIPS_OSX_USE_ARC: ON

**Comment by floooh** [comment]
You don't need to compile in Xcode, but you need the Xcode command line tools (for the compiler, etc...). Here's an example of how to compile one of the Metal samples directly from the command line (replace [sokol_dir] with the path to where the sokol-headers are:

```
> cd sokol_samples/metal
> cc cube-metal.c osxentry.m sokol_gfx.m -o cube -fobjc-arc -I[sokol_dir] -framework Metal -framework Cocoa -framework MetalKit -framework Quartz
```
This doesn't use sokol_app.h (only sokol_gfx.h), and doesn't create an app bundle, but it shows the "simplest possible" way to compile with the Metal backend outside of Xcode :)

**Comment by sherjilozair** [comment]
Is it necessary to have a .m files? I don't know any objective-C or Swift, and would like to stick to C++.
I changed my sokol implementation source file to .m, and added the framework commands. That allows me to compile, but I still get an assert failure in setup_backend.

```
Assertion failed: (desc->mtl_device), function _sg_setup_backend, file /Users/sherjilozair/CLionProjects/subsolar/include/sokol_gfx.h, line 7368.
```
My entry point is still C++: https://github.com/sherjilozair/subsolar/blob/master/src/main.cpp. Do I have to switch to using osxentry.m?

**Comment by floooh** [comment]
Yes, you need to compile the sokol **implementations** through a .m file, because they must be compiled as Objective-C (the higher level macOS APIs are all Objective-C). You don't need to know or write any Objective-C (all the sokol APIs are still pure C), but the sokol implementations must be compiled as ObjC.

Have a look at the sokol.m file in here: https://github.com/floooh/sokol-samples/tree/master/libs/sokol, this is basically the same as the sokol.c file next to it (which is used for the other platforms), but it will be compiled as Objective-C since it has the .m file extension.

That assertion means you didn't provide a pointer to the Metal device object to sokol_gfx.h, see the sokol_gfx.h initialization here (using sokol_app.h, note the .mtl_* items):

https://github.com/floooh/sokol-samples/blob/36d0a430e6448d525e029136d2a9ea232b58570e/sapp/clear-sapp.c#L11-L19

...or here for using the osx_entry.h/.m implementation instead of sokol_app.h:

 https://github.com/floooh/sokol-samples/blob/36d0a430e6448d525e029136d2a9ea232b58570e/metal/clear-metal.c#L11-L15

**Comment by sherjilozair** [comment]
Thanks @floooh Got metal working using `osxentry.m/.h` and `clear-metal.c`. I still have some questions though. I see that SDL2 or anything equivalent like GLFW is not being used at all, and that osxentry.m has functions like `keyDown` which I can use to register callbacks. Is the window/context creation being done by Metal instead of SDL2? What if I want to use SDL2, so that I'm consistent across platformers?

**Comment by floooh** [comment]
osxentry.m is basically a "poor man's substitute" for something like GLFW, it open a window, creates an MTKView, and handles input.

sokol_app.h is basically the same but cross-platform and for all sokol_gfx.h backends.

If you want to use SDL2 instead, then SDL2 must be able to provide the following things to be used with sokol_gfx.h:

- a pointer to the MTLDevice object
- for each frame, an CAMetalDrawable object (for instance when MTKView is used, this is obtained with the ```[MTKView currentDrawable]``` instance method
- for each frame, an MTLRenderPassDescriptor object (with MTKView, this is obtained with ```[MTKView currentRenderPassDescriptor]```

I haven't looked at the Metal support in SDL2 yet though, don't know if those things are readily provided by the SDL2 API.

**Comment by tanis2000** [comment]
@sherjilozair did you manage to get SDL2 working with sokol_gfx in the end?
It looks like I stumbled upon the same issue and as far as I can see I can pull off the CAMetalLayer from the NSView that SDL2 creates and assign to it my own MTLDevice. But from that point on I am a bit lost as it is not using MTKView and I have no clue how to access the current MTLRenderPassDescriptor.

**Comment by sherjilozair** [comment]
Sorry, I didn't try this any further.

**Comment by tanis2000** [comment]
@sherjilozair too bad... it looks like SDL2 is just instantiating an NWView and then you can access the CAMetalLayer of that view but then there is no default MTLRenderPassDescriptor available.

My current hack is to instantiate a new MTLRenderPassDescriptor each frame and use it as the descriptor to pass to sokol_gfx. Same goes for the drawable. I just get the nextDrawable from the metal layer.

It does work but it doesn't look nice and I'm not even sure that I'm not messing up something else by doing this.

@floooh did you ever manage to try and integrate sokol_gfx with SDL2's Metal support recently?

**Comment by floooh** [comment]
No haven't tried. If SDL is just providing a CAMetalLayer, then what's also needed is extra code to manage a depth buffer and possibly MSAA buffer, and all that wrapped into a MTLRenderPassDescriptor.

I've hit that same snag in the WIP multiwindow branch, where I need to ditch MTKView, and instead use a raw CAMetalLayer. The "Creating a Custom Metal View" sample here might help:

https://developer.apple.com/metal/sample-code/

(however for some reason this produces an empty webpage here, even though I downloaded the sample code earlier today, weird)

**Comment by lithiumtoast** [comment]
> My current hack is to instantiate a new MTLRenderPassDescriptor each frame and use it as the descriptor to pass to sokol_gfx. Same goes for the drawable. I just get the nextDrawable from the metal layer.

This is what I did before when using sokol_gfx with SDL2. Notable header with docs: https://github.com/libsdl-org/SDL/blob/main/include/SDL_metal.h
