### ISSUE TITLE
_sg_gl_reset_state_cache assert failure on GLES2

### ISSUE THREAD

**Issue by septag** [floooh/sokol#194]
I'm trying to run sokol on RaspberryPI which is OpenGL-ES2. and at the initialization I get assert failure in [here](https://github.com/floooh/sokol/blob/1f1dbde22abab7b9a4976383b2d773c45594c222/sokol_gfx.h#L4833).

By checking the [documentation](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glEnableVertexAttribArray.xhtml), I guess the error is legit because no VAO is binded.

**Comment by floooh** [comment]
Hmm, glDisableVertexAttribArray() isn't a VAO function though.

I seem to remember that the Raspi2's GL implementation doesn't support 16 vertex attributes, instead the number must be queried with ```glGetIntegerv(GL_MAX_VERTEX_ATTRIBS, &max_vertex_attrs)``` when the GL backend is setup, and the ```min(max_vertex_attrs, SG_MAX_VERTEX_ATTRIBUTES)``` must be used in loop like the one that generates the error.

I'm surprised I didn't think of that. I'll close this ticket and write a new one to fix this specific problem.
