### ISSUE TITLE
sokol_gfx: Clamp to border option for sg_image

### ISSUE THREAD

**Issue by martincohen** [floooh/sokol#204]
Hello, I'd like to discuss possibility of adding *clamp-to-border* wrap mode and *border-color* option to `sg_image_desc` in `sokol_gfx`. Is this planned? Should I attempt to add it?

I generally use it to render geometric primitives with white border and UV set to -1, -1. It bypasses the need for having a white pixel in texture and simplifies the drawing code.

By my lousy research it seems that WebGL, OpenGL, DirectX and Metal all do support it.

**Comment by floooh** [comment]
I can't find support in WebGL (there's an GLES2 extension but that doesn't seem to exist for WebGL).

But we can implement it as an optional feature, so:

- add a feature bit "image_border_color" (or a better name) to the sg_features struct
- add a SG_CLAMP_TO_BORDER enum to sg_wrap enum
- add a "float border_color[4]" to sg_image_desc

A PR would be welcome (also if you just implement for a single backend, I can then take over for the others).

**Comment by martincohen** [comment]
What's the strategy for testing the new features? I'm now using only DirectX, and tested it there with my own code. However, so far I have no code running for OpenGL, and Metal is out of my comfort zone. Do we add a sample testing the feature out?

**Comment by floooh** [comment]
Yes, a simple sample for testing/visualizing the texture addressing modes would be nice, nothing fancy.

Just implement the things you want, and then I can take over.

**Comment by floooh** [comment]
See: https://github.com/floooh/sokol/pull/209 and https://github.com/floooh/sokol-samples/pull/46

I'll update the documentation and READMEs next (tomorrow or so) and then I think it's ready for merging.

**Comment by floooh** [comment]
This has now been merged to master.
