### ISSUE TITLE
sokol_app: Show/hide mouse cursor (followup tasks)

### ISSUE THREAD

**Issue by martincohen** [floooh/sokol#208]
A way to show/hide cursor (useful for games with cursor shown again in debug mode).

Maybe `sapp_show_mouse_cursor(bool)` that has no effect on platforms where it doesn't make sense?

I can PR Windows implementation.

**Comment by floooh** [comment]
Yes, this would also be a good first step towards a proper pointer-lock mode (I started a while ago with code from GLFW, but it's quite a lot of code unfortunately).

**Comment by floooh** [comment]
This is now implemented, just forgot to close the ticket.
