### ISSUE TITLE
sokol_gfx: render pass descriptor 

### ISSUE THREAD

**Issue by amerkoleci** [floooh/sokol#216]
Hi,
Following the webgpu specs would be great if we can implement render pass descriptor logic similar to webgpu specs, separate in load and store action and manage the resolve statement,currently when creating a  multisample texture it creates two backend texture and resolve it on end render pass. 

Just an idea, I don't dislike the current one implementation. 
What do you think?

**Comment by floooh** [comment]
I need to dig into the WebGPU spec, but I don't want to add additional "complexity" if there isn't a compelling use case where "opening up" sg_end_pass() is really required.

One thing I have in the back in my head is to move the concrete sg_image handles out of the render pass object though, instead only describe the color and depth attachments of a pass in terms of pixelformats and sample count, and then "bind" concrete images only during sg_begin_pass().

But again, this change makes only sense when there's a compelling use case, creating additional passes is cheap and they don't take up much memory.

**Comment by floooh** [comment]
WebGPU also requires a separate resolve-texture, in addition to the MSAA render texture, and the MSAA resolve also happens automatically in endPass():

https://gpuweb.github.io/gpuweb/#dictdef-gpurenderpasscolorattachmentdescriptor

...it's essentially the same as Metal, the difference between sokol_gfx.h and WebGPU (and Metal) is that in sokol_gfx.h the pass object is created upfront, while in WebGPU and Metal a new render-pass object must be created for each frame. In this case I think the sokol_gfx.h model makes more sense.
