### ISSUE TITLE
Help! blend state operation for simple transparent png 

### ISSUE THREAD

**Issue by neurotok** [floooh/sokol#221]
I give up! could someone be so kind and tell me how to set up sg pipeline to achieve a simple blending of transparent png as a texture quad ?

Jus like a simple  glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA) in opengl 
https://learnopengl.com/img/advanced/blending_discard.png

**Comment by floooh** [comment]
This should do the trick (not the ".blend.enabled" flag:
```
sg_pipeline pip = sg_make_pipeline(&(sg_pipeline_desc){
    .layout = ...,
    .shader = ...,
    .blend = {
        .enabled = true,
        .src_factor_rgb = SG_BLENDFACTOR_SRC_ALPHA,
        .dst_factor_rgb = SG_BLENDFACTOR_ONE_MINUS_SRC_ALPHA
    },   
});
```

sokol_gfx.h uses separate blend state for RGB and Alpha (similar to OpenGL's glBlendFuncSeparate), so it may also be required to set the ```.src_factor_alpha``` and ```.dst_factor_alpha``` members in sg_pipeline_desc, but usually this isn't needed when rendering to the default framebuffer.

**Comment by neurotok** [comment]
That did the trick :) Thank's Floooh, you're awesome!

**Comment by geekynils** [comment]
I was also looking for this and thankfully I found this "issue". As of now I saw that the blend states were moved into an array called colors (but in all the examples only the first color is set). Could you explain what the colors array means?

**Comment by floooh** [comment]
Hi @geekynils, yes the structure of sg_pipeline_desc has changed a few months ago, see this blog post for details:

https://floooh.github.io/2021/02/07/sokol-api-overhaul.html

Blend state is now in an array because sokol_gfx.h now supports a different blend formula for each render target in a multi-render-target scenario (this isn't supported on all backends though).

**Comment by geekynils** [comment]
Ouh I should read your blog more careful, thanks for the quick answer!
