### ISSUE TITLE
Questions regarding some pixel formats

### ISSUE THREAD

**Issue by septag** [floooh/sokol#223]
I have a bit of confusion on some sg_pixel_format names ..

1. _SG_PIXELFORMAT_ETC2_RGB8A1_: there is no SG_PIXELFORMAT_ETC2_RGBA8 and it's the most common usage of ETC2 format. but in GL version it returns GL_COMPRESSED_RGBA8_ETC2_EAC and in Metal, returns MTLPixelFormatETC2_RGB8A1. is this ok?
2. _SG_PIXELFORMAT_BC1_RGBA_: the common usage for BC1 format is actually SG_PIXELFORMAT_BC1_RGB, but instead we have this one (which alpha seems to be 1bit punchthrough), isn't it more convenient to call it  SG_PIXELFORMAT_BC1_RGB and maybe have another one for RGBA ?
3. _SG_PIXELFORMAT_ETC2_RGB8_: I tried to use ETC1 format but it wasn't in the sg_pixel_format, but this one seems to work with ETC1 textures too. So the format is backwards compatible with ETC1 RGB? if yes, we can add another SG_PIXELFORMAT_ETC1_RGB8 to avoid confusion.

thanks

**Comment by floooh** [comment]
Hi, as for BC1_RGBA, that's what Metal is using: https://developer.apple.com/documentation/metal/mtlpixelformat?language=objc, there doesn't seem to be a distinction on whether the 1-bit alpha is actually used as such or not. I think it's up to the render pipeline whether the alpha channel bit is actually used for blending).

As for the ETC pixel formats: I haven't spent too much time on those I must admit, and only moved the old ETC pixel formats over. For ETC1 and ETC2 we should look at the following APIs and take the subset that's supported there:

- Metal (this has 6 "EAC" formats and and 4 "ETC2" formats, see: https://developer.apple.com/documentation/metal/mtlpixelformat?language=objc)
- the two WebGL ETC extensions: https://www.khronos.org/registry/webgl/extensions/WEBGL_compressed_texture_etc/ and https://www.khronos.org/registry/webgl/extensions/WEBGL_compressed_texture_etc1/
- and what WebGL2 supports out of the box...

It's a bit of work to figure out that "actually useful ETC subset", I'm happy to merge a PR :)

**Comment by septag** [comment]
I have submitted a PR. hopefully resolving some confusion and adding some useful ETC/EAC formats like two component ETC2_RG11

The document you referenced [here](https://www.khronos.org/registry/webgl/extensions/WEBGL_compressed_texture_etc/) clearly shows that SG_PIXELFORMAT_ETC2_RGB8A1 should be COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2.
I think the metal document is somewhat incorrect! It states that MTLPixelFormatETC2_RGB8A1 has 4 8bit components which is not what the actual format name shows. Instead, we should use MTLPixelFormatEAC_RGBA8 for ETC2_RGBA8.

ETC2_RGB also seems to be backwards compatible with ETC1, by what it says in the [wiki](https://en.wikipedia.org/wiki/Ericsson_Texture_Compression#ETC2_and_EAC) page and also my tests validates this, so I guess there is no need to define ETC1.

About the BC1 format, you are right, I guess there is not difference between RGB8 and RGB8A1, we could use another format like SG_PIXELFORMAT_BC1_RGB which will be same as SG_PIXELFORMAT_BC1_RGBA, but I wasn't sure it was useful so I didn't add it in PR.

Cheers

**Comment by floooh** [comment]
Fixed via https://github.com/floooh/sokol/pull/225
