### ISSUE TITLE
Should not glFlush() before NSOpenGLContext.flushBuffer()

### ISSUE THREAD

**Issue by thenewvu** [floooh/sokol#224]
https://github.com/floooh/sokol/blob/4c14c77d7816bd20df2e18a20c5b7125ff0433e4/sokol_app.h#L1514

As the docs said:
> An implicit glFlush is done by flushBuffer() before it returns. For optimal performance, an application should not call glFlush immediately before calling flushBuffer().

https://developer.apple.com/documentation/appkit/nsopenglcontext/1436211-flushbuffer

**Comment by floooh** [comment]
Good catch, I'm not sure why it's in there TBH, only that it's in right from the beginning. I'll remove the glFlush and check whether it behaves as expected.

Thanks!
