### ISSUE TITLE
the debug ui asserts when displaying array textures

### ISSUE THREAD

**Issue by mattiasljungstrom** [floooh/sokol#240]
Noticed in my code, but you can trigger it in your sample code:
(on Win10, VS2017, have not tried macOS)
```
fips set config sapp-win64-vs2017-debug 
fips run arraytex-sapp-ui 
click sokol-gfx -> images -> array-texture
*assert*
```

It doesn't crash in release build, but the image is shown as black.

**Comment by floooh** [comment]
ah thanks for the bug report, I think I accidentally broke this when adding the new pixel formats, I assumed that it's enough to check whether the image can be sampled and is not a depth texture, of course that's not enough when the ImGui shader expects a 2D image :)
