### ISSUE TITLE
How do you know what window the Metal renderpass descriptor callback is for?

### ISSUE THREAD

**Issue by tom-seddon** [floooh/sokol#242]
There's nothing passed in to the renderpass descriptor callback. How can it know what to do? It should surely get passed in a `void *` of the caller's choosing, as presumably supplied as part of the sg_desc.

I'll have a go at making a PR for this, but I reserve the right to soon find out that I've misunderstood what's going on...

Thanks,

--Tom

**Comment by tom-seddon** [comment]
OK, I think I see - this is #229, and it sounds like it might be more involved than I expect. So I'm not going to do anything about this.

Thanks,

--Tom

**Comment by floooh** [comment]
Hi Tom, sorry for not responding in time, I was focusing on emulator stuff over the holidays and deliberately ignored sokol stuff ;)

As you already found out, sokol_gfx.h needs "a bit" more work to really work with multiple output windows across all backends, and sokol_app.h would require quite a lot of work.
