### ISSUE TITLE
Odd bug when calling sg_update_buffer in the event callback

### ISSUE THREAD

**Issue by prime31** [floooh/sokol#244]
This is a bit of an odd one, so I'll try to explain it clearly. I also included a repro below.

The basic gist of the issue is that when calling `sg_update_buffer` in the event callback (key-up in the example) it doesnt update the buffer and causes all future draw calls to silently fail. If you then call `sg_update_buffer` again in the event callback draw calls will start to work _but_ they won't be using the updated vertex buffer.

Now for the oddity: if you do an `sg_update_buffer` in the `frame` callback just once all calls to `sg_update_buffer` in the event callback will then start working correctly.

The demo program below logs when `jiggle` (and thus `sg_update_buffer`) is called so it is clear what is happening.

**Steps to repro**:
- run the below code and press 'j' which call `jiggle`, a simple method to update the vert positions and call `sg_update_buffer` with the new data.
- notice each time your press 'j' the verts disappear, then appear the next time your press it

**Steps to make it work**:
- run the below code and press 't' which toggles calling `jiggle` in the `frame` callback
- press 'j' to have `jiggle` called in the frame callback
- press 't' to toggle having `jiggle` called in the event callback
- press 'j' and now when `jiggle` is called in the event callback it will work

```c
//------------------------------------------------------------------------------
//  quad-sapp.c
//  Simple 2D rendering with vertex- and index-buffer.
//------------------------------------------------------------------------------
#include "sokol_app.h"
#include "sokol_gfx.h"
#include "dbgui/dbgui.h"
#include "quad-sapp.glsl.h"
#include <stdlib.h>
#include <stdio.h>

static sg_pass_action pass_action = {
    .colors[0] = { .action=SG_ACTION_CLEAR, .val={0.0f, 0.0f, 0.0f, 1.0f } }
};
static sg_pipeline pip;
static sg_bindings bind;
static bool do_jiggle;
static bool update_in_frame;

void init(void) {
    sg_setup(&(sg_desc){
        .gl_force_gles2 = sapp_gles2(),
        .mtl_device = sapp_metal_get_device(),
        .mtl_renderpass_descriptor_cb = sapp_metal_get_renderpass_descriptor,
        .mtl_drawable_cb = sapp_metal_get_drawable,
        .d3d11_device = sapp_d3d11_get_device(),
        .d3d11_device_context = sapp_d3d11_get_device_context(),
        .d3d11_render_target_view_cb = sapp_d3d11_get_render_target_view,
        .d3d11_depth_stencil_view_cb = sapp_d3d11_get_depth_stencil_view
    });
    __dbgui_setup(1);

    /* a vertex buffer */
    float vertices[] = {
        // positions            colors
        -0.5f,  0.5f, 0.5f,     1.0f, 0.0f, 0.0f, 1.0f,
         0.5f,  0.5f, 0.5f,     0.0f, 1.0f, 0.0f, 1.0f,
         0.5f, -0.5f, 0.5f,     0.0f, 0.0f, 1.0f, 1.0f,
        -0.5f, -0.5f, 0.5f,     1.0f, 1.0f, 0.0f, 1.0f,
    };
    bind.vertex_buffers[0] = sg_make_buffer(&(sg_buffer_desc){
        .size = sizeof(vertices),
        .label = "quad-vertices",
        .usage = SG_USAGE_DYNAMIC
    });
    sg_update_buffer(bind.vertex_buffers[0], vertices, sizeof(vertices));

    /* an index buffer with 2 triangles */
    uint16_t indices[] = { 0, 1, 2,  0, 2, 3 };
    bind.index_buffer = sg_make_buffer(&(sg_buffer_desc){
        .type = SG_BUFFERTYPE_INDEXBUFFER,
        .size = sizeof(indices),
        .content = indices,
        .label = "quad-indices"
    });

    /* a shader (use separate shader sources here */
    sg_shader shd = sg_make_shader(quad_shader_desc());

    /* a pipeline state object */
    pip = sg_make_pipeline(&(sg_pipeline_desc){
        .shader = shd,
        .index_type = SG_INDEXTYPE_UINT16,
        .layout = {
            .attrs = {
                [ATTR_vs_position].format = SG_VERTEXFORMAT_FLOAT3,
                [ATTR_vs_color0].format   = SG_VERTEXFORMAT_FLOAT4
            }
        },
        .label = "quad-pipeline"
    });
}

double rand_between(double min, double max) {
    return ((double)rand()/RAND_MAX) * (max - min) + min;
}

void jiggle() {
    float vertices[] = {
        // positions            colors
        -0.5f,  0.5f, 0.5f,     1.0f, 0.0f, 0.0f, 1.0f,
         0.5f,  0.5f, 0.5f,     0.0f, 1.0f, 0.0f, 1.0f,
         0.5f, -0.5f, 0.5f,     0.0f, 0.0f, 1.0f, 1.0f,
        -0.5f, -0.5f, 0.5f,     1.0f, 1.0f, 0.0f, 1.0f,
    };
    for (int i = 0; i < 28; i += 7) {
        vertices[i] += rand_between(-0.1, 0.1);
        vertices[i + 1] += rand_between(-0.1, 0.1);
    }
    sg_update_buffer(bind.vertex_buffers[0], vertices, sizeof(vertices));
}

void frame(void) {
    if (do_jiggle)
    {
        do_jiggle = false;
        printf("jigging in frame callback\n");
        jiggle();
    }

    sg_begin_default_pass(&pass_action, sapp_width(), sapp_height());
    sg_apply_pipeline(pip);
    sg_apply_bindings(&bind);
    sg_draw(0, 6, 1);
    __dbgui_draw();
    sg_end_pass();
    sg_commit();
}

void event(const sapp_event* evt, void* ud) {
    __dbgui_event(evt);
    if (evt->type == SAPP_EVENTTYPE_KEY_UP) {
        if (evt->key_code == SAPP_KEYCODE_J) {
            if (update_in_frame) {
                do_jiggle = true;
            } else {
                printf("jigging in event callback\n");
                jiggle();
            }
        }
        if (evt->key_code == SAPP_KEYCODE_T) {
            update_in_frame = !update_in_frame;
            printf("doing jiggle in frame callback: %d\n", update_in_frame);
        }
    }
}

void cleanup(void) {
    __dbgui_shutdown();
    sg_shutdown();
}

sapp_desc sokol_main(int argc, char* argv[]) {
    return (sapp_desc){
        .init_cb = init,
        .frame_cb = frame,
        .event_userdata_cb = event,
        .cleanup_cb = cleanup,
        .width = 800,
        .height = 600,
        .gl_force_gles2 = true,
        .window_title = "Quad (sokol-app)",
    };
}
```

**Comment by floooh** [comment]
Hi, thanks for catching that. I can reproduce the problem on OSX with the GL backend, but not with the Metal backend. I suspect it's a problem with the GL state cache and storing/restoring the current buffer binding when sg_update_buffer() is called.

I'll try to look into it in the next few days.

**Comment by prime31** [comment]
Oh jeeze. I totally forgot to mention it was GL on macOS. My apologies. It does work fine on Linux as well btw.

**Comment by floooh** [comment]
Oh, that's interesting that there's different behaviour between different GL backends. Thanks for the info.

**Comment by floooh** [comment]
It also works fine in GL on Windows. Still digging...

**Comment by floooh** [comment]
...also works in WASM, still digging, but I'm starting to suspect it's one of those "GL is deprecated on Mac" issues...

**Comment by floooh** [comment]
Ah, no, forget my last comment. I *think* I know what's happening:

The sokol_app.h GL backend calls the sokol-app frame callback from inside the NSOpenGLView drawRect() method. But the event handler callback is called from outside that function (directly from the macOS event callbacks).

My guess is now that calling any OpenGL functions from outside the NSOpenGLView::drawRect() function is basically "undefined behaviour".

I'll experiment a bit more, but I guess it's not something that can be fixed, unless the whole event handling is rewritten...

**Comment by floooh** [comment]
Hmm, I can "fix" it by making the internal GL context current in the key event handler function, basically calling 

```objective-c
[[_sapp_view_obj openGLContext] makeCurrentContext];
```
...each time an input event happens. This fixes your test case works. Not sure if that's a good idea though, I need to ponder that a bit.

What's your use case for calling sokol-gfx functions from inside the event handler?

**Comment by prime31** [comment]
That’s an interesting and odd fix. Also odd is that doing just one update of the buffer in the frame callback fixed the issue.

I honestly don’t have a really solid use case for calling things reactively from an input handler. Sometimes when experimenting rather than setup a whole proper system I just slap code in an input handler temporarily. That’s how I came across the bug.

**Comment by floooh** [comment]
TBH I'd just like to put a mention in the doc that calling rendering function from the sokol-app event handler is "undefined behaviour" and explain the reason (some functions having a render callback function, and the platform's event handling happening outside of that), because even if some functions (like updating GL buffers) works, other things that do actual rendering might not work.

If this isn't an option, a longer-term fix would be to add an internal event queue to sokol-app, and instead of forwarding events directly to the app from the platform's event handling, instead call the event handlers from a defined point right before the frame-callback is called. This doesn't too bad either, and it would guarantee that the event handler is called from the same place on all platforms, which might also be useful for other things than rendering.

I'll keep the bug open as a reminder, need to think a bit more about this :)

**Comment by prime31** [comment]
A note sounds good to me. No need to go crazy with an event queue and all that for something that’s easy to workaround.

**Comment by floooh** [comment]
Ok, I think I'll just add a note. That internal event-queue idea also wouldn't work on the browser platform, because some JS/HTML things must be run from inside a "short-living event handler", and the current behaviour of calling the sapp-event callback directly from the JS event callbacks is quite important there.

**Comment by prime31** [comment]
I’m pretty sure it wouldn’t solve the issue anyway. When I first encounters the issue I _think_ one of the first things I did was dispatch_async all events because I thought they were coming in on a background thread.

**Comment by floooh** [comment]
I've added a short blurb to the sokol_app.h documentation here:

https://github.com/floooh/sokol/blob/1e0de43e94fb2799894efc3ff4b09cd35c1cda8c/sokol_app.h#L284-L288
