### ISSUE TITLE
Incorrect offset used to mask GetKeyState in _sapp_win32_mods

### ISSUE THREAD

**Issue by jeffkdev** [floooh/sokol#247]
```C
_SOKOL_PRIVATE uint32_t _sapp_win32_mods(void) {
    uint32_t mods = 0;
    if (GetKeyState(VK_SHIFT) & (1<<31)) {
        mods |= SAPP_MODIFIER_SHIFT;
    }
...
```
This was segfaulting (EXCEPTION_ILLEGAL_INSTRUCTION) in the latest version of Zig in debug mode. Looks like the GetKeyState result is a short and it is being masked with a 32 bit number: https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getkeystate 

Changing it each of them to (1<<15) fixed it to me and seems to be consistent with some other usages of the function: https://stackoverflow.com/a/6332025

**Comment by floooh** [comment]
Yep, definitely a bug, thanks for catching that. I guess it works in C code because the 16-bit return value might be extended to a signed 32-bit value. Fix incoming.
