### ISSUE TITLE
Is sokol suited for gamedev?

### ISSUE THREAD

**Issue by gavriil07** [floooh/sokol#252]
I want to use it for a 2D game. I also tried bgfx but it feels too heavy for my needs. 

Im mostly interested in sokol_gl, does it support sprite batching?

**Comment by prime31** [comment]
yes, sokol is perfectly well suited for gamedev. sokol_gl would be fine if you were OK with a slightly limited render setup. It does queues up all draw calls (batched where possible) in a command buffer and dumps them all at the end of the frame.

**Comment by floooh** [comment]
Yes, with the recent improvements for the sokol-fontstash header (which essentially implements draw call batching), sokol-gl can be used for sprite rendering. As long as the texture (and some other state) doesn't change , geometry primitives will be merged across sgl_begin_*() and sgl_end().

You need to put group your sprite images into few texture atlasses first though, to minimize texture switches.

So sokol-gfx + sokol-gl should be fine.

sokol-app on the other hand might be a bit too bare-bones for a cross-platform game (it's fine for use with WebAssembly, but especially on Linux, a more robust wrapper like SDL might be the better option).

**Comment by gavriil07** [comment]
I also see there is already a dear imgui port :) that makes sokol a great candidate for my game, great job, thank you!

**Comment by hbiblia** [comment]
> Sí, con las recientes mejoras en sokol-gl para el encabezado sokol-fontstash (que esencialmente implementa el procesamiento por lotes de llamadas a dibujos), sokol-gl se puede usar para la representación de sprites. Mientras la textura (y algún otro estado) no cambie, las primitivas de geometría se fusionarán en sgl_begin_*() y sgl_end().
> 
> Sin embargo, primero debe agrupar sus imágenes de sprites en pocas texturas de atlas para minimizar los cambios de textura (el procesamiento por lotes solo puede ocurrir entre cambios de textura).
> 
> Así que sokol-gfx + sokol-gl debería estar bien.
> 
> sokol-app, por otro lado, puede ser demasiado básico para un juego multiplataforma (está bien para usar con WebAssembly, pero especialmente en Linux, un envoltorio más robusto como SDL podría ser la mejor opción).

Seria genial tener un tutorial con sokol-gfx + sokol-gl para un mini-juego 2D con sprites
