### ISSUE TITLE
iOS simulator constant buffer alignment requirements

### ISSUE THREAD

**Issue by pjako** [floooh/sokol#256]
Constant Buffer in the iOS simulator have a alignment requirement of 256 instead of 4.

**Comment by floooh** [comment]
Btw, you're right about the 4-byte alignment, at least the iOS Simulator docs say so. Not sure why I assumed 16 bytes:

<img width="541" alt="Screen Shot 2020-01-28 at 5 18 22 PM" src="https://user-images.githubusercontent.com/1699414/73282689-4db7be80-41f2-11ea-9e6e-bcf646f83254.png">
