### ISSUE TITLE
sokol_gfx: Metal shader, binary main method is hard coded to main0

### ISSUE THREAD

**Issue by pjako** [floooh/sokol#26]
Hey, I'm just trying to adjust the oryol shader compiler to Sokol.
Stumbled over this problem:
spirvCross names the main function for vs/fs this way: "main0"
In metal sokol_gfx the main method for binary vs/fs shader is set to: "_main"

**Comment by floooh** [comment]
Ah looks like I forgot to document this, but it should work with the .vs.entry members, like this:

```c
    /* shader as precompiled metal lib */
    sg_shader shd = sg_make_shader(&(sg_shader_desc){
        .vs = {
            .uniform_blocks[0].size = sizeof(vs_params_t),
            .entry = "main0",
            .byte_code = vs_bytecode,
            .byte_code_size = sizeof(vs_bytecode)
        },
        .fs = {
            .entry = "main0",
            .byte_code = fs_bytecode,
            .byte_code_size = sizeof(fs_bytecode)
        }
    });
```
The byte code must be in 2 blobs though if the main entry name is identical. If you already tried this and it doesn't work it must be a bug, but from looking over the code I don't see an obvious bug:

https://github.com/floooh/sokol/blob/c4623b95d9a1ce53558b93fe9ec0a335b1fca93b/_sokol_gfx_metal.impl.h#L1075

**Comment by pjako** [comment]
I did not look into what _sg_def was doing, but is seems obvious now. Defined a custom .entry, works now. Thanks!
