### ISSUE TITLE
sokol_gfx.h: assertion failed when using GLES2 backend

### ISSUE THREAD

**Issue by datalus** [floooh/sokol#267]
When compiling with clang on Windows (and I assume pretty much everywhere) I get this error on line 10453:

error: no member named 'attrs' in '_sg_gl_shader_t' 
SOKOL_VALIDATE(!_sg_strempty(&shd->attrs[attr_index].name), _SG_VALIDATE_PIPELINEDESC_ATTR_NAME);

To me, it just seems there was a typo there. I will submit a PR for this fix.

**Comment by floooh** [comment]
Hmm, this is indeed a fairly obvious bug caused by a recent "code cleanup". I'll first need to find out why this wasn't caught by the CI before applying your fix. 

Anyway... thanks for the ticker and PR :)

**Comment by floooh** [comment]
...ah ok, CI currently doesn't catch that because I'm only building emscripten stuff with SOKOL_GLES3. I'll first fix that and then merge your PR...
