### ISSUE TITLE
Assertation failed

### ISSUE THREAD

**Issue by caiiiycuk** [floooh/sokol#270]
Hi. I am not sure is it a bug in sokol, probably I doing something wrong. I periodically have this error on app start:

```
bin: ../js-dos-cpp/clients/sokol/sokol_gfx.h:11535: void sg_begin_default_pass(const sg_pass_action*, int, int): Assertion `(pass_action->_start_canary == 0) && (pass_action->_end_canary == 0)' failed.
```

Sometimes it's work, maybe problem is in mutltithread code... Source code is here
https://github.com/caiiiycuk/js-dos/blob/sokol_protocol_dev/js-dos-cpp/clients/sokol/js-dos-protocol-sokol.cpp

Thanks!

**Comment by floooh** [comment]
That assert basically means that either the sg_pass_action struct wasn't properly zero-initialized, or has been scribbled over through some memory corruption problem.

Looking at the code it looks to me like most things in the GfxState class are not properly zero-initialized, for instance:

Here, the bind struct is not zero-initialized before things are written to it:

https://github.com/caiiiycuk/js-dos/blob/07908208551741195758cbd31f1cfc4e5a717fda/js-dos-cpp/clients/sokol/js-dos-protocol-sokol.cpp#L50

And the entire pass-action struct is not zero-initialized (meaning there's random junk in the two "canary" items at the start and end:

https://github.com/caiiiycuk/js-dos/blob/07908208551741195758cbd31f1cfc4e5a717fda/js-dos-cpp/clients/sokol/js-dos-protocol-sokol.cpp#L41

Remember, these are all plain C structs, there's no constructor which sets the struct members to zero. You either need to memset() those structs to zero in the GfxState constructor, or initialize them via C99 designated-init like:

```
    // either set everything to zero:
    bind = { };
    // or initialize as a whole, which sets the missing members to zero:
    bind = {
        .vertex_buffers[0] = ...;
        .index_buffer = ...;
    }
```
...same for the sg_pass_action struct.

Unfortunately, depending on compiler, compiler version, and C++ vs C mode, the simple ```= { };``` produces warnings, so a ```= { 0 };``` may be needed instead. Also note that not all compilers support mixing C99 code and C++ code like that (unless you use the new C++20 designated-init feature).

**Comment by caiiiycuk** [comment]
Amazing how much I was far from understanding how designators work. :) Now everything works perfectly!
