### ISSUE TITLE
sokol_args: Assert on parsing URL arguments

### ISSUE THREAD

**Issue by bqqbarbhg** [floooh/sokol#273]
sokol_args.h asserts on startup with Emscripten if there are any arguments.

During parsing there is an assert:
```c
EMSCRIPTEN_KEEPALIVE void _sargs_add_kvp(const char* key, const char* val) {
    SOKOL_ASSERT(_sargs.valid && key && val);
```

but the `valid` flag is set only after parsing:

```c
    #if defined(__EMSCRIPTEN__)
        /* on emscripten, ignore argc/argv, and parse the page URL instead */
        sargs_js_parse_url();
    #else
        /* on native platform, parse argc/argv */
        _sargs_parse_cargs(desc->argc, (const char**) desc->argv);
    #endif
    _sargs.valid = true;
```

I fixed this locally by moving the assignment (https://github.com/bqqbarbhg/bq_websocket/commit/eba8bd16a50bfe155fc9e83f0670e1712b253b4d), but maybe the assert shouldn't require `valid`?

**Comment by floooh** [comment]
Hi, yep, clearly a bug. Guess that's one combination (debug mode and using args) that never happens when I'm working on my emulators.

I'll remove the _sargs.valid check in _sargs_add_kvp(), but your fix would work as well.

Thanks for the bug report!
