### ISSUE TITLE
sokol_gfx: Ability to get underlying handles without using internal API

### ISSUE THREAD

**Issue by gingerBill** [floooh/sokol#274]
sokol_gfx: Ability to get underlying handles without using internal API.

It is currently possible to get the underlying handles through something like this:

```
info = sg_query_XXX_info(handle);
internal_data = _sg_lookup_XXX(&_sg.pools, info.slot.res_id);
internal_data->gl.YYY // or whatever
```

However, if you are using sokol_gfx not in C or C++ and binding to it, you cannot do this second step to get the necessary data.

One of the reasons I require this is for doing `glReadPixels`, since sokol_gfx does not have an equivalent.

**Comment by floooh** [comment]
I would recommend that you create a small "extension header" with additional functions you need to access the required private data and functions (or even create a "high level" function which wraps glReadPixels().

Basically create a small header which is split into a declaration part (which declares your own extension function), and an implementation part which has the actual code.

Then include that header in the same file where your sokol_gfx.h implementation is included, *after* sokol_gfx.h. That way your own extension code can access all the "guts" (private functions and data) of sokol_gfx.h, including all the backend-specific stuff.

Like this basically (for the source file which includes the implementations):

```c
#define SOKOL_IMPL
#define SOKOL_GLCORE33
...
#include "sokol_gfx.h"
#include "sokol_gfx_ext.h"
```

The sokol_gfx_ext.h header would contain your own extension functions, and this can access the private data and functions of all sokol-headers included before it.

And everywhere else in the project where you need to call the extension functions, you would also include ```sokol_gfx_ext.h``` right after ```sokol_gfx.h``` to access the new public functions.

**Comment by gingerBill** [comment]
Okay, and thank you for the quick answer. That's fine by me and what I have been doing already. Just wondering behind the rationale that was all.
