### ISSUE TITLE
Metal / GLES3 on iOS produces blank screen output.

### ISSUE THREAD

**Issue by OkanArikan** [floooh/sokol#281]
When using sokol-app + sokol-gfx on iOS using any of the samples at sokol-samples/sapp, I get a black screen output. This happens with both SOKOL_METAL and SOKOL_GLES3 and on the device and in the simulator.

Doing a frame capture shows that the correct rendering is being done, but it's not presented on the display.

The same code with SOKOL_METAL backend works on MacOS as expected.

My main:

```
sapp_desc sokol_main(int argc, char* argv[]) {
    return (sapp_desc){
        .init_cb = init,
        .frame_cb = frame,
        .cleanup_cb = cleanup,
        .width = 800,
        .height = 600,
        .sample_count = 1,
        .high_dpi = true,
        .gl_force_gles2 = false,
        .window_title = "Cube (sokol-app)",
    };
}
```

and init:
```
sg_setup(&(sg_desc){
        .gl_force_gles2 = sapp_gles2(),
        .mtl_device = sapp_metal_get_device(),
        .mtl_renderpass_descriptor_cb = sapp_metal_get_renderpass_descriptor,
        .mtl_drawable_cb = sapp_metal_get_drawable,
        .d3d11_device = sapp_d3d11_get_device(),
        .d3d11_device_context = sapp_d3d11_get_device_context(),
        .d3d11_render_target_view_cb = sapp_d3d11_get_render_target_view,
        .d3d11_depth_stencil_view_cb = sapp_d3d11_get_depth_stencil_view
    });
```

**Comment by floooh** [comment]
Hmm, I cannot reproduce here (at least on simulator, need to charge my iPad Mini4 first to test on device).

What Xcode, iOS SDK and iOS version are you using (here it is: Xcode 11.3.1, iOS SDK 13.2, and iOS version 13.3).

I tested both with the unmodified sokol-app samples (high_dpi false and sample_count 4), and your setup (high_dpi true and sample_count 1), both on GL and Metal.

These are the original samples, running on the simulator with the Metal backend:

<img width="758" alt="Screen Shot 2020-04-12 at 1 36 48 PM" src="https://user-images.githubusercontent.com/1699414/79067982-b972d900-7cc3-11ea-9fb5-03cd8c334755.png">
<img width="755" alt="Screen Shot 2020-04-12 at 1 38 41 PM" src="https://user-images.githubusercontent.com/1699414/79067983-bb3c9c80-7cc3-11ea-820a-508dc8e7337e.png">

I'll try to test on hardware next, I may need to update the OS first though to match my dev setup.

**Comment by floooh** [comment]
hmm, my iPad won't update to the latest beta version, I need to figure out why first :/

**Comment by OkanArikan** [comment]
You are right, this is a user error: I had scene delegate enabled (which is true by default it seems) which swapped sokol-app UI with a blank UI hierarchy.

Thank you!
