### ISSUE TITLE
setting fragment depth in shader.

### ISSUE THREAD

**Issue by RicoP** [floooh/sokol#298]
Hi there!

I kinda would like to set the Z-Depth of my pixel directly in my fragment shader.

I know that in regular opengl I can use gl_FragDepth  for that https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/gl_FragDepth.xhtml

What i try right now is to set both frag_color and frag_depth in my FS
```
out vec4 frag_color;
out float frag_depth;
```
However I am not quite sure how I should configure my pipeline and pass_action. 

I am using a custom pipeline for my fragment shader which consistes of two triangles which strech across the entire screen (a simple SDF shader) and then I use sokol_gl to render 3D geometry. 

My idea is to set the z-depth for every pixel in my fragment shader and then draw my regular 3D geometry.

**Comment by RicoP** [comment]
Maybe to make my question a bit clearer, I want to do that https://iquilezles.org/www/articles/raypolys/raypolys.htm

**Comment by floooh** [comment]
I haven't tried that yet, but I'm not aware of any required changes in the pipeline or pass state. You need to assign to gl_FragDepth though, e.g. a GLSL shader would look like this:

```glsl
in vec4 color;
out vec4 frag_color;

void main() {
    frag_color = color;
    gl_FragDepth = ...;
}
```
I tried that in the cube-sapp sample with the D3D11 backend, and SPIRV-Cross seems to understand and translate this properly.

One thing to be aware of is that assigning depth in the pixel shader disabled early-Z optimizations (e.g. normally the pixel shader doesn't even run if the z-test would discard the pixel).

I'm currently not sure if the depth buffer content stays valid between passes on all backends, so when in doubt first try to render depth and color in the same pass first.
