### ISSUE TITLE
sokol_gfx: more image information in sg_query_image_info

### ISSUE THREAD

**Issue by edubart** [floooh/sokol#303]
I've run into a use case where I need to retrieve more `sg_image` information such as **width** and **height** but I've noticed `sg_image_info` does not contain that. Other creation info may be useful too. Having this API will simplify my use case where I won't need to encapsulate `sg_image` into another structure to hold useful texture information.

**Comment by edubart** [comment]
I've add both width and height in PR #304

**Comment by floooh** [comment]
Agreed that's a useful fix. I'm focusing on PRs in the next couple of days, so the merge won't take long :)

**Comment by floooh** [comment]
I guess this can be closed now.

With the (somewhat recent) restructuring of the internal data structures (basically _sg_buffer_common_t, _sg_image_common_t etc...) it might make sense putting some more stuff into the sg_xxx_info structs (for instance the pixel format etc), but I guess it's fine to only do this when people actually need it :)

**Comment by edubart** [comment]
> but I guess it's fine to only do this when people actually need it :)

Indeed, otherwise that call will become heavier. I just noticed other option is to access  `_sg_image_common_t` directly through `_sg_lookup_image()` if `SOKOL_GP_IMPL_INCLUDED` is defined, this is lighter if you need to get the texture dimension in the draw loop.

**Comment by floooh** [comment]
> directly through _sg_lookup_image() if SOKOL_GP_IMPL_INCLUDED is defined

Yeah this works, but this is a private function and only available in the source code which includes the sokol_gfx.h implementation.

But you can use this technique to add your own extension functions to the sokol_gfx.h API through a separate "extension header". The implementation of this extension header can be included after the implementation of sokol_gfx.h (in the same source file), and that way you have access to all private functions and data structures from anywhere in your project.
