### ISSUE TITLE
Getting the dimensions of the monitor

### ISSUE THREAD

**Issue by medvednikov** [floooh/sokol#311]
It'd be nice to be able to get the dimensions of the monitor, like in `glfwGetVideoMode(glfwGetPrimaryMonitor()).width/height`

**Comment by floooh** [comment]
Hmm, what would you use this size for? (because there's no way to set the window size after sokol-app has been initialized, and no sokol-app functions can be called before it is initialized).

**Comment by medvednikov** [comment]
To create a fullscreen borderless window without using Apple's slow full screen mode.

Alternatively, `fullscreen` option could do that instead, since in the docs it's described as a "soft" fullscreen mode.

**Comment by floooh** [comment]
I prefer the "soft fullscreen" idea.

**Comment by floooh** [comment]
Closing the issue for now (same reasons as #313).
