### ISSUE TITLE
Crash in _dispatch_semaphore_dispose when restarting sokol in Metal backend

### ISSUE THREAD

**Issue by Fra-Ktus** [floooh/sokol#320]
I need to call sg_shutdown to reset my renderer on some user changes such as offscreen buffer size.

When you do this you will have a crash in _dispatch_semaphore_dispose:

```
libdispatch.dylib`_dispatch_semaphore_dispose:
 
...

    0x103f30962 <+31>: movq   0x30(%rdi), %rcx
    0x103f30966 <+35>: subq   %rcx, %rax
    0x103f30969 <+38>: leaq   0x2a6f7(%rip), %rcx       ; "BUG IN CLIENT OF LIBDISPATCH: Semaphore object deallocated while in use"
    0x103f30970 <+45>: movq   %rcx, 0x555d9(%rip)       ; gCRAnnotations + 8
    0x103f30977 <+52>: movq   %rax, 0x55602(%rip)       ; gCRAnnotations + 56
->  0x103f3097e <+59>: ud2    
```

The solution I found is simply to signal the semaphore and release it in the _sg_mtl_discard_backend.

I added this code at the end of _sg_mtl_discard_backend:

```
    for (int i = 0; i < SG_NUM_INFLIGHT_FRAMES; i++) {
        dispatch_semaphore_signal(_sg_mtl_sem);
    }
    _sg_mtl_sem = nil;
```

There may be a better way to do this but that fixes the crash.

**Comment by floooh** [comment]
Thanks for the bug report, it's true that "restarting" the sokol libraries isn't tested all that well, but it needs to work of course.

I'll see if I can also can come up with a test or sample for this, so it's less likely to regress in the future.

**Comment by Fra-Ktus** [comment]
I can confirm it works like a charm for the DirectX 11 and Metal backend using this patch.

**Comment by floooh** [comment]
FYI, I started on a new "mega-sample" which will use features from as many sokol headers as makes sense, and will be "restartable", while also tracking memory usage (since such a demo is a nice memory leak test). I'll add your fix to sokol-gfx while working on this, it'll be a few more days though.

**Comment by floooh** [comment]
btw I found a similar issue in the web backend in sokol_audio.h: https://github.com/floooh/sokol/issues/324

I'm using this new sample for testing: https://floooh.github.io/sokol-html5/restart-sapp.html

(the version under the link doesn't use sokol_audio.h yet)
