### ISSUE TITLE
sokol_gfx.h: Can't clear just stencil buffer for an offscreen pass with GL3.3

### ISSUE THREAD

**Issue by mgerdes** [floooh/sokol#340]
I'm trying to do something like this

       sg_pass_action pass_action = {
            .colors[0] = { .action = SG_ACTION_DONTCARE },
            .depth = {
                .action = SG_ACTION_DONTCARE,
            },
            .stencil = {
                .action = SG_ACTION_CLEAR,
            },
        };
        sg_begin_pass(pass, &action);

but this assert is failing: https://github.com/floooh/sokol/blob/a3278884e3895d996e79a38bd74e44826e3efb74/sokol_gfx.h#L6293

I narrowed it down and it looks like the problem is here: https://github.com/floooh/sokol/blob/a3278884e3895d996e79a38bd74e44826e3efb74/sokol_gfx.h#L6288

This documentation (https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glClearBuffer.xhtml) says glClearBufferuiv can only be called with GL_COLOR, so I think it should be changed to glClearBufferiv? That fixes the issue for me.

**Comment by floooh** [comment]
Yep, looks like an oversight on my part. I'll commit a fix ASAP.

Thanks for the bug report!

**Comment by floooh** [comment]
Ok, fixed. On macOS (Big Sur Beta) the old code wasn't actually throwing an error (I didn't check whether the stencil buffer is actually cleared though with *uiv()), but the documentation is pretty clear about using glClearBufferiv().
