### ISSUE TITLE
Please consider providing a context pointer to the metal callbacks

### ISSUE THREAD

**Issue by trojanfoe** [floooh/sokol#358]
The `sg_metal_context_desc` structure uses two callbacks to get a renderpass descriptor and a drawable from the Metal implementation and this is made difficult to implement unless a context pointer can be provided to the metal view/layer.

    typedef struct sg_mtl_context_desc {
        const void* device;
        const void* (*renderpass_descriptor_cb)(void* cb_context);
        const void* (*drawable_cb)(void* cb_context);
        void* cb_context;         // NEW
    } sg_metal_context_desc;

This `cb_context` would then be passed back in the callbacks, which the implementation would then use as follows:

    static const void* drawableCallback(void* cb_context)
    {
        CAMetalLayer* metalLayer = (__bridge CAMetalLayer*)cb_context;
        return (__bridge const void*)[metalLayer nextDrawable];
    }

At the moment I am left with keeping the metal layer set in a global, or using a singleton pattern, which no showstopper, but is bad practise.  I believe all callbacks are devalued if they don't pass a context back, regardless of the application.

**Comment by floooh** [comment]
Makes sense. This should probably be a separate set of callbacks (similar to the callbacks in sokol_app.h's sapp_desc), and to be consistent I would name the arg "user_data".

**Comment by trojanfoe** [comment]
Thanks for considering the change.  I think an alternative set of callbacks might make the interface a bit "busy", a bit like it's done with sapp_desc.  Are you concerned about breaking changes?  I personally wouldn't be so concerned given how easy it is to convert from the non user_data callbacks to the user_data ones... it must complicate the code to deal with two different sets?

**Comment by floooh** [comment]
> Are you concerned about breaking changes?

I'll think about it, maybe a breaking change is ok. Since I recently wrapped this stuff in the optional sokol_glue.h header, at least apps which use sokol_gfx.h together with sokol_app.h would not be affected by breaking changes in this specific case.

**Comment by floooh** [comment]
This commit has alternative userdata callback functions working for Metal, and similar changes for the other APIs are on the way:

https://github.com/floooh/sokol/commit/b5d0b089f8b0e096508b5ae1720f4cf0569ce96e

sg_context_desc has a new ```void* user_data``` and the backend-specific sg_xxx_context_desc structs have a second set of functions pointers with a userdata argument.

**Comment by floooh** [comment]
Hmm.. I will however do another change to my fix, the user_data pointer should go into the backend specific context structs, I think that makes more sense.

**Comment by floooh** [comment]
...ok there can now be different userdata pointers for each backend. For Metal I've added a test here in the Metal-backend-specific samples:

https://github.com/floooh/sokol-samples/commit/b258c820236849677c9c3c662c3113ef34ec9239

(and I will do the same for the D3D11-specific samples, and the generic sapp-samples will test the 'no userdata' case.

**Comment by floooh** [comment]
Ok, this should all work now for the Metal, D3D11 and (WIP) WGPU backends. The GL backend has no callback functions.
