### ISSUE TITLE
On the subject of running with no depth/stencil surface

### ISSUE THREAD

**Issue by trojanfoe** [floooh/sokol#359]
I note that in the `sokol_app.h` file you have the comment:

    sapp_desc needs a bool whether to initialize depth-stencil surface

Wouldn't it be enough to simply provide `SG_PIXELFORMAT_NONE` when initialising sokol_gfx to indicate this?  When writing a 2D game you don't want a depth/stencil buffer so I think it would be useful to make it optional.

**Comment by floooh** [comment]
For sokol_gfx.h yes (and it should already work that way if you don't use sokol_gfx.h together with sokol_app.h), but sokol_app.h needs a hint in sapp_desc wether a depth/stencil surface should be created for the default framebuffer.
