### ISSUE TITLE
CImgui Docking branch

### ISSUE THREAD

**Issue by OAguinagalde** [floooh/sokol#361]
Is it possible right now to use the docking features of the docking branch of Dear Imgui?
I've managed to compile a project and tried enabling the feature right after creating the Imgui context but seems like it's not working.

**Comment by floooh** [comment]
I haven't played around much with the docking branch yet unfortunately (definitely not with cimgui, but I seem to remember that I did some experiments once in my emulator project, but that was with the ImGui C++ API), but that might have been before sokol_imgui.h existed, and I don't remember if I had to do any code changes.

So TL;DR: currently it's definitely not guaranteed that sokol_imgui.h works with the docking branch :)

**Comment by freneticmonkey** [comment]
I'm currently using the docking branch and it seems to be working well so far.

**Comment by OAguinagalde** [comment]
> I'm currently using the docking branch and it seems to be working well so far.

Yeah, the docking branch "works". As in, you get to use some of the features of that branch features such as docking. However (and now that I read my own issue I realize it was impossible to know what I meant) the "multiple viewport" stuff doesn't work. Even if you enable it, you can't really get the imgui windows out of the main window. I believe I saw someone on twitter claiming to have achieved that with a personal branch of sokol, but I don't think I would be up to the task of understanding what was going on there and forgot about it for now.

Uuuh, let me know @freneticmonkey If I'm actually wrong and it's possible to have the multi viewport stuff working and I just didn't manage!

**Comment by freneticmonkey** [comment]
Ah yes I had forgotten about that.  In order to get multi-window support it would be a bunch of work to handle creating and destroying windows etc.  I haven't been using that, only the docking functionality.
