### ISSUE TITLE
Websockets anyone?

### ISSUE THREAD

**Issue by frink** [floooh/sokol#367]
I know `sokol_fetch.h` just came out, but I'm curious about doing real time bidirectional communication with Sokol.

**Is there any plan to support cross platform websockets or am I reaching for the stars here?**

...Let me know what you think!

**Comment by floooh** [comment]
Emscripten already has a socket API wrapper around WebSockets. It only works in non-blocking mode, but there's no way around that. But true, a proper cross-platform implementation would need a bit of wrapper code (e.g. send- and receive-buffers).

I have an old C++ gist laying around here which implements a cross-platform native/web socket client:

https://gist.github.com/floooh/b4d25d0e11ef2be91dd19cb974bcc7a6

...this also needs a counterpart on the server side though. We wrote a small server in Go which opened two ports, one for native clients which connect directly via TCP, and one for WebSocket clients which would connect to another port with a WebSocket proxy inbetween (we used https://github.com/gorilla/websocket).

The thing is though, currently I don't have a need for this, so such headers wouldn't get much testing from my side.

For a "proper" networked game I would probably look at libraries like these first:

https://github.com/HumbleNet/HumbleNet

http://enet.bespin.org/

**Comment by frink** [comment]
In searching issues before I posted this I found https://github.com/bqqbarbhg/bq_websocket mentioned in #273 from @bqqbarbhg. This looks like a good candidate to borrow code. It in C and already mature with the same permissive license. I figured if you've got `sokol_fetch.h` and `sokol_audio.h` that `socok_websocket.h` probably makes sense...
