### ISSUE TITLE
Cannot show Android soft-keyboard for imgui text input

### ISSUE THREAD

**Issue by mgodf** [floooh/sokol#373]
Is there any way to show the soft keyboard on Android when an imgui text input has focus? Cut/Copy/Paste/Select All are also missing. I'm working from imgui-sapp in Sokol Samples as a template.

**Comment by floooh** [comment]
No, virtual keyboard isn't implemented in the sokol_app.h Android backend unfortunately, IFIR when we looked into this there wasn't a way to do this through the C APIs, only via Java, and Java can't be integrated into C source files with the Android NDK (like it is possible to integrate Javascript code into C code in the emscripten SDK).

I haven't specifically looked into clipboard access, but I think this has the same problem that there's only Java API but no C API.
