### ISSUE TITLE
WebGPU broken

### ISSUE THREAD

**Issue by Maeiky** [floooh/sokol#378]
Hello, I'm trying to compile the WebGPU examples, but it seems even with a successfully build, there is no way to test it.

Trying it with Firefox Nightly:
>Uncaught (in promise) TypeError: gpuContext.getSwapChainPreferredFormat is not a function
    _sapp_emsc_wgpu_init

Trying it with Chrome Canary:
>Uncaught TypeError: Failed to execute 'createBindGroupLayout' on 'GPUDevice': required member entries is undefined.

So even with the [precompiled example](https://cwc-test.github.io/sokol-wgpu-preview/blend-sapp.html)

Is there a way to get it working, or it's just broken?
If it's the case, maybe just notice it somewhere.

**Comment by floooh** [comment]
See my answer here: https://github.com/floooh/sokol/issues/377
