### ISSUE TITLE
sokol_gfx. Issue with pipeline validation. Casting pointer to bool can make a non 0 pointer to evaluate false.

### ISSUE THREAD

**Issue by OAguinagalde** [floooh/sokol#379]
I'm randomly getting crashes on the pipeline creation, same executable, sometimes will crash sometimes not.

I've found (almost certain) that the issue is casting a pointer to bool in `_sg_validate`. But feel free to read the whole thing, which I wrote as I was debugging this so also feel free to just go to the end haha.

__________________

I have modified `_sg_validate_pipeline_desc(const sg_pipeline_desc* desc)` in sokol_gfx.h to output some stuff for debugging purposes.

```log
09:54:03 INFO  sokol_gfx.h:12784: 000001E00C71E000
09:54:03 ERROR sokol_gfx.h:12794: if shd
09:54:03 ERROR sokol_gfx.h:12797: before validating shd
09:54:03 ERROR sokol_gfx.h:12559: _sg_validate2 with -shd-
09:54:03 ERROR sokol_gfx.h:12560: if (!(shd))

sg_pipeline_desc.shader missing or invalid

09:54:03 ERROR sokol_gfx.h:12799: after validating shd
09:54:03 ERROR sokol_gfx.h:12802: ccc
09:54:03 ERROR sokol_gfx.h:12823: ddd

^^^^  VALIDATION FAILED, TERMINATING ^^^^
Assertion failed: 0, file dep\Sokol\sokol_gfx.h, line 12570
```

And the code for the validation is something like this:

```c
log_info("%p", shd);
// This log prints the pointer of shd
//      09:54:03 INFO  sokol_gfx.h:12784: 000001E00C71E000
if (shd == NULL) {
    // Never gets here...
    log_error("if shd == NULL");
    custom_assert(false);
}
if (!shd) {
    // Never gets here...
    log_error("if !shd");
    custom_assert(false);
}
if (shd) {
    // Gets here! it means that "if (shd)" evaluates to true
    // Which makes sens because shd is a pointer != NULL
    log_error("if shd");
}
log_error("before validating shd");
_sg_validate2(shd, "shd", _SG_VALIDATE_PIPELINEDESC_SHADER);
log_error("after validating shd");
//SOKOL_VALIDATE(shd, _SG_VALIDATE_PIPELINEDESC_SHADER);
if (shd) {
    log_error("ccc");
    // ... some other stuff ...
}
log_error("ddd");
return SOKOL_VALIDATE_END();
```

So far so good, now let's see what happens in the call to _sg_validate2:

> _sg_validate2(shd, "shd", _SG_VALIDATE_PIPELINEDESC_SHADER);

This is a modified version of the original _sg_validate, so that I can debug better. Actually I made a macro but just for confirmation made it a explicit call here.

```c
_SOKOL_PRIVATE void _sg_validate2(bool cond, const char* thingy, _sg_validate_error_t err) {
    if (!cond) {
        log_error("_sg_validate2 with -%s-", thingy);
        log_error("if (!(%s))", thingy);
        _sg.validate_error = err;
        SOKOL_LOG(_sg_validate_string(err));
    }
}
```

So, as you can see here, the parameter `cond` is a bool, and we passed our pointer shd. while `if (shd)` evaluated evaluated true before, this time around, `if (!(shd))` is also evaluating true.

So, because it evaluates to true, it deems the shader as invalid, and eventually `return SOKOL_VALIDATE_END();` will deem the pipeline as not valid and assert false here.

```c
SOKOL_PRIVATE bool _sg_validate_end(void) {
    if (_sg.validate_error != _SG_VALIDATE_SUCCESS) {
        #if !defined(SOKOL_VALIDATE_NON_FATAL)
            SOKOL_LOG("^^^^  VALIDATION FAILED, TERMINATING ^^^^");
            SOKOL_ASSERT(false);
            // I never get here!
        #endif
        return false;
    }
    else {
        return true;
    }
}
```

So, how is this possible?

So after this, I made some more tests, and what is happening is that casting a pointer to bool, is causing it to fail. This code...

```c
log_info("shd pointer %p", shd);
log_info("true is %d", true);
log_info("false is %d", false);
log_info("NULL is %d", NULL);
if (!(bool)shd) {
    log_error("if (!(bool)shd)");
}
if ((bool)shd) {
    log_error("if ((bool)shd)");
}
if (shd == NULL) {
    log_error("if shd == NULL");
    custom_assert(false);
}
if (!shd) {
    log_error("if !shd");
    custom_assert(false);
}
if (shd) {
    log_error("if shd");
}
```

Makes this output...

```log
10:17:08 INFO  sokol_gfx.h:12784: shd pointer 000002B73B01C000
10:17:08 INFO  sokol_gfx.h:12785: true is 1
10:17:08 INFO  sokol_gfx.h:12786: false is 0
10:17:08 INFO  sokol_gfx.h:12787: NULL is 0
10:17:08 ERROR sokol_gfx.h:12789: if (!(bool)shd)
10:17:08 ERROR sokol_gfx.h:12803: if shd
```

Specially pay attention to this:

```c
if (!(bool)shd) {
    log_error("if (!(bool)shd)");
    // 10:17:08 ERROR sokol_gfx.h:12789: if (!(bool)shd)
}
if ((bool)shd) {
    log_error("if ((bool)shd)");
    // Never gets here
}
if (shd) {
    log_error("if shd");
    // 10:17:08 ERROR sokol_gfx.h:12803: if shd
}
```

I'm guessing this is not intentional and is a bug, buuut who knows. I also found this <https://www.viva64.com/en/w/v724/> which talks about it.

**Comment by floooh** [comment]
Hmm that's an interesting find, but I need to understand better what's happending. E.g. just casting a pointer to bool doesn't just seem to strip the upper bits, see here for instance:

https://www.godbolt.org/z/17Tnvn

What compiler are using, what language mode (C or C++), and what CPU/ISA are you compiling for?

**Comment by floooh** [comment]
PS: what is the message printed above:

```
^^^^  VALIDATION FAILED, TERMINATING ^^^^
```

This doesn't look like a "random" crash, but like a failed validation check, are you sure there haven't been shader compilation errors before (which would cause the shd pointer to be zero).

One way to find out would be to put a debug-printf to print the resolved shd pointer here:

https://github.com/floooh/sokol/blob/2cd00ec6c80d4ef05d0522c7c0a5de0fa6daaadd/sokol_gfx.h#L13255

**Comment by floooh** [comment]
...wait ignore my last comment, you already did that...

**Comment by floooh** [comment]
...also I just plugged your example code into godbolt, and I see a different output (and the output makes sense, the shd pointer is never evaluated as false):

https://www.godbolt.org/z/Gs7fzd

```
shd pointer 0x2b73b01c000
true is 1
false is 0
NULL is (nil)
if ((bool)shd)
if shd
END
```

I'm not sure what's going on there TBH.

**Comment by floooh** [comment]
It's important to note that the PVS-Studio article doesn't talk about ```bool``` but about custom BOOL types which are typedefed from integer. In this case everything makes sense. The 64-bit pointer is cast to a shorter integer type in which case the topmost 32 bits are clipped away.

But that's not the case in sokol_gfx.h, where bool is expected to be a builtin type (that's the case since C99 and generally in C++).

Do you have some sort of custom-defined bool type by chance?

**Comment by floooh** [comment]
...e.g. here is a way of how I can get the same result as you for the test code, by defining bool myself as an 8-bit integer and not including <stdbool.h>, but as soon as <stdbool.h> is included (which sokol_gfx.h does) this custom bool type is overwritten with the builtin bool type:

https://www.godbolt.org/z/rzExME

So I guess the better question is: do you have a non-standard stdbool.h, which defines bool as an 8-bit integer instead of the usual _Bool?

**Comment by OAguinagalde** [comment]
Found it!

```c
// main.c
#include <stdbool.h>
#include <assert.h>

// comment this include to make this crash
#include <flecs.h>

void main(void) {
    void* test = 0x000001E00C71E000;
    assert(test);
    assert((bool)test);
}
```

This is all you need to recreate it consistently. It's flecs. I haven't tried to look how exactly, since I have no time right now. But basically, in a folder with just `main.c`, `flecs.h`, `flecs.c` and compiling like so `cl main.c flecs.c /I .` that's enough to make it explode in the second assert. If I comment out `#include <flecs.h>` then everything is fine, it finishes without problem. I'm confused and intrigued, I'll get back to this soon.

flecs origin master from some hours ago btw

**Comment by OAguinagalde** [comment]
Had to look it up real quick, it seems to be this, around line 110:

```c
/* The API uses the native bool type in C++, or a custom one in C */
#ifndef __cplusplus
#undef bool
#undef true
#undef false
typedef char bool;
#define false 0
#define true !false
#endif
```

**Comment by randy408** [comment]
Flecs defines its own bool type, that's probably the issue here. There is a PR open to use C99 bools but there are modules on flecs-hub (e.g. flecs-meta) that need fixing before it's merged.

**Comment by floooh** [comment]
Hmm ok, as suspected. I will fix that one place with the shader pointer anyway, because I noticed that in most other places in the code I explicitely compare pointers to zero.

For "serious" projects I recommend including the implementation of sokol headers into their own compilation unit (like here: https://github.com/floooh/v6502r/blob/master/src/sokol.c), this would also such "pollutions" from unrelated headers.

**Comment by floooh** [comment]
I did a bit of code cleanup here: https://github.com/floooh/sokol/commit/342821c8452fff509107fe4ddc6318335208e3ea

This doesn't really fix the issue, just makes it more consistent with the other validate calls. A proper fix needs to happen outside (by not overriding the bool from stdbool.h).

**Comment by SanderMertens** [comment]
@OAguinagalde I just merged this PR which should solve the issue: https://github.com/SanderMertens/flecs/pull/206

**Comment by OAguinagalde** [comment]
Can confirm, everything working great now, thanks!
