### ISSUE TITLE
CoInitializeEx: no need to check in _saudio_backend_init

### ISSUE THREAD

**Issue by alittlesail** [floooh/sokol#381]
_SOKOL_PRIVATE bool _saudio_backend_init(void) {
    REFERENCE_TIME dur;
    if (FAILED(CoInitializeEx(0, COINIT_MULTITHREADED))) {
    	// no need to check, Because CoInitializeEx maybe invoked by other system(i.e SDL)
    }

**Comment by floooh** [comment]
Thanks, fixed. It's a bit unfortunate that CoInitializeEx returns a failure result in the case it's already initialized.
