### ISSUE TITLE
Cannot have vertex buffers non-interleaved in the same buffer, due to auto-stride calculation

### ISSUE THREAD

**Issue by SoylentGraham** [floooh/sokol#382]
This may be by design? I use this method on opengl for various things, but can't for the life of me remember if I can do it in metal or directx.

But to do it, you write a vertex buffer of one block of attributes, then a block of another;
```
float vertices[] = {
	// positions           
	0.0f,  0.5f, 0.5f,     
	0.5f, -0.5f, 0.5f,     
	-0.5f, -0.5f, 0.5f,     
	// colors
	1.0f, 0.0f, 0.0f, 1.0f,
	0.0f, 1.0f, 0.0f, 1.0f,
	0.0f, 0.0f, 1.0f, 1.0f
};
```
and then set the `attr[1].offset` to the start of the the colour block, and both attributes need a stride of 0. (I've used approach this on webgl, gles, opengl3, opengl4 etc with my own opengl lib)
If I leave stride as 0 though, it gets auto-calculated and the data is off.

To verify this, I just disabled the auto-calc and the assert that checks `stride!=0`. (Tested on ios & gles2)

Would this be against the lib policy to fit in?, or possibly just not doable on other backends?
I guess I also need to remind myself how this works with instancing too (but I guess that HAS to be a seperate buffer, so maybe not a problem)

**Comment by floooh** [comment]
Check this sample which does exactly this:

https://github.com/floooh/sokol-samples/blob/master/sapp/noninterleaved-sapp.c

In the pipeline layout description, use two buffer indices (0 and 1) in the vertex attributes:

https://github.com/floooh/sokol-samples/blob/8e212c995770e83aa6f9b84013236442367edeaa/sapp/noninterleaved-sapp.c#L75-L82

...and then in the bindings, configure set the buffer binding slots 0 and 1 to the same buffer, and use the offsets to point to the data chunks: 

https://github.com/floooh/sokol-samples/blob/8e212c995770e83aa6f9b84013236442367edeaa/sapp/noninterleaved-sapp.c#L96-L108

This is limited to 4 separate chunks (because there are four buffer bind slots, but you group associated vertex attribute groups in the same chunk to make up for this limitation.

**Comment by legends2k** [comment]
@floooh In `noninterleaved-sapp.c` I see the comment

> (vertex components in separate non-interleaved chunks in the same vertex buffers). Note that only 4 separate chunks are currently possible because there are 4 vertex buffer bind slots in sg_bindings, but you can keep several related vertex components interleaved in the same chunk.

and in the code

``` c
    state.bind = (sg_bindings){
        .vertex_buffers = {
            [0] = vbuf,
            [1] = vbuf                //  <--- WHY IS THIS NEEDED?
        },
        .vertex_buffer_offsets = {
            /* position components are at start of buffer */
            [0] = 0,
            /* byte offset of color components in buffer */
            [1] = 24 * 3 * sizeof(float)
        },
        .index_buffer = ibuf
    };
```

In bindings why should I give the same buffer twice?  Why can't I have all of the non-interleaved attribute data in one buffer and do

``` c
    state.bind = (sg_bindings){
        .vertex_buffers = {
            [0] = vbuf,
        }
    }

    // describe the attribute layouts
    pipe_desc.layout.attrs[ATTR_vs_position].format = SG_VERTEXFORMAT_FLOAT3;
    pipe_desc.layout.attrs[ATTR_vs_normal].format = SG_VERTEXFORMAT_FLOAT3;
    pipe_desc.layout.attrs[ATTR_vs_normal].offset = offset_of_normals;
```

Is it expected that for every attribute I've to specify `pipe_desc.layout.buffers` too?  Is this a limitation for a particular backend?

Aside: I noticed that `sg_bindings` has 8, not 4, vertex buffer slots now.

**Comment by floooh** [comment]
Hi, the attribute offset in the pipeline description is the offset of that vertex attribute from the start of a vertex. For instance if your vertex structure looks like this:

```c
typedef struct {
    float pos[3];
    float normal[3];
    float uv[2];
    float color[4];
} vertex_t;
```

Then the corresponding attribute offsets are:

- pos: 0
- normal: 12 (same as offsetof(vertex_t, pos)
- uv: 24 (same as offsetof(vertex_t, normal)
- color: 32 (same as offsetof(vertex_t, uv)

Usually sokol-gfx can compute those offsets, you only need to provide attribute offsets in special cases (for instance if your vertex structure has normals and uv coordinates, but for a specific drawing operation you only need positions and colors (and "skip" normals and uvs), in that case you need to explicitely provide the offset of the color attribute in the vertex structure).

The vertex buffer offsets in sg_bindings struct on the other hand is the start-offset of the vertex data to use in a buffer that's bound to a specific vertex buffer slot (e.g. you can skip data at the start the buffer). Usually this offset is a multiple of the size of a vertex structure. This is mainly useful for packing multiple mesh geometries into the same buffer, but can also be used for "de-interleaved" vertex components which reside in the same buffer.

**Comment by legends2k** [comment]
Thanks for the detailed reply @floooh.
