### ISSUE TITLE
sokol_gfx.h How to begin a pass configuring the full rectangle not only the width and height ?

### ISSUE THREAD

**Issue by roig** [floooh/sokol#383]
Hello! I'm new using your sokol_gfx and it rocks! 
I'm trying to apply the begin_pass to a concrete rectangle of the window, that clears only that specific region of the viewport.
The problem I'm facing is that I don't know how to specify the region to clear because _sg_gl_begin_pass function only accept w and h values but no origin values, so it always start from bottom-left of the corner:

glViewport(0,0,w,h)
glScissor(0,0,w,h)

Is there another way to specify it?

That's what I have now:
```     
sg_pass_action pass_action;
pass_action = { 0 };
pass_action.colors[0].action = sg_action::SG_ACTION_CLEAR;
std::memcpy(pass_action.colors[0].val, cam.clear_color.data(), sizeof(float) * 4);
sg_begin_default_pass(&pass_action, vp_size.x(), vp_size.y());
sg_apply_viewport(cam_vp.bottomLeft().x(), cam_vp.bottomLeft().y(), cam_vp.sizeX(), cam_vp.sizeY(), false);
sg_apply_scissor_rect(cam_vp.bottomLeft().x(), cam_vp.bottomLeft().y(), cam_vp.sizeX(), cam_vp.sizeY(), false);

// begin rendering...
...
```

**Comment by floooh** [comment]
Hi, it's not possible to use sg_begin_pass() to only clear a specific region (as this is only supported in GL, but not D3D11 or Metal). You'd need to do the clear yourself by setting the viewport and render and then perform a draw call to "clear" that area.
