### ISSUE TITLE
sokol_audio.h: compile error

### ISSUE THREAD

**Issue by alittlesail** [floooh/sokol#384]
sokol_audio.h(1273,1): error C2362: “goto dur”跳过了“%pS”的初始化操作

**Comment by floooh** [comment]
This doesn't make sense, sorry.

**Comment by floooh** [comment]
PS: Could this be a UTF-16 / ASCII / UTF-8 confusion when working on the source with different text editors? I remember having seen similar problems when exchanging files between Xcode on Mac (which uses UTF-8) and Visual Studio on Windows machine with the Chinese language pack active (which by default seems to use UTF-16 for source files).

**Comment by alittlesail** [comment]
ok, thanks, I will try it later

**Comment by alittlesail** [comment]
I try it again, it also compile error,  error code is C2362.
that mean local var can't not define between goto and goto flag.

code before modify:
_SOKOL_PRIVATE bool _saudio_backend_init(void) {
    REFERENCE_TIME dur;  // dur is define before goto
    if (FAILED(CoInitializeEx(0, COINIT_MULTITHREADED))) {
        SOKOL_LOG("sokol_audio wasapi: CoInitializeEx failed");
        return false;
    }

code after modify:
    /* CoInitializeEx could have been called elsewhere already, in which
        case the function returns with S_FALSE (thus it doesn't make much
        sense to check the result)
    */
    CoInitializeEx(0, COINIT_MULTITHREADED);
    
so that is nothing to do with language or textcoding
