### ISSUE TITLE
sg_draw with no elements causes fault in Metal

### ISSUE THREAD

**Issue by meshula** [floooh/sokol#397]
If you pass num_elements is zero here, 

```c
SOKOL_API_IMPL void sg_draw(int base_element, int num_elements, int num_instances) {
    SOKOL_ASSERT(_sg.valid);
```

Metal will abort during

```objc
        [_sg.mtl.cmd_encoder drawIndexedPrimitives:_sg.mtl.state_cache.cur_pipeline->mtl.prim_type
            indexCount:num_elements
            indexType:_sg.mtl.state_cache.cur_pipeline->mtl.index_type
            indexBuffer:_sg_mtl_id(ib->mtl.buf[ib->cmn.active_slot])
            indexBufferOffset:index_buffer_offset
            instanceCount:num_instances];
```

with

```
_MTLDebugValidateIndexBuffer:133: failed assertion `indexCount(0) must be non-zero.'
Program ended with exit code: 9
```

I suggest either returning immediately from sg_draw for zero num_elements, or adding:

```c
    SOKOL_ASSERT(num_elements > 0);
```

Of course the message from Metal is clear enough, but it's not an issue for OpenGL, so my feeling is that Sokol should catch portability problems if it can.

**Comment by floooh** [comment]
If GL just skips the draw I guess it's best if sg_draw() also skips (I'll check how D3D behaves too).

Thanks for the bug report!

**Comment by floooh** [comment]
Ok, fixed. I'm simply skipping draws with zero elements or instances. I checked D3D11's behaviour and this also skips without error in both situations, so the behaviour makes sense for all backend APIs I think.

I still added some assert checks to make sure the sg_draw() args are not negative (it would actually make more sense to turn all args into unsigned integers, but I'll defer changes to the public API to when I'm integrating my language-bindings-experiments).
