### ISSUE TITLE
sokol_args.h: also parse argc/argv in emscripten build

### ISSUE THREAD

**Issue by thehink** [floooh/sokol#412]
Have a kinda rare use-case where I need to supply args to a webassembly app running locally in an ios webview. The problem is that ios doesn't allow sending query parameters when loading html from filesystem.

My first instinct was to use argc/argv instead but was a bit surprised when I saw that all code for parsing argc/argv was disabled for emscripten. Since emscripten does supports populating argc/argv via `Module.arguments`.

Tried to remove all ifdefs that disable parsing of argc/argv and got it to work.

If you think this is reasonable use-case I would be happy to create a PR.

**Comment by floooh** [comment]
Yeah makes sense. 

I wonder if the emscripte code path could simply do both? First call ```_sargs_parse_cargs()``` to populate the key/value store with any arguments coming in via argc/argv, and then add any additional URL query parameters by calling  ```sargs_js_parse_url()```?

**Comment by thehink** [comment]
> Yeah makes sense.
> 
> I wonder if the emscripten code path could simply do both? First call `_sargs_parse_cargs()` to populate the key/value store with any arguments coming in via argc/argv, and then add any additional URL query parameters by calling `sargs_js_parse_url()`?

Yes this is exactly what I tried and it seems to work fine at first glance.

**Comment by floooh** [comment]
Ok :) Please provide a PR which works for you, and then I can check the code which currently uses URL parameters and merge the PR.

**Comment by floooh** [comment]
Fixed in https://github.com/floooh/sokol/pull/413
