### ISSUE TITLE
Audio doesn't work on iPhone without extra code to activate AVAudioSession

### ISSUE THREAD

**Issue by oviano** [floooh/sokol#431]
A slightly odd one; audio works fine on all platforms I have tried, which are macOS, tvOS, iOS, Windows and Android...with the exception of my iPhone X.

On this device, it's necessary to have the following lines before starting the audio:

    /* activate audio session */
    AVAudioSession* audio_session = [AVAudioSession sharedInstance];
    [audio_session setCategory: AVAudioSessionCategoryPlayback withOptions:AVAudioSessionCategoryOptionDefaultToSpeaker error:nil];
    [audio_session setActive:true error:nil];

...and then presumably these lines to deactivate it afterwards:

    /* deactivate audio session */
    [[AVAudioSession sharedInstance] setActive:false error:nil];

It's only the iPhone that needs this. An iPad running the same version of iOS (14.2) outputs audio without the above lines.

I tried adding these lines to sokol_audio.h but I started running into problems as these are objective C calls, so maybe it's ok as it is, and the responsibility of the application to deal with this? Seems slightly off-beat that one platform needs this extra initialisation in order to work though.....

**Comment by floooh** [comment]
Hmm, very strange (that it works on iPad but not iPhone - I only test on an iPad mini 4 since I don't have an iPhone). 

IMHO the code should go into sokol_audio.h (which means the implementation needs to be compiled as ObjC, a bit of a shame but not that critical since sokol_app.h and sokol_gfx.h need to be compiled as ObjC anyway).

**Comment by oviano** [comment]
It would be probably be useful if someone else backed up my findings.

Also, I had a quick look at miniaudio and that does make this call for iOS platforms, but interestingly there is a optional configuration flag to disable it from doing so.

**Comment by oviano** [comment]
Also, just to add that according to this page...

https://developer.apple.com/library/archive/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/HandlingAudioInterruptions/HandlingAudioInterruptions.html#//apple_ref/doc/uid/TP40007875-CH4-SW1

(specifically table 3.2)

...the application needs to be responsible for activating/deactivating the audio when the application is interrupted (for a phone call, alarm etc).

So unless sokol_audio is going to implement support for this kind of thing, maybe it does after all beyond at the application level and sokol_audio remains the barest thin-layer? I haven't checked out the other sokol audio backends to see how they work, so that might not be correct.

**Comment by oviano** [comment]
Ok, I've worked through this and figures out some fixes.

https://github.com/floooh/sokol/pull/433

Let me know if you want me to tweak anything, I've tried to implement the code in the same style.

**Comment by floooh** [comment]
Ok, closing this because the PR has been merged!
