### ISSUE TITLE
Move `What's new` section from readme to a changelog file

### ISSUE THREAD

**Issue by serkonda7** [floooh/sokol#439]
I think you should move the notes on new features into a changelog file and link it because the readme already has grown huge in size and most of it (old entries) are not important to be loaded with the main GitHub page.

**Comment by iboB** [comment]
second that!

Perhaps just leave the most recent entry in the readme

**Comment by serkonda7** [comment]
That's a good idea too

**Comment by floooh** [comment]
Yeah good point. I would simply link from the README.md into the CHANGELOG.md though and not keep the latest entries in the readme (that's too much hassle when updating).

**Comment by floooh** [comment]
Ok, there's now a separate [CHANGELOG.md](https://github.com/floooh/sokol/blob/master/CHANGELOG.md)
