### ISSUE TITLE
Just wanted to say thank you

### ISSUE THREAD

**Issue by sherjilozair** [floooh/sokol#445]
Thank you for writing Sokol. I am using it to make a small game, and it's been an absolute joy to use such a well-designed and powerful API. The simplicity of C99 and the simplicity of Sokol is refreshing and therapeutic, and makes me come back to programming in the evenings and weekends and holidays.

As a game developer, I don't want to deal with platform-level implementation details, but still want control over the whole stack instead of dealing with a black box like most game engines are. Sokol successfully rejects the idea that powerful software needs to be complex and opaque. So thanks for not only writing Sokol but proving that it can be written.

**Comment by slmjkdbtl** [comment]
Want to add to this. Despite for being a very good software, I also really like the community here. Floooh and everyone are always super genuine and nice to every person and every discussion, which of course leads to productivity and positivity (I honestly browse the issue / pr tab for pleisure). Good tools bring good works, I really feel people in this community are all genuine dedicated and respectful creators, let's bring more fun softwares to the world!

**Comment by SanderMertens** [comment]
I second this! I can't think of a library I've used (open source or otherwise) that is so useful and as much fun to use :) Awesome job 👏

**Comment by medvednikov** [comment]
Thank you @floooh for this wonderful, clean, and powerful library.

**Comment by floooh** [comment]
Thanks for the kind words y'all and Happy New Year :)
