### ISSUE TITLE
sokol_gfx: MRT pixel_formats ?

### ISSUE THREAD

**Issue by septag** [floooh/sokol#450]
I have noticed that we can't create multiple render target passes with different pixel_formats, sokol validates that every RT must have the same pixel_format.

however, this should be valid in d3d11/GL4/Metal APIs. in fact, this is very much necessary for GBuffer creation. (ARGB for albedo, R16G16F for normals, etc..)

Is there a reason that this check is done in `make_pass` ?

**Comment by floooh** [comment]
See here:

https://github.com/floooh/sokol/issues/402#issuecomment-706687941

Definitely something that should be fixed, it will also need an extension of the sg_pipeline_desc struct though.

There may be restrictions in backend-APIs what pixel format combinations are allowed though, so before relaxing the requirement we should have another careful look at the 3D API docs and maybe allow backend-specific exceptions via the sg_features struct.

**Comment by septag** [comment]
oh. alright!
The limitation is probably from ES 2.0. I'll check it out and perhaps submit a PR

**Comment by 0x1100** [comment]
OpenGL ES 2.0 and WebGL1 can only have a single color attachment.
See the "mrt" (multi-rendertargets) sample.

**Comment by floooh** [comment]
> OpenGL ES 2.0 and WebGL1 can only have a single color attachment.

True, but general MRT support is already covered by the sg_features.multiple_render_targets field:

https://github.com/floooh/sokol/blob/5894182dddc2e0fd6531e5a2deb5d9cf7662ea2a/sokol_gfx.h#L808

The question is whether we'll need additional feature flags for pixel format restrictions.

**Comment by septag** [comment]
MRT can be enabled on certain ES2 hardware with EXT_draw_buffers extension. but the limitation of same pixel_format for all RTs would always be there for ES2

**Comment by floooh** [comment]
This is now implemented.
