### ISSUE TITLE
[sokol_app] Suggestion: add a pthread call to Linux init so there's an error instead of "weird things"

### ISSUE THREAD

**Issue by iboB** [floooh/sokol#455]
I just experienced the "weird things" like the ones in #376 because I had forgotten to add `-pthread`. I lost about half an hour until I finally figured it out. More precisely with CMake I had added `${CMAKE_THREAD_LIBS_INIT}` but I had forgotten to call `find_package(Threads)`, which is sort of common.

To prevent this from happening, why not add a simple "noop" pthread call like `pthread_yield` in the Linux initialization?

Thus users which forget about `pthread` one way or the other would at least get some kind of compilation or linker error, instead of experiencing #376 and would find the problem much faster.

**Comment by floooh** [comment]
There's a error when compiled as C++:

```
/usr/include/pthread.h:470:12: error: conflicting declaration of ‘int pthread_yield()’ with ‘C’ linkage
 extern int pthread_yield (void) __THROW;
            ^~~~~~~~~~~~~
```

I'll include pthread.h instead and removed the manual declaration.

**Comment by iboB** [comment]
Oh you've written here too. I added some comments to the PR
