### ISSUE TITLE
What is the Handiness of sokol_gl? 

### ISSUE THREAD

**Issue by RicoP** [floooh/sokol#465]
I was wondering when I am using sokol_gl what is the Handiness of my coordinate system? I am using SOKOL_GLCORE33 right now as my rendering backend so I assume I am using the right handed matrix winding of opengl. 

So when I switch to DirectX do I have to change the winding of my matrices, or does sokol_gl abstracts this in any way? 

I couldn't find this to be documented anywhere.

**Comment by floooh** [comment]
Matrix-handedness and face-winding in sokol-gl should behave the same as in GL 1.x, and you can use the same matrix layout for all backends.

The underlying sokol_gfx.h doesn't care about the coordinate system handedness, it just passes matrices through to the shader without changing their memory layout.

The default for face-winding is different between sokol-gfx (clockwise) and sokol-gl (counter-clockwise), however you can tell sokol-gl to use counter-clockwise face-winding in the setup call.

For testing, I wrote this GL sample:

https://github.com/floooh/sokol-samples/blob/master/glfw/sgl-test-glfw.c

...which produces the same output as this sokol-gl sample:

https://github.com/floooh/sokol-samples/blob/master/sapp/sgl-sapp.c
