### ISSUE TITLE
How to get *device-width* and *device-height*?

### ISSUE THREAD

**Issue by changrui** [floooh/sokol#469]
I want to get device or screen reslations, how to do it with sokol? thanks a lot.

**Comment by floooh** [comment]
You can only get the current framebuffer width/height after sokol_app.h has been initialized, querying the display dimensions before sokol_app.h is started isn't possible through sokol_app.h you'd need to do this through platform-specific APIs.

Also sokol_app.h doesn't guarantee that the framebuffer will be in the resolution that has been requested. Instead the width and height in sapp_desc are only hints which sokol_app.h might ignore (those values will be ignored when running in HTML5, iOS or generally when requesting fullscreen).

**Comment by changrui** [comment]
Thanks. I want to write full-screen program to run under various platform.

**Comment by floooh** [comment]
You can get this by simply setting the sapp_desc.fullscreen flag to true, on desktop platforms this will create a borderless window which spans the entire screen.

It's important to note that sokol_app.h does *not* support switching display modes to a different resolution though.

**Comment by changrui** [comment]
OK, thank you very much.
