### ISSUE TITLE
Immediate mode rendering?

### ISSUE THREAD

**Issue by ib00** [floooh/sokol#472]
Has anybody written a simple library or a set of functions (on top of sokol)
that lets you draw stuff in immediate mode. Example:

PushDrawState();
BeginLineLoop();
Vertex(....);
Vertex(....);
Vertex(....);
EndLineLoop();
PopDrawState();

**Comment by floooh** [comment]
Yeah, sokol_gl.h is like this:

https://github.com/floooh/sokol/blob/master/util/sokol_gl.h

It doesn't have line loops specifically, but line lists and strips.

Check out those samples:

https://floooh.github.io/sokol-html5/sgl-sapp.html

https://floooh.github.io/sokol-html5/sgl-lines-sapp.html
