### ISSUE TITLE
sokol_app.h currently doesn't compile on macOS 10.12

### ISSUE THREAD

**Issue by floooh** [floooh/sokol#479]
Not super high priority, but apparently the function NSPasteboardTypeFileURL wasn't available yet in macOS 10.12.

Since this is the only problematic function it might make sense to find a workaround.

See: https://twitter.com/tumult/status/1361205135376965636

**Comment by randrew** [comment]
It's a constant, not a function :)

Use 1: https://github.com/floooh/sokol/blob/8dd4e4a0ea07cde21308df43d66dedbf388be0dc/sokol_app.h#L3159
Uses 2 and 3: https://github.com/floooh/sokol/blob/8dd4e4a0ea07cde21308df43d66dedbf388be0dc/sokol_app.h#L3174 https://github.com/floooh/sokol/blob/8dd4e4a0ea07cde21308df43d66dedbf388be0dc/sokol_app.h#L3179

I haven't written Cocoa in a long time, but I'm pretty sure there is an equivalent way to do this on older macOS/OS X versions. I'm guessing it will probably marked deprecated for newer macOS versions.

**Comment by floooh** [comment]
Closing this because https://github.com/floooh/sokol/pull/482 has been merged.
