### ISSUE TITLE
OSX + GL framerate after API changes

### ISSUE THREAD

**Issue by bmcorser** [floooh/sokol#486]
At some point between the `pre-feb2021-api-changes` tag and current `master` branch, the framerate of the `cube-sapp` example (when compiled with `SOKOL_GLCORE33` backend on OSX) seems to have become rather unstable.

Video showing comparison

[link](https://user-images.githubusercontent.com/1449387/109058652-2a07c600-76db-11eb-894a-45567d8d84ff.mov)

I've made a repo that should make it easy for others to reproduce at https://steady.supply/git/sokol-framerate/

I'll try and bisect by stepping through commits (I notice that the commit directly after `pre-feb2021-api-changes` doesn't have this behaviour) to see if I can find where the breakage is.

**Comment by bmcorser** [comment]
The commit that introduces the framerate instability (on my machine at least!) is 9ea9c481aab3aeac4e43906d048fdcf14da12d73. Building against 9ea9c481aab3aeac4e43906d048fdcf14da12d73's parent, 098b894b4c291ba81daa1909b761b51141025e77, I don't see the issue.

I've added a target `commit-%` to test various commits to https://steady.supply/git/sokol-framerate/ and the following reproduces the issue for me.
```
make commit-098b894b4c291ba81daa1909b761b51141025e77  # all good
make commit-9ea9c481aab3aeac4e43906d048fdcf14da12d73  # stuttering
```
Probably worth mentioning I am on macOS 10.15.7 (19H2) and the commit message for 9ea9c481aab3aeac4e43906d048fdcf14da12d73's parent (098b894b4c291ba81daa1909b761b51141025e77) mentions 10.12 compatibility issues.

For now, I can just checkout `master` and revert 9ea9c481aab3aeac4e43906d048fdcf14da12d73 to get the framerate back to how it was 😅

**Comment by bmcorser** [comment]
For completeness, I've added a target `cube-sapp-metal` to https://steady.supply/git/sokol-framerate/ which shows that the issue isn't present when using the Metal backend.

@randrew any chance you could test this against macOS 10.12?

**Comment by randrew** [comment]
I actually don't have the shader cross-compiler toolchain working on my 10.12 machine, so I can't easily test it. (And I can't run  build scripts from the internet that automate things on that machine.)

@bmcorser Does the `sapp-sgl` sample have the same framerate issues on your 10.15.17 machine? I can run that one without needing the shader compiler stuff. It's fine on 10.12 in both Metal and GLCORE33.

**Comment by bmcorser** [comment]
:wave: thanks for getting back :)

> Does the `sapp-sgl` sample have the same framerate issues on your 10.15.17 machine?

Yep :( added a target to https://steady.supply/git/sokol-framerate/ to show how I built it, video below

[link](https://user-images.githubusercontent.com/1449387/109073490-5aa52b00-76ee-11eb-8d90-85e5ba84a5ef.mov)

If I comment out the call to `_sapp_macos_poll_input_events`
``` patch
diff --git a/sokol_app.h b/sokol_app.h
index a30fc9b..3fd43e5 100644
--- a/sokol_app.h
+++ b/sokol_app.h
@@ -3305,7 +3305,7 @@ _SOKOL_PRIVATE void _sapp_macos_poll_input_events() {
 - (void)drawRect:(NSRect)rect {
     _SOKOL_UNUSED(rect);
     /* Catch any last-moment input events */
-    _sapp_macos_poll_input_events();
+    // _sapp_macos_poll_input_events();
     _sapp_macos_frame();
     #if !defined(SOKOL_METAL)
     [[_sapp.macos.view openGLContext] flushBuffer];
```
then the framerate is stable, but I assume that means macOS 10.12 users lose the benefits of #483 😕

**Comment by randrew** [comment]
I suspected that might be what was causing it. However, `_sapp_macos_poll_input_events()` is not required for 10.12 users to see any benefit. The polling there is only to catch some small percentage of input events that don't get dispatched in time before a frame gets rendered. It will still be OK even without that.

But this raises an interesting question. What in the body of `_sapp_macos_poll_input_events()` is causing the problem?

First thing to try. Change this line:
```
            NSEvent* event = [NSApp nextEventMatchingMask:mask untilDate:nil inMode:NSDefaultRunLoopMode dequeue:YES];
```
to this:
```
            NSEvent* event = [NSApp nextEventMatchingMask:0 untilDate:nil inMode:NSDefaultRunLoopMode dequeue:YES];
```

and see if anything changes.

Another thing to try: log the event type to see what it is. (Make sure you first undo the change above, if you tried it.)

```diff
            if (event == nil) {
                break;
            }
+           printf("event type: %d\n", [event type]);
            [NSApp sendEvent:event];
```
This will print a number to stdout. Do you see any events that are being delivered very rapidly? You can correlate the number printed to the actual event type on this page: https://developer.apple.com/documentation/appkit/nseventtype?language=objc or by looking in the headers.

**Comment by bmcorser** [comment]
Using `nextEventMatchingMask:0` doesn't seem to change anything.

If I print events from `_sapp_macos_poll_input_events` function, I don't see anything being logged unless I move the mouse, in which case I see lots of `5` being printed (aka [`NSEventTypeMouseMoved `](https://developer.apple.com/documentation/appkit/nseventtype/nseventtypemousemoved?language=objc)). I guess that's the intended behaviour?

**Comment by randrew** [comment]
Can you try changing `untilDate:nil` to `untilDate:[NSDate distantPast]` ? (It shouldn't change anything, but maybe the docs are wrong.)

**Comment by meshula** [comment]
nextEventMatchingMask has a behavior of coalescing events. If you google nextEventMatchingMask and coalesce, you'll find reports of stuttering UI behaviors around drags, and the descriptions are very similar to what your videos show.

**Comment by randrew** [comment]
That must be an undocumented change, because the `untilDate:` parameter is specifically supposed to restrict how long it would block or coalesce for. If that's the case in OS versions like 10.15.7, the `_sapp_macos_poll_input_events()` should be completely removed from Sokol.

**Comment by meshula** [comment]
nextEventMatchingMask dequeues events from a queue. https://developer.apple.com/documentation/appkit/nswindow/1419721-nexteventmatchingmask?language=objc 

As best I recall from my years at Apple, it's an NSNotificationQueue, and the behavior is documented here: https://developer.apple.com/documentation/foundation/nsnotificationqueue?language=objc 

Anyway, I'm not insisting I'm right, it's been a while, but my Spidey Sense is tingling on this one and thought it might help resolve this issue.

**Comment by randrew** [comment]
Can you check and see how long the call to `_sapp_macos_poll_input_events()` is blocking on your machine? If it's not very long, then it's probably `nextEventMatchingMask:` causing some kind of unintended change to the event queue. (This doesn't seem to happen on 10.12.) If that's the case, then maybe it's affecting the NSTimer that's used by the GL mode.

**Comment by floooh** [comment]
Thanks for all the input :) I'll see if I can reproduce the issue on my machine (mid-2014 13" MBP with latest Big Sur Beta). There's already so many macOS+OpenGL specific workarounds in the code that one more doesn't hurt I guess ;) (for instance not calling the polling function at all in the GL code path)

**Comment by floooh** [comment]
Yep, can reproduce, looks like I only tested the Metal code path, sorry about that.

I'll tinker around with this a bit in the evening.

As a quick temporary workaround I guess it's best to remove the ```_sapp_macos_poll_input_events()``` call from the ```- (void)drawRect:(NSRect)rect``` function.

**Comment by floooh** [comment]
Using ```inMode:NSEventTrackingRunLoopMode``` instad ```inMode:NSDefaultRunLoopMode``` seems to fix the stuttering and close-button problem. 

Although I don't know yet why ;)

**Comment by randrew** [comment]
Could someone try cherry-picking this commit and seeing if it fixes the problem on OpenGL on 10.15 (or later)?

https://github.com/randrew/sokol/commit/916cb3c73b5d12b552394bfd3b8b2a442e2dbd2d

**Comment by floooh** [comment]
I'll give it a try.

**Comment by floooh** [comment]
```inMode:NSEventTrackingRunLoopMode``` seems to be for "tracking events modally", but I can't see any downsides so far here, neither on GL nor Metal:

https://developer.apple.com/documentation/appkit/nseventtrackingrunloopmode

**Comment by randrew** [comment]
`inMode:NSEventTrackingRunLoopMode` is probably a better choice, then. The commit I linked to above, https://github.com/randrew/sokol/commit/916cb3c73b5d12b552394bfd3b8b2a442e2dbd2d, is probably also worth testing in conjunction. (It may improve GL timing even more.)

(Given that the extra polling I added is now causing problems, I'm not even sure if that part of the commit is worth it anymore. It only seems to catch about 5% of mouse events, or something like that. At least on 10.12.)

**Comment by floooh** [comment]
@randrew the CVDisplayLink change fixes the stuttering, and has a nice side effect that rendering also works while resizing when the mouse stops.

But I'm seeing occasional second-long pauses during resizing, window movement or when closing via close-button where the mouse appears to get stuck. I'm not able to consitently reproduce this though...

**Comment by floooh** [comment]
I think for now I'll simply commit the ```inMode:NSEventTrackingRunLoopMode``` fix, to see how this behaves. Adding CVDisplayLink to the GL backend might be an option for later, but I'm concerned about those strange occasional freezes.

**Comment by floooh** [comment]
Ok, could you guys do an update and check if it compiled and works in 10.12 and otherwise fixes the stuttering? (it does here on my machine):

**Comment by randrew** [comment]
> I think for now I'll simply commit the inMode:NSEventTrackingRunLoopMode fix, to see how this behaves

Sounds good :)

> Adding CVDisplayLink to the GL backend might be an option for later, but I'm concerned about those strange occasional freezes

That does seem odd. Doesn't happen in 10.12. Do the freezes happen even if you completely remove the polling?

**Comment by floooh** [comment]
> Do the freezes happen even if you completely remove the polling?

It's hard to reproduce in the first place, and requires wild resizing and movement. I managed now (with CVDisplayLink and polling code) to get the application into a state where continuous window resizing didn't work at all, the window was just "frozen" as long as the mouse moves, and when releasing the mouse button, the window snaps to the new size. Another side effect during this state is that the mouse cursor doesn't properly update, e.g. when the mouse image remaining in "resizing mode" even when the resizing has finished.

I haven't managed to reproduce with the CVDisplayLink patch applied but polling removed.

But next I'll try the same stress testing without the CVDisplayLink. Maybe it's a general problem with the polling. If I can reproduce it without CVDisplayLink but polling code, I guess it's best to remove the polling.

**Comment by randrew** [comment]
Sounds good. If ends up being the cause of any more problems, I'm not sure if it's worth keeping the polling.

**Comment by floooh** [comment]
So far I couldn't reproduce the freezing with the "no CVDisplayLink" version, but I'll keep an eye on it.

**Comment by randrew** [comment]
It's possible the CVDisplayLink high-priority thread is swamping the main thread with events, or something like that. One thing that could be tested with the CVDisplayLink version: create a test app that draws too much stuff and can't keep a 60fps cadence, and see if it freezes up.

**Comment by meshula** [comment]
inMode:NSEventTrackingRunLoopMode: "modally" means that the app is in a "mode" - handling events by itself. inMode:NSDefaultRunLoopMode - trying to play nicely with the whole system to allow system wide gestures and the like.

The documentation is hidden way down here: https://developer.apple.com/documentation/corefoundation/cfrunloop?language=occ

**Comment by meshula** [comment]
@randrew Your CVDisplayLink code looks good, definitely preferable to an NSTimer. It shouldn't flood the main thread, as the selector called on the main thread only sets the needsdisplay flag, which is a lightweight operation.

**Comment by floooh** [comment]
Thanks for your feedback @meshula, it's much appreciated :)

**Comment by randrew** [comment]
> inMode:NSEventTrackingRunLoopMode: "modally" means that the app is in a "mode" - handling events by itself. inMode:NSDefaultRunLoopMode - trying to play nicely with the whole system to allow system wide gestures and the like. The documentation is hidden way down here: https://developer.apple.com/documentation/corefoundation/cfrunloop?language=occ

Ah, thank you! As soon as I saw there was a modal option when @floooh mentioned it, I figured that might be the correct choice. I didn't know it existed.

> @randrew Your CVDisplayLink code looks good, definitely preferable to an NSTimer. It shouldn't flood the main thread, as the selector called on the main thread only sets the needsdisplay flag, which is a lightweight operation.

That's what I guessed, but I was worried there could be something going on that I didn't understand :)

**Comment by randrew** [comment]
@floooh Sorry, there's a stray empty line in that commit 🤦 : https://github.com/randrew/sokol/commit/916cb3c73b5d12b552394bfd3b8b2a442e2dbd2d#diff-42747840ac0dd5aaeaa9368919646cc57e72a0bb54c03ad85c7eac18956ea584R3258 Assuming you end up taking the change, would you like me to remake the commit, or will you handle it?

**Comment by bmcorser** [comment]
Can confirm `cube-sapp` compiled against  feab36e with GL backend on my 10.15 machine does not stutter :+1:

Of course, many thanks to @floooh !

**Comment by floooh** [comment]
@randrew 

> would you like me to remake the commit, or will you handle it?

Best would be a small PR from you with the display link code, so that the change at least doesn't get lost. I'd like to figure out what's with the strange freezing effects before merging though.

**Comment by randrew** [comment]
Done :)
