### ISSUE TITLE
Any plans to have a stable API?

### ISSUE THREAD

**Issue by medvednikov** [floooh/sokol#494]
Hello,

In your recent blog post you wrote

> I try to keep such breaking updates to a minimum (at most two or three a year)

Does that mean that Sokol will always be changing, and all code bases using it will have to constantly update all code using Sokol?

That'd be unfortunate, since having a stable API is very important for adoption.

Thanks for the great lib!

**Comment by floooh** [comment]
Yeah, the sokol public APIs will keep changing, but the libraries won't change into something completely different. The next area where sokol_gfx.h will need breaking API changes is the resource updating functions (the update and append functions). IMHO for open source header-only libraries which are usually dropped directly into a project (and then don't need to be updated), a stable API isn't as important as (for instance) for a closed-source library that's only available via DLLs.

At one point it might make sense to introduce a proper versioning scheme to better keep track of breaking- and non-breaking changes, and maybe even to backport bugfixes into older versions, but that's a bit too much maintenance overhead right now.

**Comment by medvednikov** [comment]
> IMHO for open source header-only libraries which are usually dropped directly into a project (and then don't need to be updated), a stable API isn't as important

Not updating is not really an option, because of all the great new features, bug fixes, and performance improvements.

Unstable API is one of the main reasons GTK is hated so much as opposed to Win32 API which has been stable since the 90s.

Our team member had to spend an entire day to update because of the breaking changes.

I really hope you'll reconsider and think about backwards compatibility. This would make Sokol perfect and help with adoption.

Thanks for your work.
