### ISSUE TITLE
Number of extensions wrongly reported as zero on ios GLES3

### ISSUE THREAD

**Issue by SoylentGraham** [floooh/sokol#502]
2020 Ipad pro, ios 14.something

` glGetIntegerv(GL_NUM_EXTENSIONS, &num_ext);`
gives no `glGetError()`, but `num_ext` is zero, (so extensions aren't initialiesd)

if I do `print (char*)glGetString(7939)` (`GL_EXTENSIONS = 7939`) in lldb, then it prints out 
```
(char *) $2 = 0x000000010d067496 "GL_OES_standard_derivatives GL_KHR_texture_compression_astc_ldr GL_EXT_color_buffer_half_float GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_pvrtc_sRGB GL_EXT_read_format_bgra GL_EXT_separate_shader_objects GL_EXT_shader_framebuffer_fetch GL_EXT_shader_texture_lod GL_EXT_shadow_samplers GL_EXT_texture_filter_anisotropic GL_APPLE_clip_distance GL_APPLE_color_buffer_packed_float GL_APPLE_copy_texture_levels GL_APPLE_rgb_422 GL_APPLE_texture_format_BGRA8888 GL_IMG_read_format GL_IMG_texture_compression_pvrtc "
```
Now, I can't remember if this is supposed to return null on ES 3.1...(as it's deprecated) but maybe it also suggests I haven't setup my `GLKView` properly (maybe I need to be explicit with level, as I do on osx's NSOpenglView)
Now, this might be a user(me) error... but maybe sokol should be falling back? (or detect this as the wrong ES version?)

I'm also trying to remember if I actually have rendered to a float before on native ios (I know it's missing from safari), but I thought I had... (maybe my old code fellback to half_float automatically)

**Comment by floooh** [comment]
Thanks for the bug report! I'll try to investigate tomorrow with sokol_app.h (on my iPad Mini4, I hope that's good enough). It will almost definitely work with the Metal backend, but the GLES3 on iOS might indeed be a bit "undertested".

Here is how sokol_app.h initializes GLES on iOS btw (_sapp_ios_view is a subclass of GLKView):

https://github.com/floooh/sokol/blob/1d747aaf56d73f6b27411bcdc8c270f9ba5ed83e/sokol_app.h#L3298-L3327

Unless GLES2 is forced, it first tries to create a GLES3 context, and if this fails falls back to GLES2.

**Comment by SoylentGraham** [comment]
Cool, I'm using the default GLKView constructor (via swift! :), I'll do some specific initialisation like I do on mac;
https://github.com/NewChromantics/PopEngine/blob/master/src/SoyOpenglViewOsx.mm#L51

and see if my defaults aren't GLES3.

And then I may implement the glGetStrings() fallback, even if it's supposed to be deprecated, just to get stuff working :)

**Comment by SoylentGraham** [comment]
Oh scrub that, I'm explicitly making ES3 context :)
https://github.com/NewChromantics/PopEngine/blob/master/src/SoySokol_Ios_Gles.mm#L51
```
(lldb) print [mOpenglContext API]
(EAGLRenderingAPI) $0 = kEAGLRenderingAPIOpenGLES3
```
I guess this is 3.0 not 3.1, hence the `GL_EXTENSIONS` behaviour.

I'll implement something to read the GL_EXTENSIONS string as a fallback :)

**Comment by SoylentGraham** [comment]
Update #1:
I copy+pasta the strings handling from `_sg_gl_init_caps_gles2()`, which works

Update #2:
`glGetIntegerv(GL_NUM_EXTENSIONS, &num_ext);` now returns the number of extensions...
I can't explain why (I took out my other changes since having this problem)

**Comment by floooh** [comment]
Ok, I've tested on my iPad mini 4 with iOS 14.4, and the native version of this sample: 

https://floooh.github.io/sokol-html5/pixelformats-sapp.html

This is initialization the GLES3 code path in sokol_app.h and sokol_gfx.h, the GL extension init code in sokol_gfx.h calling glGetIntegerv(GL_NUM_EXTENSIONS, &num_ext) works, I get 19 extensions back, and after the loop checking the extension, the flags related to float-rendering are as follows:

- has_colorbuffer_float = false
- has_colorbuffer_half_float = true
- has_texture_float_linear = false
- has_float_blend = false

This means that rendering is enabled for the following float pixel formats: R16F, RG16F, RGBA16F (screenshot just shows the RGBA16F format):

![C8362508-7D6A-4E2C-93C2-7EEEC5D14283_1_105_c](https://user-images.githubusercontent.com/1699414/113326297-c5fba180-9319-11eb-8719-b19ebbb27840.jpeg)

I'm not sure why the call to query the number of extensions would return 0, but I notices that sometimes the order of steps on macOS or iOS can make a difference, even if the API looks like the order of function calls doesn't matter. 

I'll just close the issue for now. If you stumble over any other problems, just reopen or create a new ticket :)

**Comment by floooh** [comment]
PS: one unrelated thing I just noticed is that the iOS MTKView (so Metal, not GL) seem to ignore the view's contentScaleFactor property (the backing buffer is always full Retina resolution). I'll see if I can come up with a fix.

**Comment by SoylentGraham** [comment]
Maybe I had something like a lingering glGetError before the call... not that I've ever really seen that stop some gl calls. (I do recall checking the error and it returning 0 though)

**Comment by floooh** [comment]
Hmm ok who knows :)

While I'm at it, I'm doing some more fixes for iOS and Metal, but only in sokol_app.h, I guess that's not relevant for you :)

(GLKView multisampling wasn't supported, I guess that was broken in an older iOS version and works now, and on Metal, the high_dpi selection didn't work anymore because MTKView seems to ignore the UIView's contentScaleFactor now).

**Comment by SoylentGraham** [comment]
Cool, yeah I'm all opengl at the moment.
We're into chat territory now, but this is my current bodge in my fork
`SG_MAX_UB_MEMBERS = 1024,`
I guess the aim is to use multiple uniform buffers,(I'm just writing to one atm) which is fine, but still not exposing the max uniforms... is this a bit of a todo, or a general cross platform limitation(16*4) I'm not aware of?

**Comment by floooh** [comment]
Ouch, hmm... SG_MAX_UB_MEMBERS is a "random" value for the capacity of varous nested arrays in C structs. Setting this to a big value will make your ```sg_shader_desc``` structs awfully big (see the ```sg_shader_uniform_block_desc``` struct).

Can you use arrays? Those count as one uniform block member. But note that there are various "unfixable" alignment issues, but float arrays and vec4 arrays should be save (while vec3 arrays are currently broken, and vec2 arrays might be broken).

For instance the sokol_shdc shader compiler flattens all GL uniforms in a shader stage into a single vec4 array, and that works just fine.

**Comment by floooh** [comment]
PS: you still might run into a "max number of vec4 uniforms" even with a single vec4 array, but I think at least on iOS with GLES3 those are now "big enough" (on old GLES2 iOS devices it was just a bit over 100 vec4's if I remember right).

If you need to put much more uniform data into vertex shaders, the currently best cross-platform option is to use an RGBA32F texture and sample that in the vertex shader (unfortunately that's the only cross-platform option if WebGL1 needs to be supported).

**Comment by SoylentGraham** [comment]
It might be big, but it works ;)

Yeah, I know about alignment of shaders etc, but I typically cram it all together when optimising, after I have things working :) (I only need about 30 atm)

Getting bool's & int's working is also on my todo list.
I'm loading shaders on the fly across all platforms, so maybe the shader compiler won't quite be appropriate, but that's a topic for later. (I already have some hacky "refactoring" in my shaders I need to get rid of)
