### ISSUE TITLE
emscripten + fibers

### ISSUE THREAD

**Issue by voidware** [floooh/sokol#506]
This may not be an issue with sokol, but any help much appreciated;

I'm using emscripten fibers to simulate threads. I have the sokol frame callback swap to fiber then swap back and continue. this works until frame returns, then everything stops. no more frames rendered and no errors. Although the event callback is still happening.

If i hack `sokol_app.h/_app_emsc_run` as follows;

```
   /* start the frame loop */
    //emscripten_request_animation_frame_loop(_sapp_emsc_frame, 0);

    emscripten_set_main_loop(_sapp_emsc_frame_void, 0, true);
```
where

```
_SOKOL_PRIVATE void _sapp_emsc_frame_void()
{
    // XX HACK!
    _sapp_emsc_frame(0, 0);
}
```

it works!!

Is there some reasons the main loop via animation frame does not work with fibers but the standard main loop does? Or perhaps it could be something to do with frame timing as calculated by the caller to animation frame loop.

My hacks seem to work fine, but i'd rather like to know what's really going on and not have to hack `sokol`.

thanks for any help.

**Comment by floooh** [comment]
Hmm, no idea TBH. I haven't dabbled yet with Asyncify stuff (which emscripten fibers are based on). The documentation for ```emscripten_set_main_loop()``` reads like there's quite a bit of special handling for threads under the hood (and maybe this extends to asyncify):

https://emscripten.org/docs/api_reference/emscripten.h.html#c.emscripten_set_main_loop

...while ```emscripten_request_animation_frame_loop()``` is most likely just a very simple wrapper for JS ```window.requestAnimationFrame()```.

Maybe you could ask on the emscripten discussion group what the under-the-hood differences between the two functions are (e.g. whether the ```emscripten_request_animation_frame_loop()``` function is incompatible with asyncify.

For sokol_app.h we could add a boolean flag to ```sapp_desc``` (e.g. ```emsc_use_main_loop``` or similar), to select between the two approaches. But I agree, it would be better to first investigate what's actually going on under the hood ;)
