### ISSUE TITLE
project url change from github.com to github.io

### ISSUE THREAD

**Issue by JuanPotato** [floooh/sokol#514]
On the main github page, the project url is https://floooh.github.com/sokol-html5 but is now broken and be changed to https://floooh.github.io/sokol-html5

**Comment by floooh** [comment]
Argh, I knew I've overlooked some links. Thanks!

**Comment by floooh** [comment]
Ok, fixed. Not surprising that I missed this, because I only searched in the actual git projects for outdated links :)
