### ISSUE TITLE
Add a note for bindgen about clang exe in PATH

### ISSUE THREAD

**Issue by Srekel** [floooh/sokol#523]
Stumbled briefly on this (python complains it can't find the file but not which file.. :) )

Would help if the bindgen readme noted that clang is needed on the path.

**Comment by floooh** [comment]
I'll try to remember when I work next on the bindgen stuff. Currently it's still quite WIP.

**Comment by floooh** [comment]
Fixed in https://github.com/floooh/sokol/commit/be081ef0487017d85e03cd8f526dace502551d9e (I totally messed up the ticket number in the commit message though)
