### ISSUE TITLE
sokol_app: MacOSX (OpenGL or Metal) sapp_desc.fullscreen doesn't work

### ISSUE THREAD

**Issue by tmikov** [floooh/sokol#524]
Hi,
When I set `sapp_desc.fullscreen` to `true`, I get a window that is resized to cover the whole screen, but it still has a visible title bar, and the MacOS menu is also visible. When I click the "full screen" button on the window, it does go into "real fullscreen".

I found that if I call sapp_toggle_fullscreen() from the init callback, it works as expected. So, there is an easy workaround, but I am reporting this in case others encounter it.

**Comment by floooh** [comment]
Hmm strange, I cannot reproduce this here, the title- and menubar only slide into view when bumping the mouse against the top border.

I'm testing with the cube-sapp sample using the ```sapp-osx-xcode-debug``` build config, and setting ```.fullscreen = true;``` in sokol_main()).

What macOS and Xcode version are you using? I'm on the latest macOS 11.5 Beta (20G5023d) and Xcode 12.5.

**Comment by tmikov** [comment]
I tried building cube-sapp (with `.fullscreen = false`) and got a very surprising result. When I build it with fips (config sapp-metal-osx-make-debug), I get the correct behavior. If I build it manually as described in the readme (which is awesome, BTW), I get my "bad" result. 

I am attaching a screenshot of the top left corner of the screen to get an idea of what it looks like.
<img width="150" alt="cube-sapp" src="https://user-images.githubusercontent.com/7785196/119415889-5960ab80-bca7-11eb-957f-51337da1e3d1.png">

I will keep digging some more to see find what the difference is.

I am doing this on Catalina with XCode 12.2.  I can believe that Catalina vs Big Sur makes a difference, but given the result above, I think it is unlikely.

**Comment by floooh** [comment]
That's surprising indeed! One difference that comes to mind is that the sokol-samples are built as app bundles, and also have an Info.plist file (which is generated in cmake here: https://github.com/floooh/fips/blob/master/cmake/fips_osx.cmake#L90-L134). I'm not seeing any capability in the info.plist file which seems to related to fullscreen mode though.

Looking forward to what you find out :)

**Comment by tmikov** [comment]
This is definitely it! (Now, don't laugh at this, while I have done some Windows and X11 GUIs, I have deliberately avoided learning about MacOSX GUI development, I just use it as a more comfortable Unix... 😄)

Here is how I was able to "fix" it:
```bash
./cube-sapp # Fullscreen does not work
# OK, fix it.
mkdir -p Contents/MacOS
./cube-sapp # Fullscreen is working now!!!
```

I don't know what the heck is going on! Notice that there is no `Info.plist` and I didn't even copy the binary to `Contents/MacOS/`, I just created an empty subdirectory...

Whatever this is, clearly it doesn't seem like a bug in sokol-app, so closing.

**Comment by floooh** [comment]
Well this behaviour is new to me as well, so ;)
