### ISSUE TITLE
Question. Can I use sokol and native directx 9?

### ISSUE THREAD

**Issue by caiiiycuk** [floooh/sokol#529]
Hi. Great Russian game [Perimeter](https://github.com/KranX/Perimeter) is now open source. It's written on C++ and DirectX9. I really want to port it to Linux, and then to the Web. However, the game is too big and I want to do it step by step.

As a first step I want to rewrite window management, sound system, mouse/keyboard using sokol, and I don't want touch render because it's too complex for me. Do you think it's possible to use original DirectX 9 code with sokol?

To be clear, after the first step I want to have only one Windows dependency - DirectX 9. So, I will clearly understand that sokol integration and game is working correctly. Then on the second step I want to start to rewrite render from DirectX 9  to sokol gfx.

Do you think it's doable?

**Comment by floooh** [comment]
Hi, unfortunately no, both sokol_app.h (for the swapchain) and sokol_gfx.h are tied to D3D11. Mixing D3D9 and D3D11 code in the same application most likely won't work either. Maybe SDL2 is a better option? As far as I'm aware this also still supports D3D9.

**Comment by caiiiycuk** [comment]
Ahh clear. Thank you for advice. However my host is Linux, so best variant for me is to make porting on linux PC. I thinking to use [dxvk](https://github.com/doitsujin/dxvk) layer to translate DirectX9 to Vulkan, in that case can I use sokol and skolo_gfx and dxvk? Do you think it's crazy idea?

**Comment by floooh** [comment]
> in that case can I use sokol and skolo_gfx and dxvk

sokol_gfx.h doesn't have a Vulkan backend, but if it had that might have worked.

**Comment by caiiiycuk** [comment]
Thanks!, If I try I will keep you posted.
