### ISSUE TITLE
fetch broken?

### ISSUE THREAD

**Issue by voidware** [floooh/sokol#536]
I updated from 01April/21 to 21/6/21 and none of my fetches work anymore. `sokol_fetch.h` has not changed. Can you think of any reason why this is. Otherwise i'll have to debug it. reverting back fixed it. So something has changed.
thanks.

**Comment by voidware** [comment]
just for info, what im doing;
```
#define CHUNK_SIZE 1024*256
#define BUFFER_SIZE 1024*512

struct Fetcher
{
    typedef void fetch_done(const char* name, void* ctx);
    
    char fetchBuffer[BUFFER_SIZE];
    GrowString fetchFile;
    bool loading = false;
    bool ok = true;
    fetch_done* doneFn = 0;
    void* doneCtx = 0;
    
    static void _fetch_cb(const sfetch_response_t* r)
    {
        Fetcher* f = *(Fetcher**)r->user_data;
        f->fetch_cb(r);
    }

    void fetch_cb(const sfetch_response_t* r)
    {
        if (r->fetched)
        {
            int sz = r->fetched_size;
            int off = r->fetched_offset;
            LOG1("fetched ", r->path << " " << sz << " at " << off);
            fetchFile.append((char*)r->buffer_ptr, sz);
        }
        else if (r->failed)
        {
            LOG1("fetch ", r->path << " failed with " << r->error_code);
            ok = false;
            fetchFile.clear();
        }

        if (r->finished)
        {
            LOG1("fetch ", r->path << " finished " << fetchFile.size());
            assert(doneFn);
            loading = false;
            (*doneFn)(r->path, doneCtx);
        }
    }
    
    bool start(const char* path, fetch_done* cb, void* ctx = 0)
    {
        if (loading) return false; // wait until free
        
        sfetch_request_t fr;
        loading = true;
        ok = true;

        doneFn = cb;
        doneCtx = ctx;
        memset(&fr, 0, sizeof(fr));
        fr.path = path;
        fr.callback = _fetch_cb;
        //fr.chunk_size = CHUNK_SIZE;
        fr.buffer_size = BUFFER_SIZE;
        fr.buffer_ptr = (void*)fetchBuffer;

        void* ptr = (void*)this;
        fr.user_data_ptr = (void*)&ptr;
        fr.user_data_size = sizeof(ptr);
        
        LOG1("fetching ", fr.path);
        fetchFile.clear();
        sfetch_send(&fr);
        return true;
    }

    char* yield(int& sz)
    {
        sz = fetchFile.size();
        return fetchFile.donate();
    }

    void poll()
    {
        sfetch_dowork();
    }
    
};
```

**Comment by floooh** [comment]
Thanks for the bug report, I'll have a look. In general sokol_fetch.h still works, because I've been using it in the recent character skinning samples to load the character data, but maybe there's an edge case that changed behaviour.

**Comment by floooh** [comment]
Can you say what the broken behaviour is? Do you get an error, or corrupted data back?

**Comment by floooh** [comment]
Are you using HTTP Range requests? The only somewhat recent change is this (from January), which fixed an overlapping problem (because the range in range requests is inclusive, not exclusive).

**Comment by voidware** [comment]
This could all be my bad code :-)

Setting the `chunk_size` for me didnt work anyway, i think because im using the, somewhat lame, python http server. It probably doesnt suport ranges at all. I _do_ get `get` requests appearing from the server, but that's all.

I just wondered if there was an obvious change made recently. Otherwise i'll start looking into why it doesnt work.

**Comment by floooh** [comment]
Alright, if you find something, please let me know here. Even if it's not a bug in sokol_fetch.h maybe we can fix a few things to make such regressions less likely in the future.
