### ISSUE TITLE
How to draw a texture in it's original size (without any interpolation / transformation)

### ISSUE THREAD

**Issue by geekynils** [floooh/sokol#538]
I don't have any experience with low level computer graphics so it is possible that I miss something obvious, but I could not figure it out on my own, therefore the question: When I draw a a texture I have to map it to a geometric primitive which consists of a vertex and an index buffer. Since vertex coordinates are in normalized device coordinates I cannot just create a rectangle that exactly matches the size of texture. I guess that if I get the vertex coordinates in such a way that no transforms would be applied to the image I could then use

        .min_filter = SG_FILTER_NEAREST,
        .mag_filter = SG_FILTER_NEAREST,

in the sg_image_desc to disable any interpolation. Any help is greatly appreciated!

**Comment by lithiumtoast** [comment]
>Since vertex coordinates are in normalized device coordinates

I think you are missing the matrix transformations piece of the puzzle here. Even though it's not `sokol` directly, the concepts still apply: http://www.opengl-tutorial.org/beginners-tutorials/tutorial-3-matrices/

>I cannot just create a rectangle that exactly matches the size of texture

You could achieve this for 2D by simply having an orthographic projection mapping the screen into cartesian coordinates. Then define your textured quadrilateral vertices with the position as you would expect. If you want to render the whole texture inside that region simply use top-left uv and bottom-right uv appropriate to whether you are using bottom-left or top-left as origin.

**Comment by geekynils** [comment]
Thanks for the hint! I will read the guide and try to write the code.

**Comment by floooh** [comment]
Without matrix operations (if you just want to create a vertex buffer of the right size) you need to figure out the frame buffer pixel size in screen space coordinates.

Screen space goes from -1.0 to +1.0:

```
-1.0,-1.0             +1.0,-1.0
+----------------------+
|                                        |
|                                        |
|                                        |
+----------------------+
-1.0,+1.0             +1.0,+1.0
```

To get the size of a pixel in screen space coords, use the current framebuffer size

```c
float pixel_width = 2.0f / sapp_widthf();
float pixel_heigth = 2.0f / sapp_height();
```

Now if you have a texture that's 256 x 256, the width of the texture in screen space coordinates would be:

```c
float screen_space_width = 256.0f * pixel_width;
float screen_space_heigth = 256.0f * pixel_height;
```

With such screen space coordinates in the vertices you don't need a separate transformation in the vertex shader because the vertices are already in the right coordinate space.

Unfortunately there's no sample code for exactly this problem, the closest samples which deal with texel-to-pixel mapping are the sokol_debugtext.h samples.

**Comment by geekynils** [comment]
Thanks for your quick replay. I went for the easier option first (just calculating the size in normalized device coordinates). Here is the code:

exact_texture_mapping.c :
```
#include "sokol_app.h"
#include "sokol_gfx.h"
#include "sokol_glue.h"

#define STB_IMAGE_IMPLEMENTATION
#include "stb/stb_image.h"

// Generated from texture.glsl using shdc.
#include "texture.glsl.h"

#include <stdio.h>
#include <stdlib.h>

static struct {
    sg_pipeline pip;
    sg_bindings bind;
    sg_pass_action pass_action;
} state;

static void init(void) {
    sg_setup(&(sg_desc){ .context = sapp_sgcontext() });
    
    //MARK: Load the PNG and initialize the texture.
    
    const char* texture_path = "/Users/nils/Develop/sokol-exact-texture/tiger_small.png";
    int pixel_w, pixel_h, c;
    unsigned char *pixels = stbi_load(texture_path, &pixel_w, &pixel_h, &c, 4);
    
    if (!pixels) {
        fprintf(stderr, "Failed to load image from %s!\n", texture_path);
        state.pass_action = (sg_pass_action) {
            .colors[0] = { .action = SG_ACTION_CLEAR, .value = { 1.0f, 0.0f, 0.0f, 1.0f } }
        };
        return;
    }

    state.bind.fs_images[SLOT_tex] = sg_alloc_image();
    sg_image_desc image_desc = {
        .width = pixel_w,
        .height = pixel_h,
        .pixel_format = SG_PIXELFORMAT_RGBA8,
        .min_filter = SG_FILTER_NEAREST,
        .mag_filter = SG_FILTER_NEAREST,
        .data.subimage[0][0] = {
            .ptr = pixels,
            .size = (size_t)(pixel_w * pixel_h * 4),
        }
    };
    
    sg_init_image(state.bind.fs_images[SLOT_tex], &image_desc);
    
    stbi_image_free(pixels);
    
    //MARK: Create a rectangle that exactly matches the PNG's size.
    
    float single_pixel_w = 2.0f / sapp_widthf();
    float single_pixel_h = 2.0f / sapp_heightf();

    float w = pixel_w * single_pixel_w;
    float h = pixel_h * single_pixel_h;
    
    // Bounds of a square on which we put the texture.
    // NOTE x points to the left, y up.
    float bounds[] = { 
        //  x,        y,     z,    u,    v
        -1.0f,      1.0f,     0.0f, 0.0f, 0.0f,
        -1.0f + w,  1.0f,     0.0f, 1.0f, 0.0f,
        -1.0f + w,  1.0f - h, 0.0f, 1.0f, 1.0f,
        -1.0f,      1.0f - h, 0.0f, 0.0f, 1.0f
    };

    state.bind.vertex_buffers[0] = sg_make_buffer(&(sg_buffer_desc){
        .data = SG_RANGE(bounds),
        .label = "bounds"
    });
    
    // We need 2 triangles for a square, this makes 6 indexes.
    uint16_t indices[] = {0, 1, 2, 0, 2, 3};

    state.bind.index_buffer = sg_make_buffer(&(sg_buffer_desc){
        .type = SG_BUFFERTYPE_INDEXBUFFER,
        .data = SG_RANGE(indices),
        .label = "indices"
    });

    // NOTE texture_shader_desc(...) is defined in texture.glsl.h
    const sg_shader_desc *shader_desc = texture_shader_desc(sg_query_backend());

    state.pip = sg_make_pipeline(&(sg_pipeline_desc){
        .shader = sg_make_shader(shader_desc),
        .index_type = SG_INDEXTYPE_UINT16,
        // If the vertex layout doesn't have gaps, there is no need to provide strides and offsets.
        .layout = {
            .attrs = {
                [ATTR_vs_pos].format = SG_VERTEXFORMAT_FLOAT3,
                [ATTR_vs_texcoord0].format = SG_VERTEXFORMAT_FLOAT2
            }
        },
        .label = "pipeline"
    });

    /* a pass action to framebuffer to black */
    state.pass_action = (sg_pass_action) {
        .colors[0] = { .action = SG_ACTION_CLEAR, .value = {0.0f, 0.0f, 0.0f, 1.0f } }
    };
}

static void cleanup(void) {
    sg_shutdown();
}


static void handle_event(const sapp_event* ev) {
    switch (ev->type) {
        case SAPP_EVENTTYPE_MOUSE_DOWN:
            break;
        case SAPP_EVENTTYPE_MOUSE_UP:
            break;
        case SAPP_EVENTTYPE_MOUSE_MOVE:
            break;
        case SAPP_EVENTTYPE_MOUSE_SCROLL:
            break;
        case SAPP_EVENTTYPE_KEY_DOWN:
            break;
        case SAPP_EVENTTYPE_KEY_UP:
            break;
        case SAPP_EVENTTYPE_CHAR:
            break;
        default:
            break;
    }
}

static void frame(void) {
    sg_begin_default_pass(&state.pass_action, sapp_width(), sapp_height());
    sg_apply_pipeline(state.pip);
    sg_apply_bindings(&state.bind);

    // Number of elements is the same as the number of indices
    sg_draw(0, 6, 1); // Args are base_element, # elements, # instances.
    sg_end_pass();
    sg_commit();
}

sapp_desc sokol_main(int argc, char* argv[]) {
    (void)argc; (void)argv;
    return (sapp_desc) {
        .init_cb = init,
        .frame_cb = frame,
        .cleanup_cb = cleanup,
        .event_cb = handle_event,
        .width = 1024,
        .height = 768,
        .high_dpi = false,  // If I set this to true the texture size is halved.
        .window_title = "Exact Texture Mapping",
    };
}
```

texture.glsl
```
@vs vs
in vec4 pos;
in vec2 texcoord0;
out vec2 uv;

void main() {
    gl_Position = pos;
    uv = texcoord0;
}
@end

@fs fs
uniform sampler2D tex;

in vec2 uv;
out vec4 frag_color;

void main() {
    frag_color = texture(tex, uv);
}
@end

@program texture vs fs
```

Here is the result:

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/134199/125944250-9d70cef7-38ab-4566-806d-fdb889275e3c.png">

I moved the original image over the screenshot of the sokol app in an image editor and could not find a difference. What I do not understand though is couldn't floating point rounding lead to slightly different pixel values? I also found that I needed to turn off `high_dpi`  in `sapp_desc`, otherwise it would downscale the texture by a factor of two.

**Comment by floooh** [comment]
> couldn't floating point rounding lead to slightly different pixel values

Yes this can indeed be tricky to get right. But I found that it's better to do the entire math in floating point instead of mixing integer and float computations (see this blurb in the sokol_debugtext.h docs: https://github.com/floooh/sokol/blob/01b2916b071e20eff0e76ca717d7deb18869c553/util/sokol_debugtext.h#L143-L144).

To be "high-dpi agnostic", you need to add sapp_dpi_scale() to the formula, like this:

```
    float single_pixel_w = 2.0f / (sapp_widthf() * sapp_dpi_scale());
    float single_pixel_h = 2.0f / sapp_heightf() * sapp_dpi_scale());
```
