### ISSUE TITLE
Sokol drawing limited to 16384 instructions

### ISSUE THREAD

**Issue by BenStigsen** [floooh/sokol#540]
Recently I've been trying to fill out a window pixel-by-pixel, to create stuff like transformations between images, text and more.
However, after calling `v2f` a couple of times, like trying to fill a `100x150` window, it stops coloring. This is easy to avoid by creating an image, drawing to it, then draw that image with sokol, however, for some use-cases I might want to draw more directly without having to create an image first.

My proposal would be to extend the vertices and command limit, or to force draw once it reaches max capacity.
https://github.com/floooh/sokol/blob/0d955d75cd909d778d15e040fe7b8cbf857e6cc0/util/sokol_gl.h#L2031-L2032

**Comment by alex-rass-88** [comment]
This is default value. Your can override this in sgl_desc_t struct in initialisation

**Comment by floooh** [comment]
Yes, as @alex-rass-88 says, the limits you're seeing are just the default values, and can bump those limits during initialization:

```
sgl_setup(&(sgl_desc_t){
    .max_vertices = ...,
    .max_commands = ...,
    .pipeline_pool_size = ...
});
```

Bumping the vertex count shouldn't have any performance implications, there's just more memory allocated during the ```sgl_setup()``` call.
