### ISSUE TITLE
there is no documentation

### ISSUE THREAD

**Issue by AliChraghi** [floooh/sokol#541]
why there's no documentation? the docs in the source code is messed

**Comment by geekynils** [comment]
Documentation is in the headers, for example the docs for `sokol_gfx` is in [sokol_gfx.h](https://github.com/floooh/sokol/blob/master/sokol_gfx.h). IMHO it is usually pretty clear. However the documentation assumes that you are familiar with the underlying computer graphics concepts, for example you need to know what vertices, textures, vertex and fragment shaders are. If you are not familiar with those concepts have a look at the tutorials at [https://learnopengl.com](https://learnopengl.com).
