### ISSUE TITLE
sokol_gfx_imgui.h typedef problem

### ISSUE THREAD

**Issue by RandyGaul** [floooh/sokol#544]
I noticed you don't have typedefs setup with the type tags, which made it difficult to forward declare one of your struct types. Specifically here:

![image](https://user-images.githubusercontent.com/1919825/127953808-801c5911-85cf-4a7c-bddc-e972ea6f2f66.png)

In an API I'm creating I wanted to forward declare `sg_imgui_t` but couldn't as the type tag is missing. Just wondering, why did you omit them?

**Comment by floooh** [comment]
Just an oversight, I guess the sokol_gfx_imgui.h header was from a time before I was aware of the forward declaration problem. I'll add them right away.

**Comment by floooh** [comment]
Ok fixed.
