### ISSUE TITLE
How to draw 8bit pixel buffer as black/white?

### ISSUE THREAD

**Issue by BenStigsen** [floooh/sokol#548]
Since I only need 1 byte-per-pixel, I decided to go with the `SG_PIXELFORMAT_R8`, but this only draws red. How would I use 1 byte-per-pixel but draw it as black/white?

**Comment by floooh** [comment]
Easiest way is to replicate the red channel into blue and green via swizzle when sampling the R8 texture in the pixel shader, e.g. (note the ```.xxx```):

```glsl
@fs display_fs
uniform sampler2D tex;
in vec2 uv;
out vec4 frag_color;

void main() {
    frag_color = vec4(texture(tex, uv).xxx, 1.0);
}
@end```

**Comment by BenStigsen** [comment]
Hmm, so it still requires 4-bytes per pixel if I want to turn my 1-byte per pixel into white? Is there not a memory saving way to do this, where I can still use my 1 byte buffer?

**Comment by meshula** [comment]
the replication by .xxx is in the gpu's fragment shader, not the cpu. no memory wasted.

**Comment by BenStigsen** [comment]
Ah, nice.
