### ISSUE TITLE
Windows GL Backend high CPU usage

### ISSUE THREAD

**Issue by cshenton** [floooh/sokol#550]
On Windows 10 observed both in my own codebase and the sokol-samples sapp examples.

- 0.3% CPU usage of cube example on D3D11 backend
- 18% CPU usage of cube example on GLCORE33 backend

Using [these build instructions to repro](https://github.com/floooh/sokol-samples#building-manually-on-windows-with-clang). These %ages are from Task Manager so are % of total CPU, not of an indidivual core/hyperthread. So the GL backend is pinning more than a full logical core on my machine.

I encountered this on a month old commit, pulled the most recent commits, the problem still persists. I have a mac available to me so I'm going to test whether the same backend also exhibits this issue on macos.

**Comment by cshenton** [comment]
The same program does not appear to have as high CPU usage on my Macbook Air. It uses roughly 18% of one core (as observed in Activity Monitor, which reports %ages of a core), vs. using 18% of the full 8-core CPU on the windows machine (as observed on Task Manager, which reports %ages of the full CPU), so this does seem to be windows specific.

**Comment by Maeiky** [comment]
Check if V-Sync is enable (by default)

**Comment by floooh** [comment]
Not sure what could be causing this. As far as I'm aware the relevant GL context and swapchain code in sokol_app.h should be roughly the same as GLFW, so it probably makes sense to also test against a GLFW demo. There's also no code running in separate threads in sokol_app.h or sokol_gfx.h, so any additional core load probably comes from the GL driver. The only theory that comes to mind is that the GL implementation busy waits for vsync (which would be pretty dumb though).

Disabling vsync is currently not officially supported in sokol_app.h btw, this is mainly to be consistent with callback/event-based platforms where vsync can't be disabled (like the web for instance).

**Comment by hbiblia** [comment]
If in Windows 11 GL3 consumes much more memory and power than using D3D11 which consumes less memory and less power. This is according to what the windows task manager tells me.

**Comment by EarthenSky** [comment]
I'm also seeing busy waiting on Win 11 with _SOKOL_ANY_GL, but it goes away when switching to D3D11 as a backend

**Comment by floooh** [comment]
Btw, on my Win10 machine the GL backend only has such a high CPU load (25%) only when compiling in debug mode, in release it drops to around 1..2%. I'm not sure what's the culprit, but I can't see any differences in the sokol header code between debug and release mode which would explain this.
