### ISSUE TITLE
2 channel texture (GL_RG) in GLES2... easyish?

### ISSUE THREAD

**Issue by SoylentGraham** [floooh/sokol#552]
I'm stuck using GLES2 on a jetson/linux, but I use 2 channel 8bit images.

`GL_RG` is explicitly define'd out as it's missing from GLES2, but `GL_LUMINANCE_ALPHA` is supported.
I did some quick bodges and it seems to be working, with the obvious problem that the sampler is wrong (`.xy` vs `.xw`)

Is this sort of situation handled similarly with any other formats/backends? (maybe some swizzle info, or should it be a RA format? etc)

I don't think setting the sampler swizzle is supported on ES2 (not tried yet)

Have you tried implementing `GL_LUMINANCE_ALPHA` in sokol and hit a roadblock that I haven't yet? (before I go too far down this rabbit hole)

**Comment by SoylentGraham** [comment]
Oh, this may be moot, I've managed to get GLES3 going...

On a side note using `GL_NUM_EXTENSIONS` might be a reliable way to auto detect GLES2 vs GLES3 contexts

**Comment by floooh** [comment]
You can check the supported pixel formats and their capabilities at runtime with ```sg_query_pixelformat()```. 

Swizzle needs to happen in the pixel shader, sokol_gfx.h doesn't have support for sampler swizzle (haven't checked if this is portable across all backends).

Also, GL_LUMINANCE_ALPHA isn't supported (only GL_LUMINANCE, which is equivalent with GL_RED). For 2-channel textures you really need to switch to GLES3 I'm afraid and use one of the RG formats.

There's also a sample for exploring pixel format capabilities (WASM version is here: https://floooh.github.io/sokol-html5/pixelformats-sapp.html - but this can also be compiled natively).

In sokol_app.h, some GLES backend (iOS and WebGL) support runtime fallback from GLES3 to GLES2, in this case you can use ```sapp_gles2()``` to check whether you ended up with a GLES2 context (if you tried to create a GLES3 context but this isn't supported). Unfortunately the Android backend doesn't have this runtime fallback yet.

Hope this helps :)
