### ISSUE TITLE
Avoid setting MTLTextureDescriptor.resourceOptions

### ISSUE THREAD

**Issue by kssreeram** [floooh/sokol#556]
Apple's [docs](https://developer.apple.com/documentation/metal/mtltexturedescriptor/1515776-resourceoptions?language=objc) on `MTLTextureDescriptor.resourceOptions` say:
> The value of this property aggregates the values of storageMode, cpuCacheMode, and hazardTrackingMode. If you modify this property, the other properties also change, and vice versa.

In `_sg_mtl_init_texdesc_common`, setting `resourceOptions` undoes the write-combined cache-mode setting:
```
    if (img->cmn.usage != SG_USAGE_IMMUTABLE) {
        mtl_desc.cpuCacheMode = MTLCPUCacheModeWriteCombined;
    }
    #if defined(_SG_TARGET_MACOS)
        /* macOS: use managed textures */
        mtl_desc.resourceOptions = MTLResourceStorageModeManaged;
        mtl_desc.storageMode = MTLStorageModeManaged;
    #else
        /* iOS: use CPU/GPU shared memory */
        mtl_desc.resourceOptions = MTLResourceStorageModeShared;
        mtl_desc.storageMode = MTLStorageModeShared;
    #endif
```

To fix this, avoid setting `.resourceOptions`.

Assignments to `MTLTextureDescriptor.resourceOptions` are present in the following procedures, all of which can be removed:
- `_sg_mtl_init_texdesc_common`
- `_sg_mtl_init_texdesc_rt`
- `_sg_mtl_init_texdesc_rt_msaa`

In the latter two procedures, the assignments are harmless but redundant.

**Comment by floooh** [comment]
Wouldn't it make more sense to only set ```resourceOptions``` and remove ```storageMode``` and ```cpuCacheMode```?

**Comment by kssreeram** [comment]
That works too.

**Comment by floooh** [comment]
Ok, this should be cleaned up now. I'm only setting the resourceOptions but not the storageMode and cpuCacheMode separately.

I also changed the uniform buffers from managed to shared on macOS since it matches the point:

```
Changes frequently, is relatively small, and is accessed by both the CPU and the GPU. Choose the MTLStorageModeShared mode.
```
here: https://developer.apple.com/documentation/metal/setting_resource_storage_modes/choosing_a_resource_storage_mode_in_macos?language=objc
