### ISSUE TITLE
problem with deleting fetch's user_data

### ISSUE THREAD

**Issue by alighazi** [floooh/sokol#561]
Hi Andre
I'm trying to send a heap allocated object as user_data to fetch to later use it in the fetch callback. however in fetch callback after I'm done and want to delete the object it crashes. complaints that the object is not heap allocated. is there anything I can do about it?

an example

sending the request
  ```
FetchUserData *udata1 = new FetchUserData();
.
.
.
sfetch_request_t fetch_request = {
      .path = udata1->file_name->data(),
      .callback = fetch_callback,
      .buffer_ptr = fileBuffer_,
      .buffer_size = sizeof(fileBuffer_),
      .user_data_ptr = udata1,
      .user_data_size = sizeof(FetchUserData)};
sfetch_send(&fetch_request);

```

callback function
```
static void fetch_callback(const sfetch_response_t *response)
{
    auto udata = (FetchUserData *)response->user_data;
    if (response->fetched)
    {
        int img_width, img_height, num_channels;
        const int desired_channels = 4;
        stbi_uc *pixels = stbi_load_from_memory(
            (const stbi_uc *)response->buffer_ptr,
            (int)response->fetched_size,
            &img_width, &img_height,
            &num_channels, desired_channels);

        if (pixels)
        {
            /* initialize the sokol-gfx texture */
            sg_image_desc idesc = {
                .width = img_width,
                .height = img_height,
                .pixel_format = SG_PIXELFORMAT_RGBA8,
                .min_filter = SG_FILTER_LINEAR,
                .mag_filter = SG_FILTER_LINEAR};
            idesc.data.subimage[0][0] = {
                .ptr = pixels,
                .size = (size_t)(img_width * img_height * desired_channels),
            };
            sg_init_image(*udata->image_id, &idesc);
            stbi_image_free(pixels);
            delete udata;     //crashes here!    
        }
    }
}
```

**Comment by floooh** [comment]
Ah yes, that's a bit awkward. sokol_fetch.h copies the provided user data blob into a small per-request-buffer:

https://github.com/floooh/sokol/blob/89b1b6b1b844fd968537e633a3ded7662bb63641/sokol_fetch.h#L1097-L1099

Also see the explanation here:

https://github.com/floooh/sokol/blob/89b1b6b1b844fd968537e633a3ded7662bb63641/sokol_fetch.h#L256-L264

...so this works differently than typical user_data pointers.

What you need to do is pass a pointer to the FetchUserData pointer to be copied into the user data block, and later copy this out again:

```cpp
FetchUserData *udata1 = new FetchUserData();
//...
sfetch_request_t fetch_request = {
    .path = udata1->file_name->data(),
    .callback = fetch_callback,
    .buffer_ptr = fileBuffer_,
    .buffer_size = sizeof(fileBuffer_),
    .user_data_ptr = &udata1,
    .user_data_size = sizeof(udata1)};
sfetch_send(&fetch_request);
```
...note how the *address* and *size* of the udata1 pointer is passed to sokol_fetch.h, so 8 bytes (on a 64-bit system) are copied into the user data block.

...and later in the fetch callback extract the original FetchUserData pointer from the request's user data block:

```cpp
FetchUserData* udata = *(FetchUserData**)response->user_data;
//...
delete udata;
```

...this should work.

**Comment by alighazi** [comment]
Thanks alot, shame I didn't read the docs properly :p
