### ISSUE TITLE
ImGUI - Origin (top_left) problem

### ISSUE THREAD

**Issue by sebastien-favier** [floooh/sokol#577]
Hi,

We have successfully implemented/executed win32 executable [Sokol/opengl3.3 into Cpcdos OSx](https://youtu.be/A_I4eTmbWS0?t=50) for our [cokernel project](https://cpcdos.net/). We use our custom opengl32.dll for shader/gpu emulation into CPU.
Cpcdos can execute Win32 exe files with some native NT function.

We want to test ImGUI implementation (every win32 format), but we have strange problems. GUI objects are invisible and the 0,0 origin is on the screen center. [Screenshot here](https://media.discordapp.net/attachments/769652031694307399/903312756181184543/unknown.png?width=890&height=473) and [here](https://media.discordapp.net/attachments/769652031694307399/903326738019409991/unknown.png?width=908&height=473)

DPI has been evaluated to 1.0f

Have you a idea of what can be wrong on our implementation ?

ps: We are using the exact same win32 .exe / opengl32.dll on Windows/CpcDos, which work fine only on Windows platform

Thank a lot
Regards
Sebastien FAVIER

**Comment by sebastien-favier** [comment]
Thank you very much for your answer !

We have sokol_gfx.h + sokol_imgui.h. we directly use your sokol-samples github like ``imgui-sapp.cc`` (without modifications.) compiled for native Win32 for testing your sokol on Cpcdos.

Into ``sokol_imgui.h::sg_apply_viewport()``, i've forced the width and height to 800, 600 ... nothing

But, for `_sg_apply_viewport()` and `_sg_apply_scissor_rect()`, I added in the functions (to force):
``
x = 0;
y = 0;
w = 800;
h = 600;
``
And the GUI objects are displayed ✅ [screenshot here](https://media.discordapp.net/attachments/568049404511256577/905592946437554226/unknown.png?width=888&height=473)
But the origin, again in the center of the screen.

We're trying to find what we missed in our Win32 loader, but we don't know where we went wrong, because there are many 2D and 3D sokol samples that work! But not ImGUI ... I admit that we are perplexed 

Are there any environment variables? a specific variable (may be settled to 0) that can influence this display?

**Comment by floooh** [comment]
> Are there any environment variables? a specific variable (may be settled to 0) that can influence this display?

Not that I know of.

A few additional places to check in the debugger or with logging:

- this code block in simgui_render() where the viewport and scissor rect is reset to the full framebuffer size, check of fb_width and fb_height look correct: https://github.com/floooh/sokol/blob/8fcd271f7d4cb19c77aa9f0bbfe8cb7f319dbffc/util/sokol_imgui.h#L1969-L1973

- and right below where the shader uniforms are set, the ```vs_params.disp_size.x``` and ```vs_params.disp_size.y``` should also be the correct display size.

And finally, you can check with RenderDoc (https://renderdoc.org/) what data is arriving at the vertex shader and whether the vertex shader shader does 'the right thing' (unfortunately shader debugging isn't support on OpenGL, but I think you can look at the input and output vertex data).

**Comment by floooh** [comment]
Oops, I already showed you that sg_apply_viewport() code location, sorry...
