### ISSUE TITLE
Disabling context initialization 

### ISSUE THREAD

**Issue by kariem2k** [floooh/sokol#578]
Hello

I am trying to use sokol_app with bgfx for a webasm project. bgfx has its own context initialization and swap buffer. It is conflicting with sokol_app one. Is there a way to use sokol_app for input and other webasm goodies without 3d context initialization?

Thanks

**Comment by floooh** [comment]
Oops sorry somehow I missed the notification for this issue.

On some backends the window system code is quite closely connected to the 3D context/device setup, I think supporting such a feature across all backends might be a bit non-trivial (for instance on macOS everything is expected to be setup within the didFinishLaunching callback).

**Comment by kariem2k** [comment]
Thanks, flooh, yeah, I think I will keep it for the WebGL development only.
