### ISSUE TITLE
Unable to set Metal backbuffer filter to "linear"

### ISSUE THREAD

**Issue by trojanfoe** [floooh/sokol#580]
I am writing a game with a lo-res virtual screen size of 640 x 360 and am rendering to an offscreen render target which has linear filtering, and all sprites/text are using linear filtering. I am then drawing this render target to the backbuffer using your very own `fsq` shader.

The problem I face is that when this is rendered to the view it looks blurry.

We have discussed this on Twitter and I have changed the hardcoded setting of `kCAFilterNearest` to `kCAFilterLinear` in `sokol_app.h:3118` but this has no effect.  I have also turned off `sapp_desc.hidpi`, also to no effect.

Can you think of a way to do this please?

**Comment by trojanfoe** [comment]
As an aside, Apple's own documentation for setting this in `CALayer` looks wrong:

![image](https://user-images.githubusercontent.com/312617/142268337-da225826-f758-44e7-b602-a37d4c0081cd.png)

Surely the linear filtering is on the right?  Also I hope this is just a documentation issue...

**Comment by floooh** [comment]
Ah ok, there are several things going on :)

First: in that Apple documentation image, linear filtering is on the left (the smooth one), the right one without filtering is usually called "nearest" filtering, or in D3D lingo "point" filtering

In sokol-gfx these would be SG_FILTER_NEAREST for pixelized rendering vs SG_FILTER_LINEAR for smooth rendering.

So if you want to render the offscreen render target with a pixelized effect you would create the render target texture with ```sg_image_desc.mag_filter = SG_FILTER_NEAREST``` (not SG_FILTER_LINEAR!).

That's most likely already enough. The kCAFilter thing in sokol_app.h only affects the upscaling in the macOS window system, not anything you'd do in sokol_gfx.h. kCAFilterNearest actually enforces a pixelized look. Outside of text rendering this is hardly noticeable though (especially with MSAA anti-aliasing enabled).

**Comment by trojanfoe** [comment]
Ah that was a silly mistake.  Thanks for looking into it.
