### ISSUE TITLE
Any python or lua binding lib now?

### ISSUE THREAD

**Issue by zeroxer** [floooh/sokol#582]
I want to use sokol with python or lua script. Have there any binding now?

**Comment by floooh** [comment]
None that I know of!

**Comment by funatsufumiya** [comment]
For information, there is indirect lua binding from framework using sokol.
https://github.com/supernovaengine/supernova

**Comment by floooh** [comment]
And btw, there's also this luajit version now:

https://github.com/floooh/sokol/issues/1127
