### ISSUE TITLE
gl_FragCoord has a flipped y axis when using hlsl

### ISSUE THREAD

**Issue by kcinnu** [floooh/sokol#588]
reproduction: https://github.com/kcinnu/sokol-bug

the bottom-left corner is supposed to be black, but when using the d3d11 backend the top-left corner is black instead.
I think it might be an issue with spirv-cross used by sokol-shdc, but I'm not 100% sure.

**Comment by floooh** [comment]
Hi, yep, SPIRVCross doesn't handle the Y coordinate flipping by default, but check out the ```@glsl_option flip_vert_y``` keyword in sokol-shdc (must be placed inside the vertex shader begin/end block):

https://github.com/floooh/sokol-tools/blob/master/docs/sokol-shdc.md#glsl_options-hlsl_options-msl_options

With this option, SPIRVCross will add a small code snippet after the vertex shader logic which flips the Y coordinate.

This is used in the sokol-samples in those places:

https://github.com/floooh/sokol-samples/blob/53bf17e54376c9b3783e51e11c993fc4bf030df0/sapp/mrt-sapp.glsl#L39-L61

https://github.com/floooh/sokol-samples/blob/53bf17e54376c9b3783e51e11c993fc4bf030df0/sapp/mrt-sapp.glsl#L82-L106

https://github.com/floooh/sokol-samples/blob/53bf17e54376c9b3783e51e11c993fc4bf030df0/sapp/mrt-pixelformats-sapp.glsl#L49-L60

**Comment by kcinnu** [comment]
`@hlsl_options flip_vert_y` works perfectly fine, thanks!
