### ISSUE TITLE
sokol_time: `performance` undefined on NodeJS

### ISSUE THREAD

**Issue by eliasku** [floooh/sokol#592]
https://github.com/floooh/sokol/blob/dfe57a9d8d765dc5e689d238127558dafa72b7a3/sokol_time.h#L211

Maybe better use `emscripten_now` and `emscripten_now_res` functions for better support? Already has nodejs, conditional browsers compat and they are keeping potential future pthread implementation in mind. I personally use NodeJS to run headless wasm unit tests, and currently I have to precat js code with node require to expose performance.now in global variable. Take a look, 
https://github.com/emscripten-core/emscripten/blob/main/src/library.js#L2530

Another nice option is just to add some init with checkings and exposing `performance.now` in globals.

Thank you

**Comment by floooh** [comment]
Ok makes sense. I just replaced the direct call to performance.now() with emscripten_get_now():

https://github.com/floooh/sokol/commit/4162b001c8292a23049d8e253d17fcd7de382ed5
