### ISSUE TITLE
Black texture on WebGL

### ISSUE THREAD

**Issue by geekynils** [floooh/sokol#601]
This is probably not an issue with sokol, but rather me not using it properly. Unfortunately I could not figure out what's wrong so that's why I ask: I created a small tool for image processing with a minimal GUI using sokol-app, sokol-gfx, sokol-imgui and IMGUI (the original C++ version). In addition to the small IMGUI GUI I also show one texture with the following pipeline:

```
  sg_pipeline_desc pipelineDesc = {
      .shader = sg_make_shader(shader_desc),
      .layout = {
          .attrs = {
              [ATTR_vs_pos].format = SG_VERTEXFORMAT_FLOAT3,
              [ATTR_vs_texcoord0].format = SG_VERTEXFORMAT_FLOAT2
          }
      },
      .index_type = SG_INDEXTYPE_UINT16,
      .label = "pipeline"
  };
```

The shader is also very simple:

```
@vs vs
in vec4 pos;
in vec2 texcoord0;
out vec2 uv;

void main() {
    gl_Position = pos;
    uv = texcoord0;
}
@end

@fs fs
uniform sampler2D tex;

in vec2 uv;
out vec4 frag_color;

void main() {
    frag_color = texture(tex, uv).rrrr;
}
@end

@program texture vs fs

```

To make sure I get the right shader description for each platform I use the generated `texture_shader_desc(...)` function which the `sokol-shdc` tool generated:

```
const sg_shader_desc *shader_desc = texture_shader_desc(sg_query_backend());
```
So far I used it on my Mac with the metal backend and everything work as expected.  I also tried to compile it with emscripten and run it in the browser but I cannot see the texture, it's just black. I compiled the debug version for the web with `-sASSERTIONS=1` but got no assertions or warnings. What could be wrong or what should I check? This is the first time I try WebGL with emscripten

**Mac**
<img width="1028" alt="Mac" src="https://user-images.githubusercontent.com/134199/147102266-bcea5a9b-2696-42e9-97f4-7d8cbd6d1774.png">

**WebGL**
<img width="1002" alt="WebGL" src="https://user-images.githubusercontent.com/134199/147102518-501f0011-e9f3-4240-bc9b-b0704171669d.png">

**Comment by floooh** [comment]
WebGL(1) has various texture size restrictions, e.g. check on the devtools console if there are error messages like this:

```
RENDER WARNING: texture bound to texture unit 0 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
```

If this is the problem, create the non-power-of-2 textures with clamp-to-edge wrapping:

```c
sg_image img = sg_make_image(&(sg_image_desc){
    ....
    .wrap_u = SG_WRAP_CLAMP_TO_EDGE,
    .wrap_v = SG_WRAP_CLAMP_TO_EDGE
});
```
...which allows WebGL to render from NPOT textures. Alternatively, switch to WebGL2, which (AFAIK) also drops those restrictions.

**Comment by geekynils** [comment]
I figured it out. I hate answering my own question but maybe it somebody in the future. Here is what happens if you run it in Firefox:

![WebGLError](https://user-images.githubusercontent.com/134199/147152725-7f51b9ef-0291-46e9-ac15-5615e09381ac.png)

With Safari there is no warning but of course it will not work.

So instead of using the default settings in `sg_image_desc` you have to set:

```        
.wrap_u = SG_WRAP_CLAMP_TO_EDGE,
.wrap_v = SG_WRAP_CLAMP_TO_EDGE,
```

Just wondering? Why not set this to default instead it would work with WebGL, Metal and other APIs as well?

**Comment by geekynils** [comment]
@floooh thx for the answer :-) Actually I was hoping to keep WebGL 1 a bit longer since I do not need more functionality then what it offers.
