### ISSUE TITLE
Does sokol_app have something similar to GLFW_NO_API?

### ISSUE THREAD

**Issue by thebusytypist** [floooh/sokol#604]
I am considering to use sokol_app as a windowing/event abstraction and create` "context" (Vulkan surface actually) manually.
But it seems sokol_app always requires a backend. Is there a way to skip the backend creation?

**Comment by floooh** [comment]
No this isn't supported. In some backends (like macOS and iOS) the frame callback is called directly from the same object which also manages the 3D-API swapchain (e.g. MTKView, GLKView), disentangling this would be a bigger task. For a Vulkan renderer, GLFW might be the better option.

**Comment by thebusytypist** [comment]
Recently learning some cocoa programming and metal stuff.

I think if we start with an `NSWindow` (which is an `NSResponder`), then creating an `NSView` and a `CAMetalLayer` manually then event handling, frame callback (CVDisplayLink) and rendering can be probably decoupled.
(FYI https://developer.apple.com/documentation/metal/drawable_objects/creating_a_custom_metal_view?language=objc)

In my experiment I started with your sample `osxentry.m` and replaced that MTKView with a custom NSViewController, and created my own view in its `loadView` method.

Just some thoughts to share with you while learning Metal. I understand that other combinations (e.g. OpenGL on macOS, or Metal on iOS) may have other implications.
