### ISSUE TITLE
Can't find any documentation

### ISSUE THREAD

**Issue by chriscamacho** [floooh/sokol#609]
Unfortunately some examples and the headers themselves don't really cut it as documentation (doxygen is easy once you get over an initial hump)

When evaluating a new library I usually browse through the API docs, knowing that I will need to refer to them possibly frequently, before even looking at example code.  Documentation matters !

Having to dig through a libraries source while mid coding flow, just isn't fun, even just a cheat sheet like the raylib one would be at least something!

**Comment by floooh** [comment]
The main documentation is in the big comment block at the start of each header, and additional documentation is above each public struct.

Maybe at some point this will be brought into a form where it can be automatically extracted into a static web page, but that's currently not high priority.

I used Doxygen in former projects and wasn't a big fan, the documentation tends to become too granular, while the "hypertext linking" is also available in IDEs with Intellisense.

One thing I definitely want to fix though is to make the inline documentation "VSCode friendly", currently this just shows the documentation block above each struct, and this obscures too much of the screen.

**Comment by chriscamacho** [comment]
I get your point about doxygen, I know that raylib uses a custom script to
extract from source, that might be the way to go...

Geany is as near to an IDE as I can tolerate with a browser and separate
terminal, and a boiler plate automagical makefile...



On Wednesday, 12 January 2022, Andre Weissflog ***@***.***>
wrote:
> The main documentation is in the big comment block at the start of each
header, and additional documentation is above each public struct.
>
> Maybe at some point this will be brought into a form where it can be
automatically extracted into a static web page, but that's currently not
high priority.
>
> I used Doxygen in former projects and wasn't a big fan, the documentation
tends to become too granular, while the "hypertext linking" is also
available in IDEs with Intellisense.
>
> One thing I definitely want to fix though is to make the inline
documentation "VSCode friendly", currently this just shows the
documentation block above each struct, and this obscures too much of the
screen.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you authored the thread.<
https://ci4.googleusercontent.com/proxy/ZCPauo0Ow379zC2mM4OdP5xVmrKw-qJnVKl_k5oTxRBAoZzqx-F8VGOMUfjBeGaUJbFNJxltfw5WUUGoOJq1xbbPbFrIK727lYXobwfBXUtosn4c7yEzS5VgD7rGea8sWUAP1aZZfgnf6qYizK1X7BjZEvXrmjh_m4DrS9A974uM_drY3ZsDua1jD7siCcWExfhRIy7XXGPakHHnD7l9A2rziVcsYYmDDtj6PJFuYw=s0-d-e1-ft#https://github.com/notifications/beacon/AAFO4SL4IVOYSEAKP7C32RTUVW5TBA5CNFSM5LZP65N2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOHRDUJLA.gif>Message
ID: ***@***.***>

-- 

blog bedroomcoders.co.uk <http://bedroomcoders.co.uk>
Free source code and tutorials!


Disclaimer:
By sending an email to ANY of my addresses you are agreeing that:

   1. I am by definition, "the intended recipient"

   2. All information in the email is mine to do with as I see fit and make
such financial profit, political mileage, or good joke as it lends itself
to. In particular, I may quote it where I please.

   3. I may take the contents as representing the views of your company.

   4. This overrides any disclaimer or statement of confidentiality that
may be included on your message.
