### ISSUE TITLE
sokol_audio wasapi: audio client initialize failed

### ISSUE THREAD

**Issue by jeffkdev** [floooh/sokol#614]
When updating from b3ffdf3e561 to master I found audio wasn't working anymore on Windows. Getting the error:
`sokol_audio wasapi: audio client initialize failed`

I checked out a fresh sokol-examples branch and am seeing the same issue on the saudio-sapp sample as well. The error code is -2147024809. I'm not sure the best way to map that the actual error string- but I can add some code on my side if you have any ideas.

It seems like changing the initialization to use WAVEFORMATEXTENSIBLE might be the source of the issue. From this commit:
https://github.com/floooh/sokol/commit/73e6236d95fbd05063b0182df5b5a33b468b69e1#diff-6895bcde273e33259102954399efb1bd6c705ae45183843da44b14ccc8006e09

I was able to reproduce the problem on two different Windows 10 computers.

**Comment by floooh** [comment]
Ouch, I will start investigating after finishing the DPI-handling stuff (earliest tomorrow afternoon).

Can you provide information about the exact Win10 build version, audio hardware and drivers in those two computers that fail?

My current guess is that the float sample format is not compatible with all audio devices, if that's the case it might make sense to revert this change back to 16-bit integer sampels.

**Comment by jeffkdev** [comment]
Sure! It's no rush on my end, I just reverted the sokol_audio change on my fork and it is working same as before.

PC 1 (few years old desktop):
Windows 10 Pro
Version: 20H2
OS build: 19042.1466
Audio: Realtek High Definition Audio (6.0.8703.1)

PC 2 (new laptop):
Windows 10 Home
Version: 21H1
OS build: 19043.1415
Audio: Realtek(R) Audio (6.0.9167.1)

Let me know if there is any other info I can add or if there is anything you want me to test on my end.

**Comment by floooh** [comment]
Ok, I'm starting to look into this now. Unfortunately none of my 3 PCs has the problem (an Asus Zenbook with a "Conexant" audio device, an old Hp 360 with "Intel Smart Sound", and a somewhat recent desktop PC with "RealTek(R) Audio" v6.0.1.8627.

I'll first try to make sense of the error code and then will have a look what the WASAPI backends in SoLoud and miniaudio look like. But I think the most robust solution would be going back to a sample format that's supported anywhere.

**Comment by floooh** [comment]
Hmm that error code -2147024809 (or hex 0x80070057) doesn't look like an ```AUDCLNT_E_*``` error listed here:

https://docs.microsoft.com/en-us/windows/win32/api/audioclient/nf-audioclient-iaudioclient-initialize#return-value

For instance ```AUDCLNT_E_UNSUPPORTED_FORMAT``` is 0x88890008, and all AUDIOCLNT_E errors should follow that 0x888900xx pattern.

**Comment by jeffkdev** [comment]
Running the saudio-sapp sample again just now I saw a console message I missed:
`
avcore\audiocore\client\audioclient\audioclientcore.cpp(1501)\AUDIOSES.DLL!00007FFCFCC06E8F: (caller: 00007FFCFCBE4FE5) ReturnHr(1) tid(40e8) 80070057 The parameter is incorrect.
`

**Comment by floooh** [comment]
Hm ok thanks :)

Could you "inject" this snippet before the call to IAudioClient_Initialize() and in show the content of the resulting WAVEFORMATEX or WAVEFORMATEXTENSIBLE struct?

```c
WAVEFORMATEX* wfx = 0;
WAVEFORMATEXTENSIBLE* wfext = 0;
IAudioClient_GetMixFormat(_saudio.backend.audio_client, &wfx);
if (wfx->wFormatTag == WAVE_FORMAT_EXTENSIBLE) {
    wfext = (WAVEFORMATEXTENSIBLE*)wfx;
}
```

Here on my desktop PC with RealAudio I see:

![image](https://user-images.githubusercontent.com/1699414/150350185-4b1bbe92-b96f-4d77-826f-7bb890a53bee.png)

**Comment by floooh** [comment]
...it's notable that the number of channels (2) and samplers per second (48000) don't match what's requested by the saudio-sapp sample (which wants 1 channel and 44100 Hz, but despite those differences the initialization still works here)

**Comment by jeffkdev** [comment]
![image](https://user-images.githubusercontent.com/18176443/150350593-34f996cc-5c8e-4ad4-8dc9-853102cba00a.png)

**Comment by floooh** [comment]
How weird, it's identical! (at first I thought the SubFormat differs, but that's just a pointer, the actual UUID is identical.

Hm hm hm... that's a bit unexpected TBH...

**Comment by floooh** [comment]
Total shot in the dark, and it's a bit hilarious, but when googling I found this:

https://stackoverflow.com/questions/46281593/iaudioclientinitialize-returns-e-invalidarg-0x80070057-2147024809

There isn't a 3rd-party AntiVirus on those machines by chance? :)

**Comment by jeffkdev** [comment]
Fair guess, but nope. 
Not sure if it is a useful data point, but if I throw the wfext in the initialize instead of fmtex it does pass (but of course the sample doesn't sound right since I'm sure the parameters don't match).

**Comment by floooh** [comment]
Ok another thing to try:

Could you check if the other audio sample (modplay-sapp) works? This uses 2 channels, but 44100 Hz.

If it doesn't could additionally ask sokol_audio.h to run at 48000 Hz by changing the call to saudio_setup() like this:

```c
    /* setup sokol_audio (default sample rate is 44100Hz) */
    saudio_setup(&(saudio_desc){
        .num_channels = MODPLAY_NUM_CHANNELS,
        .sample_rate = 48000,
        #if !MODPLAY_USE_PUSH
        .stream_userdata_cb = stream_cb,
        .user_data = state
        #endif
    });
```
...that way the number of channels and sample rate would be the same that's returned by GetMixFormat().

**Comment by jeffkdev** [comment]
Oh yep, that worked without any changes.

**Comment by floooh** [comment]
Aha! So it's the number of channels, and the sample rate doesn't matter.

That SubFormat returned by GetMixFormat is the Float sample format btw.

Ok, in that case I will simply ask IAudioClient to initialize with its preferred number of channels, and do either duplicate or 'accumulate' the sample stream that's coming in from the application.

The documentation is actually very vague about what properties need to match the "driver expectations", the way I read it those details shouldn't matter for "shared mode", but ¯\_(ツ)_/¯

...I wonder if it would make more sense to have an XAudio2 backend on Windows. When I looked into this first it was a bit awkward because there are two different XAudio2 DLLs depending on Windows version, but when loading the DLL with LoadLibrary() that probably wouldn't matter much.

Anyway... for now I'll just implement the fix as above.

Thanks for your help so far :)

**Comment by jeffkdev** [comment]
This fixes saudio-sapp for me:
```fmtex.dwChannelMask = SPEAKER_FRONT_LEFT | SPEAKER_FRONT_RIGHT;```
to
```fmtex.dwChannelMask = SPEAKER_FRONT_CENTER;```

These defines I saw in ksmedia.h were my hint:
```
#define KSAUDIO_SPEAKER_MONO            (SPEAKER_FRONT_CENTER)
#define KSAUDIO_SPEAKER_1POINT1         (SPEAKER_FRONT_CENTER | SPEAKER_LOW_FREQUENCY)
#define KSAUDIO_SPEAKER_STEREO          (SPEAKER_FRONT_LEFT | SPEAKER_FRONT_RIGHT)
```
Probably just would need to go behind an if-statement to cover both 1 and 2 channels and then should be good to go.

**Comment by floooh** [comment]
Good idea! I'll get something to eat first though ;)

**Comment by floooh** [comment]
Ok, fixed in https://github.com/floooh/sokol/commit/537568c405a0dc533692c676fa06b957b2b6f89c, I'll check on my other PCs and update the changelog next. If it's not working on your end for some reason, just re-open the ticket.
