### ISSUE TITLE
sokol-app: clicking on title bar crashes application when undefined behavior checks are enabled

### ISSUE THREAD

**Issue by jeffkdev** [floooh/sokol#616]
When updating my sokol-zig-examples repo (https://github.com/jeffkdev/sokol-zig-examples) to use the latest version of Sokol it crashes when I clicked on the title bar the triangle example with an "illegal instruction" error. I checked out your sokol-zig repo (https://github.com/floooh/sokol-zig), copied in the latest sokol-app.h and the triangles program crashed for me as well when clicking on the title bar.

Removing the new case statement added in this commit https://github.com/floooh/sokol/commit/c9a36146320aa49ac79e44467d98d9eca31243f1 fixed it in both cases for me https://github.com/jeffkdev/sokol/commit/9b7777aafa98f418fa918621f30b428f2b414d06.

However, running the triangle-sapp example on the normal C sokol-examples and moving the title bar with the latest commit *does* work for me without crashing.

I'm hoping once you update your Zig examples to use the latest sokol_app you'll see it on your end too and then it should be easier to debug. But otherwise let me know if it just happening to me I'll dig into it a bit more.

**Comment by jeffkdev** [comment]
Updated title. Looks like the bit shift on the signed long is technically undefined behavior since adding `-fno-sanitize=undefined` prevents the error.

Can be fixed by casting them to unsigned longs.
```PostMessage(_sapp.win32.hwnd, WM_MOUSEMOVE, 0, point.x|(point.y << 16));```
to
```PostMessage(_sapp.win32.hwnd, WM_MOUSEMOVE, 0, ((unsigned long)point.x) | ((unsigned long)point.y) << 16);```

**Comment by floooh** [comment]
Good catch! I could reproduce with Zig 0.9.0 on Windows, fixed in https://github.com/floooh/sokol/commit/6cbbe410a981a75f1701bd9101f5a65f1783e5da.

I haven't updated the Zig bindings (because the current bindings don't have that code yet), will do so after the current batch of work (per-monitor DPI, and the sokol_audio.h fix).

**Comment by floooh** [comment]
Erm wait a second, I committed a syntex error, how did that happen?

**Comment by floooh** [comment]
Ok, should be fixed now.
