### ISSUE TITLE
Does application icon work correctly on Mac OS?

### ISSUE THREAD

**Issue by joshgoebel** [floooh/sokol#620]
I see code for it, and I'm seeing it in my sokol_main:

```
    return (sapp_desc){
        .init_cb = init,
        .frame_cb = frame,
        .cleanup_cb = cleanup,
        .icon = {
            .sokol_default = true
        },
        .window_title = "Triangle",
        // .sample_count = 4, // Enable anti aliasing.
    };
```

But I still always see the default terminal script icon:  

![Screen Shot 2022-01-21 at 12 25 10 AM](https://user-images.githubusercontent.com/6473/150470939-ce00761a-0b13-4aff-9b39-6eee4171714b.png)

**Comment by floooh** [comment]
This looks like the application is compiled as a simple executable, not as a macOS application bundle. For instance when using cmake, the application executable must be declared with:

```cmake
    add_executable(target MACOSX_BUNDLE sources ...)
```

...or when using fips:

```cmake
     fips_begin_app(bla windowed)
```

...and not:

```cmake
     fips_begin_app(bla cmdline)
```
