### ISSUE TITLE
[Feature Request] Native File Select Dialog

### ISSUE THREAD

**Issue by skylersaleh** [floooh/sokol#626]
While custom file pickers can be implemented manually using libraries like ImGui, they suffer from a few big problems compared to the native file pickers: 

- Applications running on mobile and web platforms often have restrictions on what files they may access without using native APIs. 
- They often look out of place and are less featured than the native file select dialogs
- They are a lot of effort to implement. 

To rectify this, it would be fantastic if an API could be added to sokol_app to open a platforms native file select dialog. Opening something like this on desktop platforms. 

![image](https://user-images.githubusercontent.com/7118296/152655394-e06bfeba-e9a6-4764-ba29-32256119a11a.png)

Or this on Mobile platforms. 

![image](https://user-images.githubusercontent.com/7118296/152655474-ccdc00b6-13b0-4812-b325-98048429d15e.png)

**Comment by iboB** [comment]
Why not just use this: https://github.com/mlabbe/nativefiledialog

**Comment by skylersaleh** [comment]
> Why not just use this: https://github.com/mlabbe/nativefiledialog

That library doesn't support iOS, Android, or Emscripten. Plus it would be nice to have something integrated that follows the rest of sokol's design.

**Comment by kritzikratzi** [comment]
it sounds like a simple task, but in my experience it's highly platform specific and hard to abstract. 

i'm guessing you end up spending around a week of agony per platform and contributing to https://github.com/mlabbe/nativefiledialog seems to be the more sane choice.

**Comment by skylersaleh** [comment]
> it sounds like a simple task, but in my experience it's highly platform specific and hard to abstract.
> 
> i'm guessing you end up spending around a week of agony per platform and contributing to https://github.com/mlabbe/nativefiledialog seems to be the more sane choice.

The fact that this is code that is highly platform specific seems like it would make it a perfect fit for sokol_app, as the main purpose of the sokol_app library is to abstract common platform specific operations that would be required to make an application.

**Comment by floooh** [comment]
I'll close this issue since the feature would really be better implemented in a separate library (if sokol_app.h needs to expose more platform-specific information to integrate with such a library then it makes sense to put that into a new ticket)
