### ISSUE TITLE
Assert break in sokol_gfx init: Linux + glew 1.13

### ISSUE THREAD

**Issue by septag** [floooh/sokol#63]
Hi
I'm on ubuntu with installed package glew 1.13.
I got assertion on the first ```_SG_GL_CHECK_ERROR();``` in *_sg_create_context* function. because there was a pending GL error (GL_INVALID_ENUM)
It seems that the problem is with version 1.13 of glew documented [here](https://www.khronos.org/opengl/wiki/OpenGL_Loading_Library)

So I had to reset the errors after _glewInit_. Is it ok if sokol_gfx clears errors on setup and throw a warning or something, in case if previous errors are raised by glew or similiar lib ?

**Comment by floooh** [comment]
Yes I think it's a good idea that sg_setup() clears the GL error (and probably logs a warning as you wrote).

**Comment by floooh** [comment]
This has been fixed in ef752937404d927fbf83be87df8b97a300e1c383
