### ISSUE TITLE
"sgl_ortho" works differently in GL3 and in D3D

### ISSUE THREAD

**Issue by hbiblia** [floooh/sokol#635]
I am using sokol_gl this piece of code works differently when I use SOKOL_D3D11 and SOKOL_GLCORE33.

```c
        float top = camera.fov * camera.size;
        float right = top * aspect;
        sgl_ortho(-right, right, top, -top, EGFX_CULL_DISTANCE_NEAR, EGFX_CULL_DISTANCE_FAR);
````

I am rendering a texture and this is the result I get, is this a "sokol_gl" error or my code?

**SOKOL_GLCORE33**
![image](https://user-images.githubusercontent.com/1939353/156449306-2e81d182-dc57-4e2d-a88b-42dfc72c6253.png)

**SOKOL_D3D11**
![image](https://user-images.githubusercontent.com/1939353/156449354-e4090056-97f9-45ae-9781-db394a822b3c.png)

**Comment by floooh** [comment]
Hmmm.... what's the value for EGFX_CULL_DISTANCE_NEAR? In the few places in the samples where I used sgl_ortho I always used -1.0f and +1.0f for 2D rendering just to make sure that the rendering is clipped against the near plane. Not sure why this would only happen on the D3D backend though:

https://github.com/floooh/sokol-samples/blob/1fe2ac2b0d4c1295c13a427b81e18eb8754ed40a/sapp/fontstash-sapp.c#L153

https://github.com/floooh/sokol-samples/blob/1fe2ac2b0d4c1295c13a427b81e18eb8754ed40a/sapp/basisu-sapp.c#L120

https://github.com/floooh/sokol-samples/blob/1fe2ac2b0d4c1295c13a427b81e18eb8754ed40a/sapp/sgl-microui-sapp.c#L447

D3D and GL have different opinions about the clip space Z range though (one is from 0.0 to 1.0, and the other from -1.0 to 1.0), and the embedded shader in sokol_gl.h doesn't "normalize" this via the ```fixup_clipspace``` option described here: https://github.com/floooh/sokol-tools/blob/master/docs/sokol-shdc.md#glsl_options-hlsl_options-msl_options

I guess this can be considered a bug. But a workaround try the near/far -1, +1 range in the sgl_ortho() call.
