### ISSUE TITLE
SG_PRIMITIVETYPE_POINTS and point size

### ISSUE THREAD

**Issue by timeinpixels** [floooh/sokol#636]
Is there a way to define a point size for Metal macOS shader generated using sokol-shdc?
There's a function call to specify that for OpenGL, but in Metal it actually has to be done inside shader...

Any suggestions other than supplying metal source code for the vertex shader myself?

**Comment by floooh** [comment]
Check the primtypes-sapp sample:

https://floooh.github.io/sokol-html5/primtypes-sapp.html

In the GLSL source code, apply a value to gl_PointSize, and then sokol-shdc will do the right thing (via SPIRVCross).

https://github.com/floooh/sokol-samples/blob/master/sapp/primtypes-sapp.glsl

Be aware though that this doesn't work in D3D11, which doesn't support a point size at all (point list primitives are always point size 1), and also won't work in WebGPU (as I just discovered), so a proper cross-platform way to render point list with a point size > 1 would need to be implemented outside of sokol_gfx.h with triangles.

**Comment by timeinpixels** [comment]
Oh! Fantastic - thanks!
