### ISSUE TITLE
iOS menu tap does not seem to work

### ISSUE THREAD

**Issue by OkanArikan** [floooh/sokol#637]
While running imgui-sapp sample (fips config sapp-metal-ios-xcode-debug), I see two issues on iPhone 12:

1. The initial click and drag is using incorrect initial position. When you touch, the window jumps. Seems related to DPI?
2. If somehow, you manage to get the Imgui demo window into view, you can tap on the menu bar to open the menus, but tapping on a menu item does not seem to take affect. It does close the menu however, so something right is going on.

**Comment by floooh** [comment]
Hmm this might be an issue with the new evented input code in Dear ImGui, which has some issues for touch input:

https://twitter.com/ocornut/status/1491069840035135489

**Comment by floooh** [comment]
I just merged a PR which should fix the issue (only tested on the WASM samples webpage on my Android device, but it should generally fix touch input). See: https://github.com/floooh/sokol/pull/760 and https://github.com/floooh/sokol/issues/759
