### ISSUE TITLE
Possible to implement 9 slice skinning with sokol + imgui?

### ISSUE THREAD

**Issue by quetzalsly** [floooh/sokol#639]
![9s](https://user-images.githubusercontent.com/38719748/157152806-ca08d0e8-3f34-48cd-9712-d20f5c26d0ec.png)

I know nuklear supports something like this already but I really like imgui. I am wondering if its possible to do this with the help of sokol_imgui.h? The idea was to have tiles and simply place them on the screen based on the window x,y,w,h with the minimum window dimensions being a 9 tile block.

So far I have tried:
* Make a new imgui window, set its flag to have a transparent background
* Setup the rendering loop like the sokol samples, everything works
* Implemented the callback functionality like sokol callback example, it works and draws something as a test

The first issue is that sokol_imgui.h has its own pipeline and switches back to it right after calling the user callback is called. Should I be constantly switching like that? my pipe to that pipe and back for many GUI elements? would it possible to not switch and just work with sokol_imgui.h pipe and draw quads somehow?

The other issue is that, maybe its better to append quads to the draw list in the callback without drawing quads myself?

The final issue is that how can I pass user data to the callback? how would I know which texture to use to draw my quads.

Also forgot to ask, does the sokol_imgui.h do any backface culling? could not see anything.

**Comment by floooh** [comment]
I wouldn't implement this in a callback, but instead with a helper function which uses ImGui's DrawList API, for instance something like this:

https://github.com/floooh/chips/blob/6e191f35b74ae839ed8b99ff9077d406dd828c72/ui/ui_chip.h#L246-L321

Which renders something like this:
<img width="169" alt="Screenshot 2022-03-08 at 15 10 09" src="https://user-images.githubusercontent.com/1699414/157254429-4c04a281-e478-483a-b0fd-2fb4045270b7.png">

For image rectangles you'd need to use one of those functions:

https://github.com/ocornut/imgui/blob/0f14933577a1de01d90f8e87622296c466146f21/imgui.h#L2555-L2561

AFAIK Dear ImGui does all its rendering through this DrawList API too, so it should be relatively straightforward to implement your own custom widgets with this.

**Comment by quetzalsly** [comment]
Thanks! I was looking at callback when it fact you dont need any callback, just GetWindowDrawList(). It works perfectly. Regarding backface culling, it seems imgui example backends also dont use any culling. Is this something to do with the way imgui handles winding order? I guess I can leave it as it is?

**Comment by floooh** [comment]
I'm actually not sure if Dear ImGui draws all triangles in the same winding order, it's probably best to disable backface culling.
