### ISSUE TITLE
sokol_app: Compile error on MSVC + cl

### ISSUE THREAD

**Issue by septag** [floooh/sokol#64]
when building with cpp cl compiler, I get error in sokol_app.h, line 2873:
```
1>error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
```

here's the place where it happens (function: _sapp_d3d11_destroy_device_and_swapchain):
```
_SOKOL_PRIVATE _sapp_d3d11_destroy_device_and_swapchain(void) {
    _SAPP_SAFE_RELEASE(IDXGISwapChain, _sapp_dxgi_swap_chain);
    _SAPP_SAFE_RELEASE(ID3D11DeviceContext, _sapp_d3d11_device_context);
    _SAPP_SAFE_RELEASE(ID3D11Device, _sapp_d3d11_device);
}
```

I guess inserting void on the beginning of the declaration solved the problem

**Comment by floooh** [comment]
Indeed! I wonder why that slipped through the CI test in sokol-samples.
