### ISSUE TITLE
Q: Pool Sizes

### ISSUE THREAD

**Issue by DctrNoob** [floooh/sokol#641]
I'd like to clarify a potential misunderstanding regarding pool sizes because I quickly ran into "pipeline pool exhausted" in my app.

The default pipeline pool size is 64 so assuming that I don't change that size I can have a maximum of 64 pipelines at the same time, right? And since you need a dedicated pipeline per shader, this basically means that once your app has 64 unique objects in a scene (each with a unique shader) the pipeline is already exhausted, or is it?

If this understanding is correct, I should configure the pool size to be sufficiently large for my maximum amount of concurrent unique scene objects, right?

Thanks!

**Comment by floooh** [comment]
Yep, you need (at least) one pipeline object per shader, and the pool size if the maximum number of objects of a type (buffers, images, shaders, pipelines and passes) that can be alive at the same time. You can increase the number generously in the ```sg_setup()``` call (currently up to around 16k), the only downside is slightly more memory usage (but this is about KBytes, not MBytes).

**Comment by DctrNoob** [comment]
Great, thanks for clarifying.
