### ISSUE TITLE
How to return value after sapp_quit() on MacOS

### ISSUE THREAD

**Issue by danhambleton** [floooh/sokol#642]
It appears that with code like this on MacOS:

```    
    ...
    desc.init_cb = init;
    desc.frame_cb = frame;
    desc.cleanup_cb = cleanup;

    sapp_run(&desc);

    std::cout << "done\n";

    return state.image_data;
```

I will never hit the code after `sapp_run` and therefore never return the contents of `state.image_data` on MacOS. Is there anyway to manually exit the frame loop or otherwise quit but hit those lines of code?

**Comment by floooh** [comment]
Unfortunately there's now cross-platform way to execute code after sapp_run(). Particularly macOS won't return from ```[NSApp run]``` as commented here:

https://github.com/floooh/sokol/blob/e8931e4399a0eb4bf026120d7bdb89825815af9e/sokol_app.h#L3094-L3097

Mobile operating systems (and the web) also tend to simply terminate the process without warning (so not even the cleanup callback might be called).

On macOS, the only place to run "exit code" is in the cleanup callback (which will be called from the ```applicationWillTerminate``` event handler here:

https://github.com/floooh/sokol/blob/e8931e4399a0eb4bf026120d7bdb89825815af9e/sokol_app.h#L3461-L3466
