### ISSUE TITLE
iOS orientation change triggers MTL assertion

### ISSUE THREAD

**Issue by OkanArikan** [floooh/sokol#645]
While running the imgui-sapp sample on an iPhone (fips config sapp-metal-ios-xcode-debug), changing device orientation triggers a MTL assertion:

-[MTLDebugRenderCommandEncoder setScissorRect:]:3635: failed assertion `Set Scissor Rect Validation
(rect.y(0) + rect.height(480))(480) must be <= render pass height(320)

from function _sg_mtl_apply_scissor_rect, line [_sg.mtl.cmd_encoder setScissorRect:r];

**Comment by floooh** [comment]
Ok, I now have both autoResizeEnabled on the MTKView, and explicitely set the view size in ```_sapp_ios_update_dimensions()```. This seems to be the only way to "make it work" despite not making much sense.

It's yet another argument to scrap MTKView and insteas use CAMetalLayer directly.

**Comment by OkanArikan** [comment]
Thank you for looking into this.

**Comment by floooh** [comment]
@OkanArikan: unfortunately this fix triggers a Metal validation layer error now (at least in the simulator, haven't checked on device yet), see https://github.com/floooh/sokol/issues/726.

**Comment by floooh** [comment]
...it seems I can no longer reproduce the original issue of triggering that assertion when the device orientation changes (on an iOS iPhone12 simulator with Xcode 13.4.1). I have reverted this "fix" (e.g. autoResizeEnabled is now turned off again). This fixes both the validation layer warning while device rotation appears to work.
