### ISSUE TITLE
Sokol+imgui+emscripten+gles2, android firefox key problem

### ISSUE THREAD

**Issue by voidware** [floooh/sokol#647]
I'm using Sokol+imgui+emscripten+gles2

imgui + sokol + firefox. all latest versions.
emcc v3.1.7

I'm not getting enter or backspace keys (in fact possibly not _any_ keys) working. characters _are_ working. So in a Imgui `InputText` only characters appear, eg normal letters.

This is only with Android (currently firefox). Desktop versions work fine.

I don't know whether key events are even working. I can't get any debugging output going either (my fault). For some reason, android remote USB debugging + emscripten produces nothing for `console.log`. Not sure why.

I was wondering if you've any idea why there'd be a difference for Android firefox?

**Comment by floooh** [comment]
Yeah these are known problems unfortunately. Keyboard input on mobile browsers uses a very fragile hack by creating a hidden text input field and then programmatically focusing this to make the virtual keyboard show up. When I implemented this there were all sorts of differences between browsers and platforms, I don't quite remember which platforms and browsers caused trouble. I think I had it working on iOS, but IFIR it never worked reliably on Android.

I'm not aware of a more robust solution though, virtual keyboard support in browsers on mobile platforms seems to be limited to very specific scenarios (such as regular text input fields which need to be tapped to be activated, and it looks like not all browsers generate key input events while a text input into an input element happens).

**Comment by voidware** [comment]
OK, after some hacking it appears `key` is still valid.

`sokol_app.h/_sapp_emsc_key_cb`

```
                //_sapp.event.key_code = _sapp_emsc_translate_key(emsc_event->code);
                _sapp.event.key_code = _sapp_emsc_translate_key(emsc_event->key);
```

But according to the docs, `code` should be correct. I run the emscripten test `test_keyboard_codes.c` and `code` is empty, but `key` is populated (except when it's set to "Process", whatever that means).

So now, my problem is stopping the virtual keyboard from popping up when i touch random non-input UI components....  :)
