### ISSUE TITLE
sokol+emscripten, safari does not scroll to accommodate virtual keyboard

### ISSUE THREAD

**Issue by voidware** [floooh/sokol#648]
on iOS. Virtual keyboard just overlays the input box and you can't see anything.

tried `.ios_keyboard_resizes_canvas`, but i think this is for iOS build and not emsc.

any clues?

**Comment by floooh** [comment]
(I assume this was for Emscripten, closing the ticket since virtual keyboard support for web has been removed recently)

**Comment by voidware** [comment]
Yes. All working here now.
