### ISSUE TITLE
What's the reasoning for primitive type baked into the pipeline?

### ISSUE THREAD

**Issue by meshula** [floooh/sokol#655]
What's the reasoning for primitive type baked into the pipeline? I can see that the internal platform state has the SG_PRIMITIVE type converted to platform native, and that the baking step transmogrifies this value. But, is there another reason?

The reason I ask, is that I have a simple drawing pipeline, that can draw triangles, or it can draw triangle strips. At the moment I am creating the TRIANGLE pipeline, then creating a duplicate pipeline for TRIANGLE_STRIP. It's unintuitive to me why I'd want to apply the pipelines back and forth in my drawing code, instead of simply using the one pipeline, and calling sg_draw repeatedly with the appropriate primitive type. Even if they are identical pipelines, I'm incurring overhead within sokol as it checks if the shader program is different and so on.

I double checked what sgl does, and I can see it has a pipeline cache which makes me think I'm understanding the setup correctly. But I'm wondering why the primitive type is in the pipeline, not a sg_draw parameter, as the latter seems much more intuitive, and, presumably, more efficient if pipeilne switches can be reduced.

**Comment by floooh** [comment]
Some of the new-ish 3D APIs (for instance WebGPU, and I think Vulkan and D3D12 too) require the primitive topology in the pipeline state:

E.g. in WebGPU:

https://github.com/webgpu-native/webgpu-headers/blob/b46ca3c39249c537b2b421a37cf06b0d20bbf2c1/webgpu.h#L794

...the surrounding WGPUPrimitiveState is part of the pipeline creation structure WGPURenderPipelineState here: https://github.com/webgpu-native/webgpu-headers/blob/b46ca3c39249c537b2b421a37cf06b0d20bbf2c1/webgpu.h#L1175

I think Vulkan and D3D11 only need to know whether the pipeline is used to render triangles, lines or points (e.g. the same pipeline could be used for triangle lists and strips), but in WebGPU the detailed primitive type is required.

Metal had added something similar (https://developer.apple.com/documentation/metal/mtlrenderpipelinedescriptor/1514684-inputprimitivetopology?language=objc) but apparently that's only needed for "layered rendering" (not exactly clear to me what that means, maybe rendering to layers of an array texture?)

**Comment by meshula** [comment]
Coincidentally, I'm using GL on Windows and Metal on Mac, so my perspective must be biased :) Thanks for the detailed response.

**Comment by floooh** [comment]
Btw, I remember having read on several occassions that triangle strips don't really make much sense on modern CPUs anymore compared to triangle lists with vertex indices (in the right order) because of the post-transform vertex cache.

Maybe dropping triangle strips in favour of indexed triangle lists would also be an option? If not, then maybe it's at least possible to group lists and strips into separate buckets so that switching between the two is minimized.

Meshoptimizer (https://github.com/zeux/meshoptimizer) might help with creating vertex indices in optimal order. I haven't used it yet, but AFAIK it's pretty much the standard these days :)

**Comment by meshula** [comment]
Definitely indexed lists are a win, both from a transform cache perspective and from a bandwidth perspective. It would be simple enough to change my code to eliminate strips. I think that would be a smart change, thanks for the thoughts.
