### ISSUE TITLE
Sokol nuklear - issue with rendering nk_image

### ISSUE THREAD

**Issue by VerwirrteLaborratte** [floooh/sokol#656]
Hi Hi,

I've got an issue while trying to build a nuklear gui with sokol app, sokol nuklear and sokol gfx. Not sure if this is a bug or expected/intended behaviour, so I'd like to describe it and my solution as best as I can and would like to hear some comments or advise:
My Platform is Ubuntu 20.4, I build with fips and config sapp-linux-ninja-debug ( from the sokol examples).
So in my GUI I would like to render some 2d images as ng_image, for now just static images but goal is to render fast changing images (not every frame but likely changing at 10-20Hz).

So in sokol app init() I create a global nk_image with:

```
sg_image img = sg_make_image(...);
image = nk_image_id(img.id);
```

and in frame() I add it to the GUI with

```
...
nk_layout_row_dynamic(ctx, 400, 1);
nk_image(ctx, image);
...
```
No matter how my image looks like I always got this result (The image is supposed to be displayed under the buttons):
![image](https://user-images.githubusercontent.com/104308783/164994326-1a49e145-49df-4c1e-8c63-2bc1dae142f9.png)

I tried to figure out where this image comes from and also tried a lot of workarounds in my code with no sucess.
Then I started stepping true the actual rendering code with the debugger and figured out that in sokol_nuklear.h in snk_render() in the nk_draw_foreach loop for every cmd  sg_apply_bindings is called with the texture _snuklear.img , which is the font atlas in the global sokol nuklear state object. This texture is bound even when the cmd brings it's own texture handle which is the case for cmd converted from nk_image
Here's a screenshot of the situation from my debugger (cmd->texture.id != _snuklear.img.id):
![image](https://user-images.githubusercontent.com/104308783/164995075-4ec09c5b-a1fe-4f81-a738-18680b15279c.png)

Changing sg_apply_bindings to bind the texture from the cmd in case it differs from _snuklear.img and is not zero solves my problem and the image is rendered and displayed correctly.

So what do you think? Is this a bug or am I missing something? This are my first tries on 3d rendering backends so I actually still quite often have the feeling I don't know exactly what I am doing. ;-)

Best
Andreas

**Comment by floooh** [comment]
Ok this should be fixed now. I also wrote a minimal sample/test here: https://github.com/floooh/sokol-samples/blob/master/sapp/nuklear-images-sapp.c

..sample webpage on the way as soon as CI is green.

**Comment by VerwirrteLaborratte** [comment]
Thanks for the fast fix and confirmation, it's much appreciated!
