### ISSUE TITLE
Support WEBGL_multi_draw

### ISSUE THREAD

**Issue by logankaser** [floooh/sokol#669]
https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_multi_draw
WEBGL_multi_draw is great for when you need to draw many simple objects but can't use instancing because of flexibility issues.
In particular, it helps on chrome-based browsers where draw calls are expensive.

The API has some nice properties:
* It's easy to fall back to a loop calling the non-multi variants, so lack of support in Firefox is not an issue
* The design does not require a GPU upload like how indirect rendering works for desktop GL, but it can be emulated by that.
A downside is that to properly use it, you often need to be able to upload a lot of uniform data. For my renderer I use a dynamic texture for that as Uniform buffers caused many problems, but this adds some usage complexity. (For context I'm rendering 2D maps, so many small objects with disjoint geometry is difficult to combine. Draw call overhead tends to dominate, hence multidraw)

It has been easy enough to add myself by taking the WebGL implementation and making a multidraw version, but it would be cool to see something like this as an optional feature in the main API.

**Comment by floooh** [comment]
Interesting idea, but the fact that it leaks into the shader (via gl_DrawID) is a bit of a bummer (and that it's not supported on Firefox, so there will always need to be two sets of shaders, even if the the draw loop is "emulated" up in sokol_gfx,.h).

It basically comes down to whether SPIRVCross knows about gl_DrawID and somehow can map/emulate this in other 3D backends (D3D11 and Metal).

**Comment by logankaser** [comment]
Hmm, for the Firefox fallback maybe `gl_DrawID` could be emulated as a normal uniform, setting just once uniform per loop iteration would probably not hurt performance much. I'm uncertain if `gl_` variables have some kind of protected status, but if they do, then I agree that the shader compiler would need to alias `gl_DrawID` and the emulated uniform to some third location so that the actual shader body could be shared between them.
As it turns out, Firefox has lower overhead per draw call, I believe the main reason they have not implemented this extension is due to a lack of motivation as compared to Chrome, where draw call minimization matters more.

Both D3D11 and Metal support multi draw (both with the two-stage from GPU buffer style like desktop OpenGL):
https://docs.microsoft.com/en-us/windows/win32/api/d3d11/nf-d3d11-id3d11devicecontext-drawindexedinstancedindirect
https://developer.apple.com/documentation/metal/mtlrendercommandencoder/1515467-drawprimitives
But as you guessed, they don't provide a `gl_DrawID` equivalent.
For DirectX 12 you can define a custom indirect draw argument struct, and if you do it in the right way it will be just as efficient as `gl_DrawID`, but for D3D11 complex workarounds such as binding a buffer with per-instance step rate of 1 to map from instance id to draw id.
I have no idea for metal, the documentation in that area is sparse to put it nicely.

To write a truly portable app, one would have to go with the binding of a buffer with per-instance step rate of 1 to map from instance id to draw id approach, as I think that works in all APIs.
It may be better to just give up and say that the APIs are just too inconsistent for this particular usage mode.
