### ISSUE TITLE
Assertion when running Sokol app in a separate thread from a console

### ISSUE THREAD

**Issue by Oldes** [floooh/sokol#677]
Hi,

I'm trying to run Sokol from a separate thread started from a console application - [Rebol3](https://github.com/Oldes/Rebol3)
Any idea why I'm getting assertion [at line 15753](https://github.com/floooh/sokol/blob/22fbff5f201d0ad01d6795d80822e0260afde768/sokol_gfx.h#L15753), when I hit enter in the console and Sokol is running?

![rebol-sokol](https://user-images.githubusercontent.com/454805/174236819-63d4e2c4-7e1a-40b3-8ede-a5f24d398c31.gif)

Without using `SOKOL_VALIDATE_NON_FATAL` define the assertion is [on line 14126](https://github.com/floooh/sokol/blob/22fbff5f201d0ad01d6795d80822e0260afde768/sokol_gfx.h#L14126).

Sokol is started using code like:
```
static void *Task_Ready;

void Sokol_Run(void *arg) {
    app_state_t* state = (app_state_t*)arg;
    SetEvent(Task_Ready);
    sapp_run(&(sapp_desc){
        .user_data = state,
        .init_userdata_cb = init,
        .frame_userdata_cb = frame,
        .cleanup_cb = cleanup,          /* cleanup doesn't need access to the state struct */
        .width = 800,
        .height = 600,
        .sample_count = 4,
        .gl_force_gles2 = true,
        .window_title = "Sokol Test",
    });
}
...
    REBINT thread;
    app_state_t* state = calloc(1, sizeof(app_state_t));
    Task_Ready = CreateEvent(NULL, TRUE, FALSE, TEXT("Sokol_Task_Launch"));
    if (!Task_Ready) return;

    thread = _beginthread(Sokol_Run, 0, &state);

    if (thread) WaitForSingleObject(Task_Ready, 2000);
    CloseHandle(Task_Ready); 
...
```

**Comment by floooh** [comment]
The assert indicates that the sg_bindings struct contains garbage data (so the canary fields **are** actually useful, I was thinking about removing them).

Can you share the code which initializes that sg_bindings struct which is then passed into sg_apply_bindings()? It looks to me like this isn't properly zero-initialized.

Are maybe doing something like this?

```c
sg_bindings bindings;
bindings.vertex_buffers[0] = ...;
```

**Comment by Oldes** [comment]
I'm really sorry... it was of course my fault... as I was just dirty testing, what is possible, I made the state local to the command and so it was made invalidated somehow. When I make it global (or later in the correct context), it works as expected!
