### ISSUE TITLE
sokol_gfx : Manually sync buffer mapping for dynamic data streaming

### ISSUE THREAD

**Issue by RandyGaul** [floooh/sokol#679]
[This page](https://developer.apple.com/library/archive/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/TechniquesforWorkingwithVertexData/TechniquesforWorkingwithVertexData.html#//apple_ref/doc/uid/TP40008793-CH107-SW28) has a good discussion of exactly this topic in the context of OpenGL. Currently sokol_gfx uses `glSubBufferData`, which is not too shabby, but I was hoping to find access to `glMapBufferRange`.

Currently I am using triple buffering to stream dynamic data and it works just fine, but a better use of buffers in this case would be to only advance the buffer index once the current buffer fills up. With `glSubBufferData` we must advance the buffer index at the end of each frame to avoid synchronization stalls, leaving potentially large chunks of unused buffer memory at the end of the buffer.

Or `glMapBufferRange` can be used on a single large dynamic buffer like a ring buffer, with no need for double/triple buffering at all.

After a preliminary search it looks like GLES2.0 only has access to this functionality through an extension, and the rest of the APIs have equivalent functions supported.

Is this not yet implemented in sokol_gfx because it's low priority? Considered a minor optimization? Would you want help with a pull request?

You talked a little bit about something similar here: https://github.com/floooh/sokol/issues/323

**Comment by RandyGaul** [comment]
How hectic! WebGL2 here to ruin everything :)

Just out of curiosity, is it possible to see a rough sketch of what the new resource update functions might look like?

**Comment by floooh** [comment]
>  is it possible to see a rough sketch of what the new resource update functions might look like?

I have something like this in mind (especially the "CopyBufferXtoY" combinations:

https://github.com/icculus/SDL/blob/a600fdbf5b77e2531e405bd23b91a2eb4e7fb0c8/include/SDL_gpu.h#L634-L663

...probably not the "begin/end blit pass" functions if I can avoid it.
