### ISSUE TITLE
sokol_gfx.h: add integer and boolean shader uniform types

### ISSUE THREAD

**Issue by floooh** [floooh/sokol#68]
As long as supported across all backend 3D-APIs, sokol_gfx.h should also support the following uniform types:

- boolean, b2, b3, b4
- int, i2, i3, i4

**Comment by floooh** [comment]
PS: this will be tricky with the "flatten uniform buffer" feature in sokol-shdc.

Such mixed-type uniform blocks can't be flattened.

**Comment by ElArtista** [comment]
Any update on this?

**Comment by floooh** [comment]
This PR added support for integer uniform types: https://github.com/floooh/sokol/pull/606.
