### ISSUE TITLE
Valid render target formats

### ISSUE THREAD

**Issue by mhalber** [floooh/sokol#69]
Hi again,

Apologies if I am spamming these issues of late a bit, but I've been exploring sokol over past couple of days and have questions piling up :)

What I wanted to ask about this time is the valid render targets - currently only 4 render targets are valid and will pass validation. I am unsure what is the reasoning behind that? For implementing something like variance shadow maps, it would be nice to be able to bind RG32F, without additional 64 bit overhead per pixel. Is this limitation caused by GLES2 limitations or something else I am unaware of?

Additionally, is there a way to setup a framebuffer depth channel? Currently it seems like the depth channel is always set up as an renderbuffer object (in OpenGL), hence you cannot sample from it.

Thanks again for all the help!

**Comment by floooh** [comment]
Yes, in short these are all limitations incurred by various 3D APIs (mostly WebGL). The renderable pixel formats in sokol_gfx are (somewhat) safe to use across all supported platforms.

For shadow map rendering I didn't even get R32F reliably working across platforms, I had to encode/decode the shadow map depth into a normal RGBA8 pixel format for this (Oryol) demo:

http://floooh.github.io/oryol-samples/asmjs/BulletPhysicsBasic.html

For the shadow map encoding/decoding see here:

https://github.com/floooh/oryol-samples/blob/9c86213d46a1ba7f395a7f4235aab3c7fd56c071/src/BulletPhysicsBasic/shaders.shd#L1-L18

**Comment by floooh** [comment]
Closing this as duplicate for new issue: #187
