### ISSUE TITLE
Error while building GLFW example

### ISSUE THREAD

**Issue by VinnyVicious** [floooh/sokol#690]
Just tried building the example included in the README, but:

```
main.cpp:18:24: error: taking address of rvalue [-fpermissive]
   18 |     sg_setup(&(sg_desc){0});
```

Is there a way to properly deal with this? All samples use this approach, so I'm assuming a best practice of sokol?

**Comment by floooh** [comment]
This looks like you're compiling in C++ mode, not in C mode (```&(sg_desc){0}``` is valid C, but not valid C++).

Have a look at the sokol sapp samples which have the .cc file extension for possible solutions:

https://github.com/floooh/sokol-samples/tree/master/sapp

**Comment by VinnyVicious** [comment]
Thank you, I totally messed up my build file. :)
