### ISSUE TITLE
Scene graph?

### ISSUE THREAD

**Issue by VinnyVicious** [floooh/sokol#691]
Is sokol_scene_graph.h a possibility in the future? It would be awesome to have a library with the same mindset, a minimal implementation of a scene graph which nicely interfaces with sokol. In fact, the only pluggable scene graph library I could find was this: http://sgl.sourceforge.net/ (which is bulky and obsolete)

**Comment by floooh** [comment]
Probably not ;) [Scene Graphics, just say no](https://tomforsyth1000.github.io/blog.wiki.html#%5B%5BScene%20Graphs%20-%20just%20say%20no%5D%5D)

From time to time I'm thinking about a couple mid-level headers which would implement a few more of the parts required for an engine, like a material system, mesh system, animation system, and a resource loading system. But without a proper 'indie demo game project' to go with those headers and guide the design this would be a somewhat pointless undertaking.

**Comment by VinnyVicious** [comment]
That was a very interesting article, thanks for sharing that. I think that Unity/Unreal have spoiled me into thinking that the only way to build a level for a game was the scene graph.

**Comment by floooh** [comment]
TBF, the scene graph described in that blog post is a bit different from Unity (don't know how UE handles it). In 'traditional' Unity you have a tree of game objects with components attached, while the blog post is strictly about rendering. There's still a lot of overlap though (for instance the transform hierarchy of Unity objects).
