### ISSUE TITLE
pass pool exhausted!

### ISSUE THREAD

**Issue by pseregiet** [floooh/sokol#692]
Hi. the render pass object is described as something that is created up front at the start of the application, this is also how it's showed in all the learnopengl sokol port examples. However, after creating 16 passes the pool is already exhausted. So how to deal with that ? Should I create and destroy passes as I need them ? or can I modify them ? For example, in case of rendering shadows for point lights you need to do 6 passes. Right now I have a still rather conservative limit of 4 point lights and that already is too many passes.

BTW, since it's a more of a usage question and not issue with code itself, if there's a better place to ask such question please let me know.

**Comment by floooh** [comment]
Just bump the number of pass objects during sokol-gfx setup:

```c
sg_setup(&(sg_desc){
    .pass_pool_size = 1024,
    ...
});
```

> BTW, since it's a more of a usage question and not issue with code itself, if there's a better place to ask such question please let me know.

Currently not :)
