### ISSUE TITLE
Undefined Reference Errors C++ GCC-12

### ISSUE THREAD

**Issue by TheFloatingBrain** [floooh/sokol#695]
Hello, I downloaded Sokol using Conan and am trying to use it with: 
OS: Ubuntu 22.04 LTS x86_64
Compiler: `g++ (Ubuntu 12-20220319-1ubuntu1) 12.0.1 20220319 (experimental) [master r12-7719-g8ca61ad148f]`
I have a simple source file, but all the sokol functions are giving me undefined reference errors. I tried wrapping the implementation of a function in `extern "C"` in `sokol_glue.h` but to no avail, here is the source
```C++
#include <iostream>

#include <sokol_app.h>
#include <sokol_gfx.h>
#include <sokol_glue.h>


sg_pass_action initialize_sokol_graphics();
void cleanup();

int main(int argc, char** args)
{
	auto pass_action = initialize_sokol_graphics();
	cleanup();
	return 0;
}

sg_pass_action initialize_sokol_graphics()
{
	sg_desc setup_description = {
			.context = sapp_sgcontext() 
		};
	sg_setup(&setup_description);
	sg_pass_action pass_action = {
			.colors = { [0] = { .action=SG_ACTION_CLEAR, .value={1.0f, 0.0f, 0.0f, 1.0f} } }
		};
	return pass_action;
}

void cleanup() {
	sg_shutdown();
}
```

and here is the CMakeLists.txt

```CMake
cmake_minimum_required(VERSION 3.2)
project(S3O)#LANGUAGE CXX)
set(CXX_STANDARD_REQUIRED 20)

SET(GCC_COVERAGE_COMPILE_FLAGS "-g")

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()

# Sources
file(GLOB_RECURSE SOURCES Source/*.cpp)
#file(GLOB_RECURSE HEADERS include/*.h include/*.hpp)

add_executable(game ${SOURCES})
set_property(TARGET game PROPERTY CXX_STANDARD 20)
target_link_libraries(game PUBLIC ${CONAN_LIBS})
target_include_directories(game PUBLIC Include)
```

If I wrap my includes in `extern "C"` I get: 

```C++
In file included from /root/workdir/Source/Main.cpp:3:
/root/.conan/data/sokol/cci.20210304/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/sokol_app.h:1308:13: error: conflicting declaration of C function ‘void sapp_run(const sapp_desc&)’
 1308 | inline void sapp_run(const sapp_desc& desc) { return sapp_run(&desc); }
      |             ^~~~~~~~
/root/.conan/data/sokol/cci.20210304/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/sokol_app.h:1258:25: note: previous declaration ‘void sapp_run(const sapp_desc*)’
 1258 | SOKOL_APP_API_DECL void sapp_run(const sapp_desc* desc);
      |                         ^~~~~~~~
```

for all library functions. This happens if I clone directly from master as well.
Is there something special I need to do with conan config or something?

Thanks! :)

**Comment by floooh** [comment]
Looks like you need to define SOKOL_IMPL before including the sokol headers, so that the implementation gets compiled in, see:

https://github.com/floooh/sokol/blob/a902d73c9109159bd041bbe6a14d3afe54629dfa/sokol_app.h#L10-L14

In the sokol-samples this isn't obvious, because there the (common) sokol headers are compiled into a separate library:

https://github.com/floooh/sokol-samples/tree/master/libs/sokol

**Comment by TheFloatingBrain** [comment]
Thanks for the response, I did as you said, I changed the source code too the following 

```C++
#include <iostream>

#define SOKOL_IMPL
#define SOKOL_GLCORE33
#include <sokol_app.h>
#include <sokol_gfx.h>
#include <sokol_glue.h>

sg_pass_action initialize_sokol_graphics();
void cleanup();

sapp_desc sokol_main(int argc, char** args)
{
//.. the rest is the same, except for removing the return in "main"
```

But now it seems I am getting a lot of errors related to X server:
e.g
```C++
/usr/bin/ld: CMakeFiles/game.dir/Source/Main.cpp.o: in function `_sapp_x11_init_extensions()':
Main.cpp:(.text+0x11c9): undefined reference to `XQueryExtension'
/usr/bin/ld: Main.cpp:(.text+0x1206): undefined reference to `XIQueryVersion'
```

**Comment by floooh** [comment]
Yes, that's also expected. On Linux and macOS you need to link with system libraries.

See here:

https://github.com/floooh/sokol/blob/a902d73c9109159bd041bbe6a14d3afe54629dfa/sokol_app.h#L60-L79

Also don't forget the ```-pthread``` command line arg, otherwise weird crashes will happen when X11 is initialized.

**Comment by TheFloatingBrain** [comment]
Sorry for late reply, got it building and crashing with `glad`, it does not seem to know where the opengl headers are without glad

**Comment by floooh** [comment]
The sokol headers don't require a GL loader, on Linux and macOS, there's no loader needed because the required headers and libraries are provided by the system, and on Windows sokol_app.h and sokol_gfx.h come with their own integrated GL loader.
