### ISSUE TITLE
Transform Feedback

### ISSUE THREAD

**Issue by pseregiet** [floooh/sokol#698]
I'd like to request transform feedback feature in sokol. But in the meantime I'm trying to get a minimal version running for the GLCORE33 backend at least. I'd like to use it because I'm doing skeletal animations on the GPU and I think it would be really wasteful to recalculate all these matrices per vertex on every shadow pass for all the lights... 

If I understand how this feature works in openGL these are the steps:

1. Create a gl program containing a vertex shader. It has to include the out vertex attributes as if they were passed to the later stage.
2. Before calling glLinkProgram we need to call glTransformFeedbackVaryings with the names of the out vertex attributes
3. We have to bind the output buffer with glBindBuffer function with target GL_TRANSFORM_FEEDBACK_BUFFER
4. Call glBeginTransformFeedback and glEndTransformFeedback between draw calls

In order for this to work with sokol this has to be done:
For point 1 and 2 shader_desc needs to add an array of strings for the out vertex attributes. shdc-sokol needs to understand the feedback transform shaders so it can automatically fill the desc. Then in the _sg_gl_create_shader function we need to call glTransformDeedbackVaryings if the names are present. Perhaps the fragment shader can be skipped too, I'm not sure if it's required (I guess sokol right now compiles a dummy fragment shader if you don't need one just for simplicity).

For point 3: sg_bindings contains an array of vertex_buffers that's of size 8 by default. I don't know what is the usage of so many vertex_buffers. I only ever saw 2 used at the same time and the second one was always the per instance buffer. In any case, there needs to be a sg_buffer handle for the output feedback transform buffer. I think it would be easier to add new member in the sg_bindings for that instead of using the vertex_buffers array as that is used to setup the vertex attributes which is not needed for the output buffers as far as I understand it.

For point 4: A non-issue, could just be wrapped to something like sg_begin_feedback / sg_end_feedback.

I hope you can comment on this and suggests anything if I said something wrong or if you have better ideas. I've found some older issue where you said you already had transform feedback working but you removed it as it would be hard to get working cross all APIs. I understand your main goal of sokol is working with all different APIs but I use it as a nice (great in fact !) openGL wrapper so I'd be content with just a minimal openGL version (at least for now). Thanks

**Comment by floooh** [comment]
I had tinkered with transform feedback back in the Oryol days (here's an old demo, which doesn't even appear to work anymore: https://floooh.github.io/oryol-sticky-tests/VertexCapture.html).

I had decided back then that it's not worth the hassle to pursue this further, if I remember correctly, the main reason was that it is hard to wrap the feature under a common API across all 3D backends (D3D11 has a similar "Stream Output Stage" https://docs.microsoft.com/en-us/windows/win32/direct3d11/d3d10-graphics-programming-guide-output-stream-stage, while Metal doesn't have this as explicit feature, but apparently allows to write back into a vertex buffer from a shader).

In any case, I think the main blocker was that SPIRVCross cannot abstract those backend differences away.

It would probably make more sense to invest the time into "proper" compute shader support.
