### ISSUE TITLE
building against mac sdk 11.3 fails

### ISSUE THREAD

**Issue by billzez** [floooh/sokol#705]
Building with `zig build-exe` target aarch64-macos:

```
sokol-zig/src/sokol/c/sokol_app.h:3557:43: error: property 'maximumFramesPerSecond' not found on object of type 'NSScreen *'
```

I'm not particularly familiar with objective-c, but I believe in the following code:

```
        #if (__MAC_OS_X_VERSION_MAX_ALLOWED >= 120000)
        if (@available(macOS 12.0, *)) {
            max_fps = NSScreen.mainScreen.maximumFramesPerSecond;
        }
        #endif
```

should use a runtime getter:

```
max_fps = [NSScreen.mainScreen maximumFramesPerSecond];
```

**Comment by floooh** [comment]
Hmm, I don't know either why the method call is different from the property access in this case, but if it fixes the issue then so be it ;)

**Comment by floooh** [comment]
PS: I wonder if the build.zig script doesn't properly set up the ```-mmacosx-version-min``` flag, for instance in the sokol-samples cmake files I need to define the minimal supported macOS version line this:

```cmake
set(CMAKE_OSX_DEPLOYMENT_TARGET "10.13" CACHE STRING "")
```
...which is explained here:

https://vector-of-bool.github.io/docs/vscode-cmake-tools/debugging.html

**Comment by billzez** [comment]
I believe your intended goal here is that this piece of code is always compiled into the binary, but only executes on macos 12+.

If you uses a static getter, the compiler cannot compile it with the 11.3 sdk, because maximumFramesPerSecond is not part of NSScreen.

If you use a dynamic getter, the compiled code is actually a function call (to a weak linked function), gets built into the binary, but is only called on macos 12+.

The other option would be to only compile this code for the 12+ sdk/os.  In that case, `__MAC_OS_X_VERSION_MIN_REQUIRED` should be used.  Then setting `CMAKE_OSX_DEPLOYMENT_TARGET` would have an effect.

This is my understanding at least.  I believe what you have now is ideal.
