### ISSUE TITLE
On Android, make the native activity available before sokol_main is called

### ISSUE THREAD

**Issue by neslib** [floooh/sokol#708]
I am writing a Sokol language binding for Delphi and it works great on Windows, macOS and iOS.

However, for Android, I need to know the native activity at the moment `sokol_main` is called, but `ANativeActivity_onCreate` sets the native activity *after* `sokol_main` returns. I see 2 solutions for this:

1. Set the native activity *before* `sokol_main` is called, so I can use `sapp_android_get_native_activity` to retrieve it. However, the application is not valid yet at this point, so `sapp_android_get_native_activity` currently raises an assertion.

2. Pass the native activity as an extra parameter to the `sokol_main` function. However, this breaks compatibility with existing code.

**Comment by floooh** [comment]
Hi, apologies for late reply. I'm actually not all that familiar with the Android backend, but I think it should be possible to move the line:

```
_sapp.android.activity = activity;
```
...before the call to sokol_main() and remove the assert from sapp_android_get_native_activity().

I agree that it would be better to pass some sort of struct into sokol_main() which has additional information (not just the cmdline args), but it's not worth it yet to break compatibility for this. I'll try to keep it in mind for the next compatibility breaking update.

Would you like to provide a PR with the 'simple' fix?

**Comment by neslib** [comment]
Done. And thanks for this amazing library!
I'm almost done with the Delphi language binding and this was the only issue standing in the way.

**Comment by floooh** [comment]
Closing this as the PR is merged.
