### ISSUE TITLE
[sokol_app.h] GLES2 on linux

### ISSUE THREAD

**Issue by darltrash** [floooh/sokol#711]
Is it possible to have a GLES2 app in linux through sokol_app.h? 
![imagen](https://user-images.githubusercontent.com/38925212/187543776-cdd7d532-a5a5-44bc-b46d-d096fe59345d.png)
So far I only got this

**Comment by floooh** [comment]
No, the selection of backend APIs is limited by platform:

- Windows: GL3.2 or D3D11
- macOS: GL3.2 or Metal
- Linux: GL3.2 only
- Android, Web: GLES2 or GLES3
- iOS: GLES2, GLES3 or Metal

In sokol_gfx.h the only place where this matters is where the GL headers are included, which you could avoid by defining SOKOL_EXTERNAL_GL_LOADER: https://github.com/floooh/sokol/blob/01eeb35658fee9b6fe2e31145925fbd5e22faf47/sokol_gfx.h#L2765-L2804

...but in sokol_app.h the X11/GLX window system glue doesn't know how to setup a GLES2 context (there's an extension for this https://registry.khronos.org/OpenGL/extensions/EXT/GLX_EXT_create_context_es2_profile.txt, but I haven't tinkered with this yet).

**Comment by billzez** [comment]
This pull request adds GLES support:

https://github.com/floooh/sokol/pull/716

**Comment by floooh** [comment]
Closing this ticket as #716 has been merged.
