### ISSUE TITLE
GL_MAX_VERTEX_UNIFORM_VECTORS is not included per default in GL3.3

### ISSUE THREAD

**Issue by jwurzer** [floooh/sokol#714]
When I use Sokol with GL3.3 backend and activated macro SOKOL_EXTERNAL_GL_LOADER in combination with Glad Loader I get an compilation error. The macro GL_MAX_VERTEX_UNIFORM_VECTORS can't be found. The OpenGL header files for OpenGL 3.3 Core are generated with Glad (https://glad.dav1d.de/). Glad does not include the macro GL_MAX_VERTEX_UNIFORM_VECTORS for GL3.3 Core. Only if I added the extension GL_ARB_ES2_compatibility the macro GL_MAX_VERTEX_UNIFORM_VECTORS is available. Without the extension the macro is only included in >= OpenGL 4.1.

Looks like per OpenGL specification the macro GL_MAX_VERTEX_UNIFORM_VECTORS is not included in pure GL3.3 core. Maybe the GL3.3 backend should not use GL_MAX_VERTEX_UNIFORM_VECTORS or the README should include the GL_ARB_ES2_compatibility extension for GL3.3.

**Comment by floooh** [comment]
Hmm ok, strange that this only pops up now. The closest alternative seems to be GL_MAX_VERTEX_UNIFORM_COMPONENTS, but that's not the same thing. The value isn't used by sokol_gfx.h itself, only as return value of sg_query_limits() in the sg_limits struct, so it's not super critical.

I need to check if GL_MAX_VERTEX_UNIFORM_COMPONENTS and GL_MAX_VERTEX_UNIFORM_VECTORS can be converted into each other, if yes, that's probably the best solution.

**Comment by floooh** [comment]
I was running into the same problem just now. I fixed this in https://github.com/floooh/sokol/commit/bfaccb35836005d70cd38eb3036774e1103795f5 with a breaking change (this branch will introduce other breaking changes anyway).

This issue should close automatically when that branch is merged.
