### ISSUE TITLE
Stereo sound doesn't work on OSX

### ISSUE THREAD

**Issue by nesbox** [floooh/sokol#72]
`ChannelsPerFrame` is always `1` independently of `_saudio.num_channels` here https://github.com/floooh/sokol/blob/3eb4db239d4b607b17deeb51c51d25f8c3456e54/sokol_audio.h#L494

Could you please fix it, I'm going to use Sokol with [TIC-80](https://github.com/nesbox/TIC-80).
Thank you.

**Comment by floooh** [comment]
Yes, sokol_audio.h is very work in progress. I'll first finish the WASAPI implementation on Windows, then I'll look into stereo output (it's hardcoded to single-channel on all platforms currently).

**Comment by nesbox** [comment]
thank you, all is working fine
