### ISSUE TITLE
Add function to open URL in browser

### ISSUE THREAD

**Issue by tomasandrle** [floooh/sokol#738]
A portable way for opening web links would be handy.

On Mac it usually looks like this:

```
[[NSWorkspace sharedWorkspace] openURL: [NSURL URLWithString: s]];
```

Windows:

```
ShellExecute(NULL, "open", url.c_str(), NULL, NULL, SW_SHOWNORMAL);
```

etc.

**Comment by floooh** [comment]
Not a fan :) This would be relatively easy to put into a separate library since it doesn't rely on sokol_app.h internals (and even then it would probably be better to expose the required platform-specific internals, similar to ```sapp_win32_get_hwnd()```.
