### ISSUE TITLE
sokol_fontstash to sokol_sgl offscreen pass

### ISSUE THREAD

**Issue by Larpon** [floooh/sokol#749]
Hi, hope you're doing good!

I've been trying to get fonts to render to an offscreen pass texture using `sokol-gl`, `sokol_fontstash.h` mixed with the
setup used in [`sgl-context-sapp`](https://github.com/floooh/sokol-samples/blob/1cc53b53/sapp/sgl-context-sapp.c#L70-L86).

I like this approach since I have been able to draw both shapes and textures to an offscreen texture, which suits my needs in a 2D/2.5D project really nice, but when trying to mix-in font rendering I'm hit with:
```
sg_apply_pipeline: pipeline depth pixel_format doesn't match pass depth attachment pixel format
^^^^  SOKOL-GFX VALIDATION FAILED, TERMINATING ^^^^
```

My approach to try and solve this has been, [like previous attempts](https://github.com/floooh/sokol/issues/703), to simply comment out [the validation check that causes the error](https://github.com/floooh/sokol/blob/67b554b903f77b27c6da8289477a8a127e86324f/sokol_gfx.h#L14711) (.. and yes, I know: *wrong* "fix" :sweat_smile: ). However it allowed me to end up with an... *erhm* "solution" :grimacing: :

![image](https://user-images.githubusercontent.com/768942/203042979-5d92e874-de37-46b8-ae7c-ef6153b1568e.png)
![image](https://user-images.githubusercontent.com/768942/203043150-25c540d6-97c1-4c56-a422-eb59f6c7797a.png)

The screenshot above is from an attempt of simply expanding on the `sgl-context-sapp` example.
* I'm rendering an image to the offline texture (works, except for the y-flip)
* Then a quad (works)
* ... and then adding the [fontstash-sapp](https://github.com/floooh/sokol-samples/blob/master/sapp/fontstash-sapp.c) example on top (yields the assertion error above)

As you can see there is issues with the texture flipping on the font on top - but my real issue here is understanding how I can, correctly, render fonts to the same offscreen texture - like it's possible with images and primitives via `sokol-gl`?

I'm not very experienced when it comes to low-level graphics programming like this - so understanding when to use a specific pipeline/context/format is still a struggle for me - but I hope I'm making, somekind of, sense :smile:

(I hope it's alright that I'm posting here in the open since I think it might benefit others on my level)

**Comment by floooh** [comment]
PS: better solution: call sfons_create() after creating and setting the sokol-gl offscreen context. This should create the fonststash pipeline in the correct format for the offscreen render pass (untested, but should work).

E.g. in the sgl-context-sapp sample you have a call to ```sgl_make_context```, just add a call to ```sgl_set_context``` and ```sfons_create()``` afterwards:

```c
    state.offscreen.sgl_ctx = sgl_make_context(&(sgl_context_desc_t){
        .max_vertices = 8,
        .max_commands = 4,
        .color_format = OFFSCREEN_PIXELFORMAT,
        .depth_format = SG_PIXELFORMAT_NONE,
        .sample_count = OFFSCREEN_SAMPLECOUNT,
    });
    sgl_set_context(state.offscreen.sgl_ctx);

    // move the call to sfons_create() down here after sgl_set_context()
    FONScontext* fons_context = sfons_create(&(sfons_desc_t){
        .width = atlas_dim,
        .height = atlas_dim,
    });        
```

...sokol_fontstash.h should still be a bit more flexible (for instance accepting a an optional sokol-gl context handle in sfons_desc_t), but as a workaround this should hopefully work.

**Comment by Larpon** [comment]
We have a winner :partying_face: 
After flipping the quad with the texture in the render - it works like expected
![image](https://user-images.githubusercontent.com/768942/203304763-5ae23f12-0f86-4deb-ac1a-33d568d8b9aa.png)
