### ISSUE TITLE
sokol_app: DPI scale is 0 on Linux

### ISSUE THREAD

**Issue by samrat** [floooh/sokol#755]
On Linux, I get 0 when I call `sapp_dpi_scale`. It seems that `XResourceManagerString` [here](https://github.com/floooh/sokol/blob/master/sokol_app.h#L10280) returns null. 

This happens both with and without an external display(running Ubuntu 22.04 with i3). If there is any other information I can provide, please let me know.

Would it maybe be a good idea to have a default value of `1.0` in case it is not possible to query the DPI scale?

**Comment by floooh** [comment]
Ouch, yes, dpi_scale should be set to 1.0 if anything goes wrong querying the value. I'll commit a quick fix...

**Comment by floooh** [comment]
Ok, I added a fallback, let me know if it works.

Also, what's the output of ```xrdb -query``` on your setup? E.g. on my Ubuntu laptop it prints:

```
sokol ➤ xrdb -query                                                                                                      git:master
*customization:	-color
Xcursor.size:	24
Xcursor.theme:	Adwaita
Xft.antialias:	1
Xft.dpi:	96
Xft.hinting:	1
Xft.hintstyle:	hintfull
Xft.rgba:	rgb
```
