### ISSUE TITLE
[Question] blending textures with sokol_gl

### ISSUE THREAD

**Issue by Larpon** [floooh/sokol#756]
I've tried searching for an example of how to achieve blending of textures drawn via `sgl_texture()` with sokol_gl.h but I can't find any.

Is it possible to blend a texture over what's already in the framebuffer?
```c
sg_image img = sg_make_image(...);
...
sgl_texture(img);
// blend against what's already drawn, like setting an "opacity" value to e.g.: 0.5f 
```
... or maybe I am missing some crucial point/limitation? :sweat_smile: 

(I initially thought that calling `sgl_c4b(255,255,255,127)` before plotting the vertices would do it - but that's obviously not the case)

**Comment by floooh** [comment]
Check out the new debugtext-layers sample, this uses sokol-gl rendering with alpha-blending:

https://floooh.github.io/sokol-html5/debugtext-layers-sapp.html

The trick is to create an sgl_pipeline_t object (which is a wrapper around sokol-gfx pipeline object) with alpha-blending configured:

https://github.com/floooh/sokol-samples/blob/cde553da075299fcbc592d8a69809e0ab96ffec8/sapp/debugtext-layers-sapp.c#L34-L44

...and then use sgl_load_pipeline() to use this pipeline object:

https://github.com/floooh/sokol-samples/blob/cde553da075299fcbc592d8a69809e0ab96ffec8/sapp/debugtext-layers-sapp.c#L61-L78

(sokol-gl has a 'pipeline-stack' which works much the same as the traditional GL matrix stack):

https://github.com/floooh/sokol/blob/97dc77d8f5440429aabcad1963a21130cae759cc/util/sokol_gl.h#L792-L796

The 'opacity' is set in the alpha channel of the color register (in this case: 160, where 0 means 'fully transparent' and 255 'fully opaque'):

https://github.com/floooh/sokol-samples/blob/cde553da075299fcbc592d8a69809e0ab96ffec8/sapp/debugtext-layers-sapp.c#L68-L73

**Comment by floooh** [comment]
(I agree that this stuff is too hidden and in an unrelated sample, I should probably create a dedicate 'sokol-gl-features' sample)

**Comment by Larpon** [comment]
Ah, I didn't look hard enough, thanks a lot!
