### ISSUE TITLE
sokol_gfx.h - Disable `gl*Ext` with `SOKOL_GLES2`

### ISSUE THREAD

**Issue by eloraiby** [floooh/sokol#76]
These extensions do not work on all GLES2 implementations. On some platforms (tested with nVidia, intel - ubuntu) there is no `glVertexAttribDivisorEXT`, `glDrawArraysInstancedEXT` or `glDrawElementsInstancedEXT`. This causes issues both at runtime and on compilation.

```
#ifdef SOKOL_GLES2
#define glVertexAttribDivisor(index, divisor) glVertexAttribDivisorEXT(index, divisor)
#define glDrawArraysInstanced(mode, first, count, instancecount) glDrawArraysInstancedEXT(mode, first, count, instancecount)
#define glDrawElementsInstanced(mode, count, type, indices, instancecount) glDrawElementsInstancedEXT(mode, count, type, indices, instancecount)
#endif
```

I can make a pull request, if need be.

**Comment by floooh** [comment]
Hmm I see. I guess this needs an ```#ifdef GL_ANGLE_instanced_array``` around it(?)

A PR would be great, I think I don't have a config were I can test this.

Thanks!

**Comment by eloraiby** [comment]
@floooh please review the pull request #77

**Comment by eloraiby** [comment]
Pr #77 is merged

**Comment by floooh** [comment]
btw I tested with emscripten and it works fine
