### ISSUE TITLE
Impossible to set swap_interval to 0

### ISSUE THREAD

**Issue by fafok29** [floooh/sokol#768]
https://github.com/floooh/sokol/blob/21c9d47c85324104b0a5eeae3e017bd3551df7bb/sokol_app.h#L2895

Basically, it is not possible to specify swap_interval as 0 because of _sapp_def, even if I explicitly stated swap_interval eq to 0 in sapp_desc.

**Comment by floooh** [comment]
Yes, there's a couple of similar issues already, long story short, the sokol_app.h frame model doesn't easily allow to switch off vsync, and the ```swap_interval``` setting should actually be a ```preferred_framerate```, because defining a swap interval isn't very helpful with different monitor refresh rates.

**Comment by floooh** [comment]
Here's the original ticket: https://github.com/floooh/sokol/issues/292
