### ISSUE TITLE
sokol_audio.h: Accept signed 16 and 32 bit samples besides float 32 ones

### ISSUE THREAD

**Issue by nikneym** [floooh/sokol#781]
This would allow one to directly push 16 or 32 bits PCM data to the stream. Audio backend can be set to only accept one type of these sample types too.

**Comment by floooh** [comment]
I considered this but it would complicate both the implementation and the API (e.g. there would need to be 3 versions of saudio_push() for float, uint16_t and uint32_t, and 3 variants of the streaming callback).

And if an audio backend doesn't support all 3 sample types, the necessary conversion would need to happen on the CPU anyway. It's better to do this outside (like I'm doing here in the modplay sample: https://github.com/floooh/sokol-samples/blob/9eb58faeff2c60dc0d625bdad8eb9d5ea5341cff/sapp/modplay-sapp.c#L43-L45)
