### ISSUE TITLE
sokol_log: error when compiling with emscripten

### ISSUE THREAD

**Issue by tanis2000** [floooh/sokol#791]
I recently upgraded to the latest version of sokol_gfx and I have included sokol_log as explained in the changelog. It works fine on Windows and macOS but I am getting the following error when compiling with emscripten:

```
In file included from /Users/tanis/Documents/binocle-c/src/binocle/core/binocle_sokol.c:17:
/Users/tanis/Documents/binocle-c/src/deps/sokol/sokol_log.h:240:1: error: expected function body after function declarator
EM_JS(void, slog_js_log, (uint32_t level, const char* c_str), {
^
/Users/tanis/Documents/emsdk/upstream/emscripten/cache/sysroot/include/emscripten/em_js.h:68:39: note: expanded from macro 'EM_JS'
#define EM_JS(ret, name, params, ...) _EM_JS(ret, name, name, params, #__VA_ARGS__)
                                      ^
/Users/tanis/Documents/emsdk/upstream/emscripten/cache/sysroot/include/emscripten/em_js.h:62:21: note: expanded from macro '_EM_JS'
  ret c_name params EM_IMPORT(js_name);                                                            \
                    ^
In file included from /Users/tanis/Documents/binocle-c/src/binocle/core/binocle_sokol.c:17:
/Users/tanis/Documents/binocle-c/src/deps/sokol/sokol_log.h:240:1: error: unknown type name 'EMSCRIPTEN_KEEPALIVE'
/Users/tanis/Documents/emsdk/upstream/emscripten/cache/sysroot/include/emscripten/em_js.h:68:39: note: expanded from macro 'EM_JS'
#define EM_JS(ret, name, params, ...) _EM_JS(ret, name, name, params, #__VA_ARGS__)
                                      ^
/Users/tanis/Documents/emsdk/upstream/emscripten/cache/sysroot/include/emscripten/em_js.h:63:3: note: expanded from macro '_EM_JS'
  EMSCRIPTEN_KEEPALIVE                                                                             \
  ^
In file included from /Users/tanis/Documents/binocle-c/src/binocle/core/binocle_sokol.c:17:
/Users/tanis/Documents/binocle-c/src/deps/sokol/sokol_log.h:328:9: error: call to undeclared function 'slog_js_log'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        slog_js_log(log_level, line_buf);
        ^
3 errors generated.
```

The content of binocle_sokol.c is just the following:

```c
#define SOKOL_IMPL
#if defined(BINOCLE_GL)
  #if defined(__EMSCRIPTEN__)
    #define GL_GLEXT_PROTOTYPES
    #include <GLES2/gl2.h>
    #include <GLES2/gl2ext.h>
    #define SOKOL_GLES2
  #elif defined(__IPHONEOS__) || defined(__ANDROID__)
    #define SOKOL_GLES3
  #else
    #define SOKOL_GLCORE33
  #endif
#elif defined(BINOCLE_METAL)
  #define SOKOL_METAL
#endif
#include "sokol_log.h"
#include "sokol_gfx.h"

GLuint binocle_sokol_tex_id(sg_image img_id) {
  SOKOL_ASSERT(img_id.id != SG_INVALID_ID);
  _sg_image_t* img = _sg_lookup_image(&_sg.pools, img_id.id);
  SOKOL_ASSERT(img);
  SOKOL_ASSERT(img->gl.target == GL_TEXTURE_2D);
  SOKOL_ASSERT(0 != img->gl.tex[img->cmn.active_slot]);
  return img->gl.tex[img->cmn.active_slot];
}
```

I am using emscripten 3.1.22 if that can help.

**Comment by tanis2000** [comment]
I have fixed this issue by adding this include to binocle_sokol.c:

```c
#include <emscripten/emscripten.h>
```

I am not entirely sure this is the right way to go, though :)

**Comment by floooh** [comment]
Hmm that include should actually be in sokol_log.h... let me check.

**Comment by floooh** [comment]
It should be taken care of by this include:

https://github.com/floooh/sokol/blob/154ac78f09bf0d8f382eb036da2ab91110cdaef0/sokol_log.h#L195-L197

I remember that I forgot this in an earlier version of sokol_log.h, because I only added this later (on 06-Feb, but that's already 10 days ago and was not yet in the master branch).

https://github.com/floooh/sokol/commit/4ef1cda4ed642fef15587f56028f4a4663261ea3

Can you check if you that include?

Normally the compile checks in here should make sure that there is no "header leakage", this is compiled for all platforms:

https://github.com/floooh/sokol/blob/master/tests/compile/

...e.g. here's standalone sokol_log.c implementation file is here:

https://github.com/floooh/sokol/blob/master/tests/compile/sokol_log.c

**Comment by tanis2000** [comment]
yes, the include for em_js.h is there, but it looks like that's not enough for some reason. I replaced it with emscripten.h and it works correctly. Are you using the same emscripten version?

**Comment by floooh** [comment]
I'm on emsdk version ```3.1.31```

**Comment by floooh** [comment]
PPS: but note that the sokol headers now also require the relatively new ```EM_JS_DEPS()``` macro which was added around that time too... so if you are on an older Emscripten SDK version that might also be a problem...

**Comment by floooh** [comment]
Ok, I changed the include to <emscripten/emscripten.h> can you check if that works for you? If not please re-open and we need to investigate further :)

In any case: thanks for reporting the issue!

**Comment by tanis2000** [comment]
Yes, that seems to be the issue. I removed the include I added before and updated to emsdk 3.1.31 and it works fine ;)

**Comment by floooh** [comment]
Ok, I changed the include anyway :) I also just checked, and I'm including emscripten.h in all other places, instead of the lower level headers, so it's probably a good idea anyway.
