### ISSUE TITLE
WASM broken in some old devices

### ISSUE THREAD

**Issue by Alan-FGR** [floooh/sokol#793]
Hello.
I noticed that at some point WebGL stopped working on some older devices. For instance, the demos used to work flawlessly but these days they don't work on an older iPad Air 2 as well as a Sony Xperia G3 Android device I have here. The page stays black forever.
I'm not sure how to collect information that would be useful for debugging. Maybe a webpage? Other WebGL1 stuff works, like Oryol and Magnum samples for example.
I was hoping you guys could have an idea of what changed recently that would justify WebGL being broken in those devices.
Thank you :)

**Comment by floooh** [comment]
Hmm, nothing comes to mind, but I haven't paid much attention to WebGL1 compatibility recently to be honest.

I have an old Nexus tablet here which I will check on, but I need to load it first, and I'm not sure if the Android version is old enough to not yet have WebGL2 support.

A snippet of any errors from the Javascript console would be useful, but that's a bit of a hassle:

For the Android device, first open regular Chrome on a computer, and go to 

```chrome://inspect/```

Now connect your Android device via USB and it should show up in the device list like here:

<img width="537" alt="Screenshot 2023-02-16 at 18 20 51" src="https://user-images.githubusercontent.com/1699414/219440667-e9c0c6ec-c9fd-4078-8c71-5caf9f112093.png">

...and next when you open Chrome and navigate to one of the sokol samples it should show this:

<img width="745" alt="Screenshot 2023-02-16 at 18 23 40" src="https://user-images.githubusercontent.com/1699414/219441043-86638dee-11e8-4d68-a2c7-b97063daa542.png">

...then you click on "inspect" and it opens the browser devtools, one of the tabs is the "Console", and hopefully there will be errors logged which provide more info:

<img width="916" alt="Screenshot 2023-02-16 at 18 24 25" src="https://user-images.githubusercontent.com/1699414/219441342-c855011d-9845-4366-949b-c45a3085b1dc.png">

**Comment by floooh** [comment]
...iOS there's a similar procedure for desktop Safari under the "Develop" menu (which needs to be activated somewhere in the Safari settings).

**Comment by floooh** [comment]
FWIW, on my iPad Mini4, which also doesn't support WebGL2 yet, the sokol samples still work, except for those that require WebGL2 (like https://floooh.github.io/sokol-html5/mrt-sapp.html). But this sample then doesn't have a black screen, but instead renders a red screen (which is the "WebGL1 fallback").

This iPad Mini4 has iOS version 15.4.1 though, so relatively recent, even though the device is fairly old (around 2015).

...so it doesn't seem to be a WebGL2 vs WebGL1 thing at least...

**Comment by floooh** [comment]
...iOS simulator also isn't very helpful, I can go back to the iPhone4S, but only with a current operating system:
<img width="437" alt="Screenshot 2023-02-16 at 18 36 06" src="https://user-images.githubusercontent.com/1699414/219444045-6b18bc27-d237-463d-b7e8-52b4b6583b8d.png">

**Comment by floooh** [comment]
Ok! I can reproduce on my old Nexus tablet. I'll have a closer look tomorrow! No promises though about a fix.

Apart from that: do you think it's to soon to drop support for such older devices? (e.g. should I reconsider the plan to drop WebGL1 support?).

**Comment by Alan-FGR** [comment]
Hello again. Thank you so much for this!

For my purposes WebGL1 is very desirable since my plan is to make a game that people can play directly from the webpage on both desktops and mobiles and it's not graphically intensive. The idea is to also use HTML elements for the UI.
That said, I guess that scenario is not very representative of your user base, and to be honest I could just use GLES2 and if I ever need to ship actual apps I could use ANGLE which for my purposes should suffice (and RmlUi because people should stop embedding Chromium (and Nodejs) in everything).
Other than that Sokol always worked wonderfully and I really like the code quality. You did a fantastic job :)

**Comment by floooh** [comment]
Fuuuu....ck...

I updated Chrome (to version 95.0.4638.74) on my Nexus tablet (because the link from desktop Chrome didn't work), and now the samples all work meaning I can no longer reproduce the issue....

So it's not related to old devices or old Android versions, but to old browser versions...

Btw the other config details are:

Android 6.0.1; Nexus 7 (I think it's the 2013 version, not 2012, but not entirely sure).

**Comment by Alan-FGR** [comment]
Yes, I can confirm the problem on Android on my end was also the browser. The iPad still doesn't like it and there are no updates available in the Apple Store. I'm not an Apple user so I don't even know how to check the version, it's overcomplicated; I've tried the browser menu and the settings (buried in the system settings) to no avail. The report by https://webglreport.com/ is not looking good though, so I guess it's an edge case, idk. I was also checking this report: https://www.khronos.org/blog/webgl-2-achieves-pervasive-support-from-all-major-web-browsers and I'd say go for WebGL2 tbh, since WebGL1 is just a source of headaches apparently.

Also, at some point bgfx also stopped working 😆: http://alangamedev.com/bgfx/example-01-cubesRelease.html - the old metaballs in the example docs still work fine.

If you want help fixing it in the iPad please lemme know and I'll happily do what I can. I have an Apple laptop gathering dust here which I could use to retrieve some debugging info from Safari afaik. Otherwise, if that doesn't matter to you then I think this can be closed.

**Comment by floooh** [comment]
Thanks for the reply. It could also be WASM related btw, but just a hunch.

It would be great if you could try this to diagnose the problem on iOS:

- On a Mac, open Safari and go to "Safari => Setting", in the panel that open go to the "Advanced" tab. There should be a "Show Develop menu in menu bar" checkbox, check that.
- On the iPad, something similar needs to be enabled: Go to the system settings, find Safari => Advanced => Web Inspector" and enable that...
- Connect the iPad to the Mac.
- Open Safari on both Mac and iPad.
- When you go to the new Develop menu in desktop Safari, your iPad should be listed now, select this menupoint and a "Web Inspector" window should open => select the "Console" tab.
- Now back on the iPad select one of the sokol demos which creates a black screen...

...and hopefully there will be helpful error messages listed in the Web Inspector console tab as a result. Post those here :)

**Comment by Alan-FGR** [comment]
Sorry the delay, here's the error:

> [Error] failed to asynchronously prepare wasm: CompileError: WebAssembly.Module doesn't parse at byte 239: invalid opcode 193, in function at index 22
	printErr (triangle-sapp.html:74)
	(anonymous function) (triangle-sapp.js:54:375)
	promiseReactionJob
[Error] Aborted(CompileError: WebAssembly.Module doesn't parse at byte 239: invalid opcode 193, in function at index 22)
	printErr (triangle-sapp.html:74)
	z (triangle-sapp.js:9:136)
	(anonymous function) (triangle-sapp.js:54:422)
	promiseReactionJob
[Error] Unhandled Promise Rejection: RuntimeError: Aborted(CompileError: WebAssembly.Module doesn't parse at byte 239: invalid opcode 193, in function at index 22). Build with -sASSERTIONS for more info. (evaluating 'new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.")')
	z (triangle-sapp.js:9:226)
	(anonymous function) (triangle-sapp.js:54:422)
	promiseReactionJob

So apparently the error is indeed emscripten generating some opcodes that Safari can't parse. At least judging by that message, I didn't investigate further.
It's weird though because this iPad still seems to be pretty decent, I've enabled WebGL2 in the advanced settings and it runs everything smoothly, even the fluid simulations from Magnum and whatnot.

**Comment by Alan-FGR** [comment]
Upon initial investigation apparently these are related to SIMD:
192: i64.extend8_s
193: i64.extend16_s

**Comment by floooh** [comment]
Aha, I had a hunch that it could be WASM related.

I need to investigate this a bit (I think the instructions are actually ```192 = 0xC0: i32.extend_8s``` and ```193 = 0xC1: i32.extend_16s```, but those are listed in the spec as regular 'numeric instructions', not as part of the SIMD extension (see: https://webassembly.github.io/spec/core/binary/instructions.html#numeric-instructions)...

Still weird though, because I would think these are 'bread-and-butter' instructions. I'll ask around on the Emscripten discord if this issue looks familiar to anyone.

**Comment by floooh** [comment]
Ok, basically:
<img width="939" alt="Screenshot 2023-02-23 at 18 41 22" src="https://user-images.githubusercontent.com/1699414/220987108-8625ee5a-f9f7-4e17-832e-22988e9d6170.png">

(link: https://discord.com/channels/453584038356058112/590215642444202044/1078369484139671632)

These are actually core instructions but where added either right before WASM 1.0 or some time after in context of threading support...

But I don't think there's any way to build without those instructions except going back to a very old Emscripten version or maybe using an asm.js fallback (if asm.js output even still works).

I'll close the ticket, since there's not much that can be done by the sokol headers.
