### ISSUE TITLE
pacman.c example uploaded on itch.io don't receive keypresses

### ISSUE THREAD

**Issue by mosmetro** [floooh/sokol#795]
It is works ok on local http server, however.

**Comment by floooh** [comment]
Do you have a link for me to test?

**Comment by mosmetro** [comment]
Sure.
https://nsobject.itch.io/wgpu?secret=i0g8XFqheSXlE5EZnQw0o7O5Qg0

**Comment by floooh** [comment]
That's not a sokol issue, the problem is that the 'outer webpage' eats the input events before they get to the game's canvas element (note how the whole webpage is scrolled when you press the arrow keys).

Why are you trying to put the game on itchio btw?

**Comment by mosmetro** [comment]
Ok.

> Why are you trying to put the game on itchio btw?

Because why not? :)

**Comment by mosmetro** [comment]
I set `<body>` in shell.html file to:
`<body onclick=window.focus() onload=window.focus()>`
Now it works fine. Thanks for the advice.
