### ISSUE TITLE
sokol_gfx.h: Bad depth value for SG_IMAGETYPE_ARRAY with mipmaps under OpenGL

### ISSUE THREAD

**Issue by thennequin** [floooh/sokol#81]
Hi,
I found a bug during the creation of an array image, when we use mipmaps, you reduce the depth size by the mip index, its make sense for 3D texture, but seems incorrect for texture array.
I see the bug under OpenGL, but I doesn't check for others API.

https://github.com/floooh/sokol/blob/7a8076a1dcb150fcf13e58484fff9f1dbdebd2c1/sokol_gfx.h#L3010

Here my solution for solving the previous line:
```cpp
int mip_depth = img->depth;
if (SG_IMAGETYPE_3D == img->type) {
	mip_depth = mip_depth >> mip_index;
}
if (mip_depth == 0) {
	mip_depth = 1;
}
```

**Comment by floooh** [comment]
Yes, this looks like a bug. Applying your fix now. Thanks!

**Comment by thennequin** [comment]
Ok, thanks for the Applying ;)
And good to know for D3D11 and metal.
