### ISSUE TITLE
Create Sokol port of nanovg

### ISSUE THREAD

**Issue by samrat** [floooh/sokol#819]
I'm trying to use nanovg(with [MetalNanoVG](https://github.com/ollix/MetalNanoVG)) in a project that also uses sokol-gfx(and sokol_gl). This doesn't work well because, if I understand correctly, both libraries create and render a framebuffer. I see a flickering screen.

I think it would be useful to create a Sokol port of nanovg which uses sokol-gfx(or maybe sokol-gl) calls to render nanovg shapes.

Also, I found this old tweet from @floooh : https://mobile.twitter.com/FlohOfWoe/status/505108580329349120 . Seems like something like this was part of Oryol.

**Comment by darkuranium** [comment]
Pretty sure this is a duplicate of https://github.com/floooh/sokol/issues/633?

**Comment by samrat** [comment]
Yup, closing this one.
