### ISSUE TITLE
Question: How do I use Android lifecycle callbacks?

### ISSUE THREAD

**Issue by 20kano** [floooh/sokol#823]
How can I use onPause() and onResume() in Android?
Are there any examples?

**Comment by floooh** [comment]
I haven't used it so far, but the pause and resume lifecycle events are mapped to the sokol-app events `SAPP_EVENTTYPE_RESUMED` and `SAPP_EVENTTYPE_SUSPENDED` (see here: https://github.com/floooh/sokol/blob/7373dda48c5e62953cc7ec942da90fc6a25989fa/sokol_app.h#L8165-L8174)

...so you can listen for those events in the sokol-app event callback (like regular input events).
