### ISSUE TITLE
Uncaught ReferenceError ReferenceError: __sapp_html5_get_ask_leave_site is not defined 

### ISSUE THREAD

**Issue by FunnyPixel** [floooh/sokol#827]
Hi.
In the code I see you got this function:

`  _sapp_html5_get_ask_leave_site()`

But then you call it with double underscore:

`  __sapp_html5_get_ask_leave_site()`

Can that be the problem?

**Comment by floooh** [comment]
That should be correct. What exactly is the problem you're seeing?

**Comment by FunnyPixel** [comment]
In firefox this error message is thrown in the console:

`Uncaught ReferenceError ReferenceError: __sapp_html5_get_ask_leave_site is not defined`

I see the double __ underscore in the code where the function call takes place, but the function itself comes with single underscore.

**Comment by FunnyPixel** [comment]
I am on 3.1.23. For me,what's strange is that the compiler should somehow guess that these two functions are related. Why there is a need for __ double underscore of the function call? Is that a rule to call C functions from within EMSCRIPTEN_KEEPALIVE? I will check your sample.

**Comment by FunnyPixel** [comment]
> he extra leading underscore added to public symbols is a fairly common feature of C compilers (usually that's not visible to regular code, it's only important to the linker, or when calling those functions from another language).

But that's exactly what I am saying - you got that __ double underscore in the code. Here it is in your code:



```
EM_JS(void, sapp_js_add_beforeunload_listener, (void), {
    Module.sokol_beforeunload = (event) => {
        if (**__sapp_html5_get_ask_leave_site()** != 0) {
            event.preventDefault();
            event.returnValue = ' ';
        }
    };
    window.addEventListener('beforeunload', Module.sokol_beforeunload);
});
```

It is already with underscore. If you run in Firefox you don't get that error?

**Comment by floooh** [comment]
That extra underscore is needed because the call happens from Javascript code, not from C code.

When I remove that underscore, I get a compiler error (from the Closure Javascript compiler):

```
ERROR: Closure compiler run failed:

building:ERROR: /var/folders/dz/g9ydwg8973z9nn5bvffcwf3h0000gn/T/emscripten_temp_xurs504e/imgui-highdpi-sapp.js.jso.js.jso.js.jso.js.jso.js:555:6: ERROR - [JSC_UNDEFINED_VARIABLE] variable _sapp_html5_get_ask_leave_site is undeclared
  555|   if (_sapp_html5_get_ask_leave_site() != 0) {
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 error(s), 0 warning(s)
```

**Comment by floooh** [comment]
PS: Firefox works too here (it would be very surprising if it differed by browser):

<img width="864" alt="Screenshot 2023-05-09 at 18 50 02" src="https://github.com/floooh/sokol/assets/1699414/a3f62cf4-c055-415b-8a3b-eb5f1f3f4e8c">

...it must be something about the build process or compile options...

**Comment by floooh** [comment]
Closing this issue, if this is still an issue please feel free to re-open with new information :)
