### ISSUE TITLE
sokol_gfx: offscreen texture binding not becoming active (OpenGL) when writing to the frame buffer

### ISSUE THREAD

**Issue by tanis2000** [floooh/sokol#828]
I have an example project that is using an offscreen texture to render all the elements and then that offscreen texture is being used to plot the result to a quad on the frame buffer. 

For some reason, when the offscreen texture is going to be bound to be used by the shader that draws to the frame buffer, there is no call to `glBindTexture` happening (I checked that with RenderDoc).

Here is the sample project: https://github.com/tanis2000/binocle-c-examples/tree/master/spritebatch

What is happening is that the last bound texture will still be the active one.. so if I was drawing a sprite, its texture will be the one that gets activated last and then drawn as a full-screen quad to the frame buffer.
In this case the last drawn element is some text and in fact the texture being bound last is the one with the bitmap font.

I noticed that when the code hits https://github.com/floooh/sokol/blob/9b93f0fd31baa61537d706920cf254e595029587/sokol_gfx.h#L7648 the value of gl_tex_slot of the offscreen texture is -1 and the following section of the code that is supposed to bind the new texture is being skipped.

Any help is highly appreciated 😄

**Comment by tanis2000** [comment]
Figured it our. @floooh you were right.

https://github.com/floooh/sokol/blob/9b93f0fd31baa61537d706920cf254e595029587/sokol_gfx.h#L6979-L6987

When the uniform for the sampler2d is being looked up, it can't find it (because I am dumb and I used the wrong uniform name of course!).
Is there any chance to get a warning when this happens? Or maybe enable a kind of debug version of sokol_gfx that is providing verbose error checks that you do not want to run in your production code to avoid performance issues?

**Comment by floooh** [comment]
Yes I'll add some sort of warning through the regular logging callback. This means the warning message has to be generic (e.g. I can't add the uniform name it's looking for), but at least it's not silent anymore, and it's telling you the source location so you can set a debugger breakpoint and get the uniform name from inside the debugger.

I'll keep the issue open until I added the warning.

**Comment by floooh** [comment]
There's actually already a similar warning for mismatching vertex attribute names here:

https://github.com/floooh/sokol/blob/9b93f0fd31baa61537d706920cf254e595029587/sokol_gfx.h#L7062-L7065

...I've added the same for texture name mismatch, it looks a bit messy, but it gives you all the information:

```
[sg][error][id:8] /Users/floh/projects/sokol/sokol_gfx.h:6988:0: 
	GL_TEXTURE_NAME_NOT_FOUND_IN_SHADER: texture name not found in shader (gl)

[sg][info][id:8] /Users/floh/projects/sokol/sokol_gfx.h:6989:0: 
	blabla
```

(this is trying to look up a non-existing texture `blabla` in the shader)

**Comment by tanis2000** [comment]
That’s definitely going to help. Thanks a ton Andre!
