### ISSUE TITLE
sokol_gfx.h: add a sg_append_buffer() function

### ISSUE THREAD

**Issue by floooh** [floooh/sokol#85]
This would relax the "one update per buffer per frame" rule without making the public API and internal implementation more complicated.

An application can call sg_append_buffer() multiple times per frame on the same buffer, and it would strictly append data to the same buffer (never overwrite existing data). An sg_append_buffer() call can be followed by a draw call, as long as the draw call only uses the currently valid buffer data (this is already possible now). The internal buffer rotation system would remain unchanged, and the internal "append position" would be reset to the start of the buffer each frame.

See this thread for motivation and details: https://github.com/floooh/sokol/issues/84

**Comment by floooh** [comment]
[ ] Metal implementation
[ ] GL implementation
[ ] D3D11 implementation

[ ] test Metal on macOS
[ ] test Metal on iOS
[ ] test GL on iOS
[ ] test on HTML5
[ ] test on GLFW (Windows)
[ ] test on GLFW (Linux)
[ ] test on D3D11

**Comment by Alzathar** [comment]
@floooh If you are interested, I tested the function `sg_append_buffer()` on macOS 10.12.6 with GLFW 3.3dev + ImGui 1.66WIP using the code proposed in this comment https://github.com/floooh/sokol/issues/84#issuecomment-432970935 for both UINT16 and UINT32 index types. Everything works like a charm! Thanks a lot!

**Comment by floooh** [comment]
Thanks! I think everything is complete now, going to merge this now.

**Comment by floooh** [comment]
Ok, this has been merged into master now.
