### ISSUE TITLE
I've created a discord server for Sokol

### ISSUE THREAD

**Issue by jeangit** [floooh/sokol#857]
Hello,

I've created a discord server for Sokol, as it doesn't seem it's already exist.
I'm rather IRC, but the new kids on the (code)block seem to like better discord, so let's get modern.

@floooh 
If you don't agree with that, tell me and i will remove the server.
If you want i can transfer you the admin role.

The invite link is:
https://discord.gg/7f8Ak6zm

**Comment by floooh** [comment]
Go ahead but please don't expect me to get involved ;)

I will probably open up the Github Wiki and Discussions feature in the future once using Issues for questions becomes to messy, but I'm really not a fan of using a chat platform for this type of stuff.

**Comment by jeangit** [comment]
Yes i understand.
I prefer the classic forums that have a greater retention, but it was more work to create one.
Let's see what it turns out !

**Comment by brytonsf** [comment]
@jeangit your invite link has expired, could you share it again please?

I think an unofficial discord would be cool as well. At very least, some place where people are free to talk about Sokol.
The only chat I see for this is on Twitter, and it's like 1 post every 2 weeks by 1 person.

**Comment by jeangit** [comment]
Sorry @brytonsf , the chan has been removed due to lack of activity. May be IRC will be better, next time :)

**Comment by squk** [comment]
> Hello,
> 
> I've created a discord server for Sokol, as it doesn't seem it's already exist. I'm rather IRC, but the new kids on the (code)block seem to like better discord, so let's get modern.
> 
> [@floooh](https://github.com/floooh) If you don't agree with that, tell me and i will remove the server. If you want i can transfer you the admin role.
> 
> The invite link is: https://discord.gg/7f8Ak6zm

Your link is expired
