### ISSUE TITLE
Add missing built-in cursors.

### ISSUE THREAD

**Issue by skejeton** [floooh/sokol#864]
Missing cursors in question:

* Wait cursor; Hourglass/Spinning wheel cursor
  ![Wait cursor](https://github.com/floooh/sokol/assets/27076041/38ce6e07-2d7d-4d7b-b1ac-c19f2aad43e4)

* Wait with arrow cursor; Hourglass/Spinning wheel with arrow cursor
  ![Wait with arrow cursor](https://github.com/floooh/sokol/assets/27076041/41a4bcbf-e4a7-466a-a25b-845f75520c14)

* (Not as necessary) Help cursor; Arrow with question mark cursor 
  ![Help cursor](https://github.com/floooh/sokol/assets/27076041/ef2c62ed-5aab-4f2a-bded-75a897500b14)

**Comment by floooh** [comment]
These cursor images are not standardized across operating systems, sokol_app.h basically can only implement the subset of cursor images that are available on all platforms. GLFW basically already did that research, and sokol_app.h is just following the GLFW convention.
