### ISSUE TITLE
sokol_gfx: UBOs for OpenGL ?

### ISSUE THREAD

**Issue by septag** [floooh/sokol#88]
I'm trying out OpenGL 3.3 implementation, my shaders include uniform buffer objects, but it seems that the GL implementation doesn't support it, and assumes that all uniforms are declared outside of uniform buffer. Am I right ?
If yes, is there a reason for this ?

**Comment by floooh** [comment]
Yes, GL uniform buffer objects are surprisingly useless, especially on GLES3 (more details below) Once there's an "official" cross-platform-shader solution in sokol_gfx similar to what I did in Oryol, it will work like this:

- you author shaders in "desktop GLSL", using uniform blocks
- the shader code generator will translate this source-GLSL into all required shader dialects and versions (HLSL, MetalSL and the various required GL/GLES versions)
- the uniform blocks in the original shader source code will be translated into a single vec4 array (one vec4 array per uniform block)
- each call to sg_apply_uniform_block() will then result in a single call to glUniform4fv(), which is just as efficient (on some platforms: more efficient) than using uniform buffers

There will be no changes required for this in sokol_gfx.h.

Links:
- Fortnite on Android is using the same technique: https://www.epicgames.com/fortnite/en-US/news/fortnite-on-android-launch-technical-blog
- my original implementation plan for GL uniform buffer support in Oryol, which I had completely implemented and found to be not faster then the old solution, so removed it again: https://floooh.github.io/2016/10/06/oryol-webgl2.html (this was before I switched to the "single vec4 array solution", which was only possible with the shader code generation)
- why I didn't keep this code in: https://floooh.github.io/2017/04/04/oryol-webgl2-merge.html
- how the Oryol shader code generation works, for sokol-gfx it will be similar, but with less build-system complexity (I hope to drop python and do everything in a single standalone cmdline tool): https://floooh.github.io/2017/05/15/oryol-spirv.html

**Comment by septag** [comment]
Thanks for the thorough explanation.
Yes, actually I read the fortnite article some time ago, saw the feature in spirv-cross and decided to do something similar to what you did in your article. I mixed the glslang and spirv-cross and made my own tool for cross compiling glsl - [glslcc](https://github.com/septag/glslcc)

But I haven't experimented with OpenGL/ES ubos, and thought that UBOs should perform like constant buffers in d3d..

**Comment by floooh** [comment]
Nice tool :) This is exactly what I have in mind for sokol too, I'm not sure yet how hardwired the code generation will be for sokol_gfx.h though.

**Comment by mchiasson** [comment]
Oh wow! ran into the same exact situation: Created a tool based of glslang + spirv-cross, which spits out uniform buffers which doesn't work in Sokol and why is everyone having the same idea?! LOL

**Comment by floooh** [comment]
@mchiasson the sokol-shdc tool (which was created after this thread) 'flattens' shader uniform blocks in to vec4 arrays, so that they can be updated with a single glUniform4fv() call in the sokol-gfx GL backend.

https://github.com/floooh/sokol-tools/blob/master/docs/sokol-shdc.md

It's currently limited to uniform blocks with float types (no int or bool), and this limitation is currently in sokol_gfx.h, but that will probably be one of the next things I'll work on.

**Comment by mchiasson** [comment]
ohhh! just like the `--flatten-ubo` argument from spirv-cross? because that's exactly what I ended up using :grin:
