### ISSUE TITLE
Some way to sponsor the project in the readme

### ISSUE THREAD

**Issue by creikey** [floooh/sokol#901]
Sokol is really awesome, I use it heavily and I think you should be paid to maintain/work on it, so I scrolled to the readme but couldn't see any patreon/kofi/sponsorship information where I could chuck a little money. Does such a thing exist? If so I would gladly pay (and hopefully others)

**Comment by floooh** [comment]
There's currently no way to sponsor the project and I'd like to keep it that way :)
