### ISSUE TITLE
Misleading error message VALIDATE_ABND_FS_EXPECTED_IMAGE_BINDING

### ISSUE THREAD

**Issue by danielchasehooper** [floooh/sokol#918]
This error message can be confusing when you *did* assign to the slot, but the `sg_image.id` is zero:
`sg_apply_bindings: missing image binding on fragment stage`
```c
    sg_apply_bindings(&(sg_bindings){
        .vertex_buffers[0] = g_square_vertex_buffer,
        .fs.images[SLOT_tex] = src, // look the image binding is right here!
        .fs.samplers[SLOT_smp] = linear_sampler, 
    });
```

I think it'd be helpful if the message were updated to make it clear that either the bound image is zero or you didn't even specify the binding

**Comment by floooh** [comment]
Hmm good point, but unfortunately in that case sokol-gfx cannot differentiate between the bind slot being assigned an invalid handle (SG_INVALID_ID), and the slot not being set in the first place. In both cases there's a zero in `.fs.images[SLOT_tex].id`

The actual test in the validation layer is `bindings->fs.images[i].id != SG_INVALID_ID` (where `SG_INVALID_ID` is defined as zero).

Any ideas for a better error message in that case? (e.g. the bind slot is either not set, or the image handle is invalid).

**Comment by danielchasehooper** [comment]
Maybe `sg_apply_bindings: image binding is either missing or set to a sg_image with id 0`?
`sg_apply_bindings: image binding is either missing or set to an uninitialized sg_image`?
