### ISSUE TITLE
Something wrong with WebGPU

### ISSUE THREAD

**Issue by ryuukk** [floooh/sokol#920]
https://floooh.github.io/sokol-html5/spine-inspector-sapp.html

![image](https://github.com/floooh/sokol/assets/44361234/a45cf19c-a4d5-4aee-b519-16ecef6690a0)

https://floooh.github.io/sokol-webgpu/spine-inspector-sapp.html

![image](https://github.com/floooh/sokol/assets/44361234/dfd36f0c-9b99-4e8c-b161-93c4e6d498a7)

WebGPU is darker

**Comment by floooh** [comment]
What device, platform and browser is this?

**Comment by floooh** [comment]
Wait! I can reproduce on Chrome macOS, why didn't I notice this before?

**Comment by floooh** [comment]
Might be some sort of SRGBA problem, the texcube sample which uses fully saturated colors looks identical.

I'll investigate. It must be a somewhat recent regression, otherwise I would have noticed it during development.

**Comment by floooh** [comment]
Ah silly me:

https://github.com/floooh/sokol/blob/08ae58e275decf36ca932ac8be3469556a46992f/sokol_gfx.h#L12787-L12788

I remember that I added the SRGB format sort of last minute before merging. I should be more careful. Fix incoming

**Comment by floooh** [comment]
Ok fixed, webpage will be updated when this CI job finishes: https://github.com/floooh/sokol-samples/actions/runs/6611073889

Thanks for the bug report!
