### ISSUE TITLE
What is the recommended version that still supports GLES2? 

### ISSUE THREAD

**Issue by tmikov** [floooh/sokol#934]
Is the `gles2` tag the best bet when checking out a working version with GLES2 support?

**Comment by floooh** [comment]
https://github.com/floooh/sokol/releases/tag/gles2

The sokol-shdc compiler is missing the tag though, you'll probably need to combine that with the following sokol-shdc version:

https://github.com/floooh/sokol-tools-bin/releases/tag/pre-separate-samplers
