### ISSUE TITLE
Expose _sg_pixelformat_bytesize to users?

### ISSUE THREAD

**Issue by logankaser** [floooh/sokol#946]
`_sg_pixelformat_bytesize` Would be useful to expose to users.
I have a texture manager abstraction that internally creates sg_images.
Its API accepts `sg_pixel_format`(s) from callers, and width and height parameters,
and it would be nice to be able to use `_sg_pixelformat_bytesize` to calculate data size.

**Comment by floooh** [comment]
I would prefer adding that as a field to `sg_pixelformat_info` returned by the `sg_query_pixelformat` call.

Thoughts?

**Comment by logankaser** [comment]
That seems like a great place to add it!

**Comment by floooh** [comment]
I'll start looking into this today.

**Comment by floooh** [comment]
Ok, this is now merged. I also exposed the helper functions to compute the number of bytes in a texture row and surface, which might actually be a bit more useful.

Details are in the changelog https://github.com/floooh/sokol/blob/master/CHANGELOG.md#06-jan-2024, and also in the sokol_gfx.h documentation comments.
