### ISSUE TITLE
sokol_nuklear.h: how to know if nuklear handled an event

### ISSUE THREAD

**Issue by adamrt** [floooh/sokol#958]
Hi is there a standard way to know if nuklear handled an event in the same way we can with imgui?         `void snk_handle_event(const sapp_event* ev);` doesn't return anything and the state is isn't public. I have some ideas for a patch but wanted to make sure that I wasn't missing something obvious.

Thank you for such a rad library.

**Comment by floooh** [comment]
Yeah you're right, there currently isn't a way to check. If you have an idea I'm open for a PR :)

(I think it's ok to just add a bool return value to the existing snk_handle_event() function, since existing code would still compile and work)

**Comment by adamrt** [comment]
PR: https://github.com/floooh/sokol/pull/959

**Comment by floooh** [comment]
Closing as fixed since PR #959 has been merged.
