### ISSUE TITLE
sokol_app.h: Full GLES support

### ISSUE THREAD

**Issue by automainint** [floooh/sokol#966]
Currently, GLES support is missing on
- [ ] Linux with GLX;
- [ ] Windows;
- [ ] macOS.

My implementation for Linux: #965 
I don't have a Windows or macOS machine, so I can't do those.

**Comment by floooh** [comment]
Adding new GL related functionality on macOS doesn't make a lot of sense, since Apple has deprecated OpenGL on Mac (and since macOS also only supports the OpenGL Core Profile, GLES, wouldn't be supported anyway).

Also as I wrote in the PR, unless there's a very good reason why supporting GLES on desktop operating systems is needed, I'm not a big fan of the idea since it leads to more configurations that need to be tested.

**Comment by automainint** [comment]
The reason is to have one graphics API on all platforms, as a wrote in the PR comment

> Apple has deprecated OpenGL

That's very unfortunate. But it's weird, they still run WebGL in browser, so they must have some kind of support for it, do they plan to cross-compile shaders to Metal? I'm also looking into shader cross-compilation, but I hoped to have a capacity to just use a single API.

**Comment by floooh** [comment]
> they still run WebGL in browser, so they must have some kind of support for it

WebGL is running on top of Metal in Safari (via the ANGLE library - same on Windows btw, WebGL is actually running on top of D3D11 via ANGLE, not OpenGL). Apple's native OpenGL implementation has been frozen at 4.1 and is also running on top of Metal for quite a while now.

> The reason is to have one graphics API on all platforms, as a wrote in the PR comment

It wouldn't be supported out of the box on Windows and macOS without a third party library (ANGLE). If you want to author shaders in a single shading language, the best option is to use on the shader cross-compiling tools (like Google's shahderc, the SPRIVCross command line tool, or sokol-shdc.

**Comment by floooh** [comment]
I'm closing this ticket since it turned out to be a dead-end (sokol_app.h supports creating a GLES3 context in the Linux backend via EGL, but on other platforms that's impossible or would require linking with ANGLE).
